Repository particle-iot/device-os, pull requests merged in 2018-12, with the labels that each got.

#1617 Fixes user part update procedure in hybrid build
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/user.cpp
  hal/src/nRF52840/user.h
  system/src/system_task.cpp
Labels: bug, mesh

#1619 Do not log WiFi passwords
  hal/network/ncp/at_parser/at_parser.cpp
  hal/network/ncp/at_parser/at_parser.h
  hal/network/ncp/at_parser/at_parser_impl.cpp
  hal/network/ncp/at_parser/at_parser_impl.h
  hal/src/argon/network/esp32_ncp_client.cpp
Labels: enhancement, mesh, ready to merge

#1621 [nrf52840] Enables power failure comparator on boot with a registered power failure handler that resets the device
  platform/MCU/nRF52840/inc/sdk_config_bootloader.h
  platform/MCU/nRF52840/inc/sdk_config_system.h
  platform/MCU/nRF52840/src/hw_config.c
Labels: mesh, needs review

#1581 [Electron/LTE] Power Manager Watchdog Timer Fix
  system/src/system_power.cpp
  system/src/system_power_manager.cpp
  system/src/system_power_manager.h
  wiring/src/spark_wiring_power.cpp
Labels: bug

#1622 Do not disable interrupts on every system loop iteration
  system/inc/active_object.h
  system/src/active_object.cpp
Labels: bug, ready to merge

#1623 Do not set the sticky skip hello after handshake
  communication/src/protocol.cpp
Labels: bug, mesh, ready to merge

#1624 Do not set the sticky skip hello after handshake
  communication/src/protocol.cpp
Labels: bug, ready to merge

#1626 Fixes Network Manager initial state after network_setup()
  system/src/system_network_manager_api.cpp
Labels: bug, mesh

#1627 [LTE] AT+CNUM command causing registration failure on LTE devices
  hal/src/electron/modem/mdm_hal.cpp
Labels: bug

#1629 [OpenThread] Max transmit power setting (HAL_PLATFORM_OPENTHREAD_MAX_TX_POWER)
  hal/inc/hal_platform.h
  hal/network/openthread/ot_api.cpp
  hal/src/nRF52840/hal_platform_nrf52840_config.h
Labels: enhancement, mesh, needs review

#1633 [nrf52840] hal: enables Wire1 on Argon and Xenon by defining HAL_PLATFORM_I2C2 in common platform config
  hal/src/boron/hal_platform_config.h
  hal/src/nRF52840/hal_platform_nrf52840_config.h
Labels: bug, mesh, ready to merge

#1635 [Photon] Memory usage optimizations
  hal/src/photon/miniz.h
Labels: enhancement, ready to merge

#1639 Invalidate sockets when turning WiFi off
  hal/src/photon/socket_hal.cpp
  hal/src/photon/wlan_hal.cpp
  system/src/system_cloud_internal.cpp
Labels: bug, ready to merge

#1640 Cache persistent feature flags
  hal/src/stm32f2xx/core_hal_stm32f2xx.c
Labels: bug, ready to merge

#1528 Wait for Wiring Thread to start
  user/tests/wiring/api/thread.cpp
  user/tests/wiring/no_fixture/thread.cpp
  wiring/inc/spark_wiring_thread.h
Labels: bug, regression

#1636 [nrf52840] hal: implements __assert_func() to handle libc assert()
  hal/src/nRF52840/newlib.cpp
  rt-dynalib/inc/rt_dynalib.h
Labels: enhancement, mesh, ready to merge

#1638 Fixes to the Argon in Listening Mode showing wrong MAC address with the command `m`.
  hal/network/lwip/esp32/esp32ncpnetif.cpp
  hal/network/lwip/esp32/esp32ncpnetif.h
  hal/src/argon/wlan_hal.cpp
  system/src/system_setup.cpp
Labels: bug, mesh, ready to merge

#1645 [argon] ncp: updateFirmware() after the NCP reset needs to re-enable the client
  hal/src/argon/network/esp32_ncp_client.cpp
Labels: bug, mesh, ready to merge

#1650 Execute button and OOM event handlers synchronously
  system/inc/system_event.h
  system/src/main.cpp
  system/src/system_event.cpp
  user/tests/wiring/no_fixture/system.cpp
Labels: needs review, regression

#1652 Fixes an assertion failure (SOS 10) with Mesh.subscribe() and threading enabled
  hal/network/lwip/openthread/lwip_openthreadif.cpp
  wiring/src/spark_wiring_udp_posix.cpp
Labels: bug, mesh, needs review
