Repository particle-iot/device-os, pull requests merged in 2018-11, with the labels that each got.

#1585 [Mesh] Network system events
  system/src/system_listening_mode.cpp
  system/src/system_listening_mode.h
  system/src/system_network_manager.cpp
  system/src/system_network_manager_api.cpp
Labels: mesh, ready to merge

#1588 Feature/hal/spi slave
  hal/src/nRF52840/spi_hal.cpp
  platform/MCU/nRF52840/inc/sdk_config_system.h
  user/tests/wiring/spi_master_slave/spi_slave/spi_slave.cpp
Labels: mesh, ready to merge

#1589 Feature/hal/servo
  hal/inc/servo_hal.h
  hal/src/nRF52840/pinmap_impl.h
  hal/src/nRF52840/pwm_hal.cpp
  hal/src/nRF52840/servo_hal.cpp
Labels: mesh, ready to merge

#1591 Implement I2C Slave
  hal/inc/i2c_hal.h
  hal/src/nRF52840/i2c_hal.cpp
  platform/MCU/nRF52840/inc/sdk_config_system.h
Labels: mesh, ready to merge

#1593 [Mesh] mbedtls: adds hardware accelerated sha1
  hal/src/nRF52840/mbedtls/mbedtls_config_platform.h
  hal/src/nRF52840/mbedtls/sha1_alt.h
  hal/src/nRF52840/mbedtls/sha1_alt_cc310.c
Labels: enhancement, mesh, ready to merge

#1595 [Mesh] Adds DHCP hostname for Ethernet and WiFi interfaces
  hal/network/lwip/esp32/esp32ncpnetif.cpp
  hal/network/lwip/esp32/esp32ncpnetif.h
  hal/network/lwip/ifapi.cpp
  hal/network/lwip/wiznet/wiznetif.cpp
  hal/network/lwip/wiznet/wiznetif.h
  hal/src/nRF52840/lwip/lwipopts.h
Labels: enhancement, mesh, ready to merge

#1599 _CONST was dropped in Newlib 3.0.0
  services/inc/printf_export.h
Labels: enhancement, mesh, ready to merge

#1609 [network] nat64: randomize base source port on boot
  hal/network/lwip/nat64.cpp
Labels: enhancement, mesh, ready to merge

#1610 [Gen 3] Some LwIP optimizations
  hal/network/lwip/ppp_client.cpp
  hal/network/lwip/ppp_client.h
  hal/network/lwip/ppp_ipcp.cpp
  hal/network/lwip/ppp_ipcp.h
  hal/network/lwip/ppp_ncp.cpp
  hal/network/lwip/ppp_ncp.h
  hal/src/nRF52840/lwip/lwipopts.h
  hal/src/nRF52840/lwip/lwippppopts.h
  wiring/inc/spark_wiring_posix_common.h
Labels: bug, enhancement, mesh, ready to merge

#1584 [Boron] Fixes a race condition on startup from cold boot (U201)
  hal/src/boron/network/sara_ncp_client.cpp
  hal/src/nRF52840/core_hal.c
Labels: enhancement, mesh, ready to merge

#1613 [boron] cellular_hal: fixes a crash with STARTUP() macros and credentials management functions
  hal/src/boron/cellular_hal.cpp
Labels: bug, mesh, ready to merge

#1615 Mark Gen 3 platforms as prerelease
  .buildpackrc
Labels: mesh, ready to merge
