Repository particle-iot/device-os, pull requests merged in 2018-04, with the labels that each got.

#1500 Photon/P1: A number of networking-related fixes [v2]
  hal/src/photon/lib/FreeRTOS/LwIP.a
  hal/src/photon/lib/FreeRTOS/WICED_LwIP_Interface.a
  hal/src/photon/socket_hal.cpp
  hal/src/photon/wlan_hal.cpp
  system/src/system_cloud_internal.cpp
  wiring/inc/spark_wiring_tcpclient.h
  wiring/src/spark_wiring_tcpclient.cpp
  wiring/src/spark_wiring_tcpserver.cpp
Labels: bug, enhancement

#1492 Photon/P1: A number of networking-related fixes
  communication/src/ping.h
  hal/src/photon/lib/FreeRTOS/FreeRTOS.a
  hal/src/photon/lib/FreeRTOS/Lib_DHCP_Server.a
  hal/src/photon/lib/FreeRTOS/Lib_DNS.a
  hal/src/photon/lib/FreeRTOS/Lib_DNS_Redirect_Daemon.a
  hal/src/photon/lib/FreeRTOS/LwIP.a
  hal/src/photon/lib/FreeRTOS/Platform_BCM9WCDUSI09.a
  hal/src/photon/lib/FreeRTOS/STM32F2xx.a
  hal/src/photon/lib/FreeRTOS/STM32F2xx_Peripheral_Drivers.a
  hal/src/photon/lib/FreeRTOS/WICED.a
  hal/src/photon/lib/FreeRTOS/WICED_FreeRTOS_Interface.a
  hal/src/photon/lib/FreeRTOS/WICED_LwIP_Interface.a
  hal/src/photon/lib/FreeRTOS/WWD_FreeRTOS_Interface_BCM9WCDUSI09.a
  hal/src/photon/lib/FreeRTOS/WWD_LwIP_Interface_FreeRTOS.a
  hal/src/photon/lib/FreeRTOS/WWD_for_SDIO_FreeRTOS.a
  hal/src/photon/lib/FreeRTOS/Wiced_Network_LwIP_FreeRTOS.a
  hal/src/photon/lib/Lib_HTTP_Server.a
  hal/src/photon/lib/Lib_Linked_List.a
  hal/src/photon/lib/Lib_Ring_Buffer.a
  hal/src/photon/lib/Lib_SPI_Flash_Library_BCM9WCDUSI09.a
  hal/src/photon/lib/Lib_TLV.a
  hal/src/photon/lib/Lib_Wiced_RO_FS.a
  hal/src/photon/lib/Lib_base64.a
  hal/src/photon/lib/Lib_crc.a
  hal/src/photon/lib/Lib_crypto_open.a
  hal/src/photon/lib/Lib_micro_ecc.a
  hal/src/photon/lib/STM32F2xx_Peripheral_Libraries.a
  hal/src/photon/lib/Supplicant_BESL.a
  hal/src/photon/lib/common_GCC.a
  hal/src/photon/lib/resources.a
  hal/src/photon/socket_hal.cpp
  hal/src/photon/wlan_hal.cpp
  system/src/system_cloud_internal.cpp
  system/src/system_network_internal.h
  wiring/inc/spark_wiring_tcpclient.h
  wiring/src/spark_wiring_tcpclient.cpp
  wiring/src/spark_wiring_tcpserver.cpp
Labels: bug

#1501 [Photon/P1] Enables support for SHA384/SHA512 certificates for WPA Enterprise
  crypto/inc/crypto_dynalib.h
  crypto/inc/mbedtls_config_photon.h
  crypto/inc/mbedtls_weaken.h
  hal/src/photon/crypto_compat.cpp
  hal/src/photon/lib/BESL.ARM_CM3.release.a
  hal/src/photon/lib/FreeRTOS/FreeRTOS.a
  hal/src/photon/lib/FreeRTOS/Lib_DHCP_Server.a
  hal/src/photon/lib/FreeRTOS/Lib_DNS.a
  hal/src/photon/lib/FreeRTOS/Lib_DNS_Redirect_Daemon.a
  hal/src/photon/lib/FreeRTOS/LwIP.a
  hal/src/photon/lib/FreeRTOS/Platform_BCM9WCDUSI09.a
  hal/src/photon/lib/FreeRTOS/Platform_BCM9WCDUSI14.a
  hal/src/photon/lib/FreeRTOS/STM32F2xx.a
  hal/src/photon/lib/FreeRTOS/STM32F2xx_Peripheral_Drivers.a
  hal/src/photon/lib/FreeRTOS/STM32F2xx_bootloader.a
  hal/src/photon/lib/FreeRTOS/WICED.a
  hal/src/photon/lib/FreeRTOS/WICED_FreeRTOS_Interface.a
  hal/src/photon/lib/FreeRTOS/WICED_LwIP_Interface.a
  hal/src/photon/lib/FreeRTOS/WWD_FreeRTOS_Interface_BCM9WCDUSI09.a
  hal/src/photon/lib/FreeRTOS/WWD_FreeRTOS_Interface_BCM9WCDUSI14.a
  hal/src/photon/lib/FreeRTOS/WWD_LwIP_Interface_FreeRTOS.a
  hal/src/photon/lib/FreeRTOS/WWD_for_SDIO_FreeRTOS.a
  hal/src/photon/lib/FreeRTOS/Wiced_Network_LwIP_FreeRTOS.a
  hal/src/photon/lib/Lib_HTTP_Server.a
  hal/src/photon/lib/Lib_Linked_List.a
  hal/src/photon/lib/Lib_Ring_Buffer.a
  hal/src/photon/lib/Lib_SPI_Flash_Library_BCM9WCDUSI09.a
  hal/src/photon/lib/Lib_SPI_Flash_Library_BCM9WCDUSI14.a
  hal/src/photon/lib/Lib_TLV.a
  hal/src/photon/lib/Lib_Wiced_RO_FS.a
  hal/src/photon/lib/Lib_base64.a
  hal/src/photon/lib/Lib_crc.a
  hal/src/photon/lib/Lib_crypto_open.a
  hal/src/photon/lib/Lib_crypto_open_part2.a
  hal/src/photon/lib/Lib_micro_ecc.a
  hal/src/photon/lib/STM32F2xx_Peripheral_Libraries.a
  hal/src/photon/lib/Supplicant_BESL.a
  hal/src/photon/lib/common_GCC.a
  hal/src/photon/lib/resources.a
  hal/src/photon/libraries/daemons/HTTP_server/http_server.h
  hal/src/photon/wiced/security/BESL/host/WICED/tls_cipher_suites.h
Labels: enhancement

#1517 [Photon/P1/Electron] Recursive logging freezes the application thread while the LogHandler is trying to acquire a lock on the resource.
  user/tests/wiring/no_fixture/logging.cpp
  wiring/inc/spark_wiring_logging.h
  wiring/src/spark_wiring_logging.cpp
Labels: bug
