Repository particle-iot/device-os, pull requests merged in 2019-04, with the labels that each got.

#1741 [bootloader] SysTick needs to be disabled in Reset_System() on Gen 2 platforms
  platform/MCU/STM32F1xx/SPARK_Firmware_Driver/inc/hw_config.h
  platform/MCU/STM32F1xx/SPARK_Firmware_Driver/src/hw_config.c
  platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/hw_config.c
Labels: bug, ready to merge

#1739 [hal] Correct ADC channel number for SoM
  hal/src/nRF52840/pinmap_hal.c
Labels: bug, ready to merge

#1743 [photon/p1] crypto: re-enables MD5 for TLS (WPA Enterprise)
  crypto/inc/crypto_dynalib.h
  crypto/inc/mbedtls_config_photon.h
  crypto/inc/mbedtls_weaken.h
Labels: bug, ready to merge

#1747 release/v1.1.0-rc.1
  CHANGELOG.md
  build/release.sh
  build/version.mk
  hal/src/stm32f2xx/bootloader_platform_10.c
  hal/src/stm32f2xx/bootloader_platform_6.c
  hal/src/stm32f2xx/bootloader_platform_8.c
  modules/shared/system_module_version.mk
  system/inc/system_version.h
  system/system-versions.md
  user/tests/release-tests.json
Labels: do not merge, needs review

#1751 Remove the message "External flash is not supported" from Gen 3 builds
  system/src/control/storage.cpp
Labels: enhancement, ready to merge

#1750 Do not fail the build if PARTICLE_DEVELOP is not defined
  build/checks.mk
  docs/build.md
Labels: internal, ready to merge

#1755 [Photon/P1] Fixes 802.11n mode
  hal/src/photon/lib/FreeRTOS/WWD_for_SDIO_FreeRTOS.a
Labels: bug, ready to merge, regression

#1756 [Gen 3] Updates embedded bootloader
  CHANGELOG.md
  build/release.sh
  build/version.mk
  hal/src/argon/bootloader_platform_12.c
  hal/src/boron/bootloader_platform_13.c
  hal/src/xenon/bootloader_platform_14.c
  modules/shared/system_module_version.mk
  system/inc/system_version.h
  system/system-versions.md
Labels: bug, ready to merge

#1754 Shared Gen3 module code
  modules/argon/system-part1/src/export_rt.c
  modules/argon/system-part1/src/export_system.cpp
  modules/argon/system-part1/src/import_user.c
  modules/argon/system-part1/src/module_info.c
  modules/argon/system-part1/src/module_system_part1.cpp
  modules/argon/user-part/src/module_info.c
  modules/argon/user-part/src/newlib_stubs.cpp
  modules/argon/user-part/src/user_export.c
  modules/argon/user-part/src/user_module.c
  modules/boron/system-part1/src/export_rt.c
  modules/boron/system-part1/src/export_system.cpp
  modules/boron/system-part1/src/import_user.c
  modules/boron/system-part1/src/module_info.c
  modules/boron/system-part1/src/module_system_part1.cpp
  modules/boron/user-part/src/module_info.c
  modules/boron/user-part/src/newlib_stubs.cpp
  modules/boron/user-part/src/user_export.c
  modules/boron/user-part/src/user_module.c
  modules/shared/nRF52840/inc/system-part1/export_rt.inc
  modules/shared/nRF52840/inc/system-part1/export_system.inc
  modules/shared/nRF52840/inc/system-part1/import_user.inc
  modules/shared/nRF52840/inc/system-part1/module_system_part1.inc
  modules/shared/nRF52840/inc/user-part/newlib_stubs.inc
  modules/shared/nRF52840/inc/user-part/user_export.inc
  modules/shared/nRF52840/inc/user-part/user_module.inc
  modules/shared/nRF52840/part1_build.mk
  modules/shared/nRF52840/user_build.mk
  modules/xenon/system-part1/src/export_rt.c
  modules/xenon/system-part1/src/export_system.cpp
  modules/xenon/system-part1/src/import_user.c
  modules/xenon/system-part1/src/module_info.c
  modules/xenon/system-part1/src/module_system_part1.cpp
  modules/xenon/user-part/src/module_info.c
  modules/xenon/user-part/src/newlib_stubs.cpp
  modules/xenon/user-part/src/user_export.c
  modules/xenon/user-part/src/user_module.c
Labels: internal, ready to merge
