Repository particle-iot/device-os, pull requests merged in 2019-10, with the labels that each got.

#1933 Implement Mesh.selectAntenna()
  hal-dynalib/src/hal_mesh.c
  hal/inc/ble_hal.h
  hal/inc/hal_dynalib_mesh.h
  hal/inc/hal_platform.h
  hal/inc/mesh_hal.h
  hal/inc/radio_hal.h
  hal/src/argon/hal_platform_config.h
  hal/src/boron/hal_platform_config.h
  hal/src/nRF52840/ble_hal.cpp
  hal/src/nRF52840/hal_dynalib_export.cpp
  hal/src/nRF52840/mesh_hal.cpp
  hal/src/nRF52840/openthread/system.c
  hal/src/nRF52840/radio_common.cpp
  hal/src/nRF52840/radio_common.h
  hal/src/xenon/hal_platform_config.h
  modules/argon/system-part1/module_system_part1_export.ld
  modules/boron/system-part1/module_system_part1_export.ld
  modules/shared/nRF52840/inc/system-part1/module_system_part1.inc
  modules/xenon/system-part1/module_system_part1_export.ld
  platform/MCU/nRF52840/inc/dct.h
  system/src/main.cpp
  wiring/inc/spark_wiring_mesh.h
  wiring/src/spark_wiring_mesh.cpp
Labels: enhancement, ready to merge

#1935 Send safe mode event when the session is resumed
  system/src/system_cloud_internal.cpp
Labels: bug, ready to merge

#1918 [wiring] Enable Wiring_SetupButtonUX feature for Boron
  hal/inc/hal_platform.h
  hal/inc/hal_platform_compat.h
  hal/src/boron/hal_platform_config.h
  system/src/main.cpp
  system/src/system_sleep.cpp
  system/src/system_task.cpp
  wiring/inc/spark_wiring_platform.h
Labels: bug, ready to merge

#1939 Fixes the attachInterrupt() fails for pin D7 on Boron
  hal/inc/hal_dynalib_gpio.h
  hal/inc/interrupts_hal.h
  hal/src/core/interrupts_hal.c
  hal/src/nRF52840/interrupts_hal.cpp
  hal/src/stm32f2xx/interrupts_hal.c
  hal/src/template/interrupts_hal.cpp
  user/tests/wiring/no_fixture/interrupts.cpp
  wiring/inc/spark_wiring_interrupts.h
  wiring/src/spark_wiring_interrupts.cpp
Labels: bug, ready to merge

#1944 Fixes D7 pin interrupt unit test: be #if instead of #ifdef
  user/tests/wiring/no_fixture/interrupts.cpp
Labels: internal, ready to merge

#1940 electron: use standalone DNS client for all modem types
  hal/src/electron/modem/mdm_hal.cpp
Labels: enhancement, ready to merge

#1941 [electron] enables modem logs in non-debug builds [ch35402]
  hal/src/electron/modem/electronserialpipe_hal.cpp
  hal/src/electron/modem/mdm_debug.h
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
  hal/src/electron/modem/pipe_hal.h
Labels: enhancement, ready to merge

#1945 [photon] wlan: limit WPA Enterprise maximum TLS version to 1.1
  hal/src/photon/wlan_hal.cpp
Labels: enhancement, ready to merge

#1943 Implement a command to reset all network interfaces of a device remotely
  system/src/system_cloud_internal.cpp
  system/src/system_network_internal.cpp
  system/src/system_network_internal.h
Labels: feature, ready to merge

#1938 [LTE, u-blox] adds a mitigation to keep DNS Client responsive [ch38990]
  hal/src/electron/modem/dns_client.cpp
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
Labels: bug, needs review

#1947 [test] i2c_mcp23017: implements HighPriorityInterruptInterferer for nRF52840-based platforms
  user/tests/wiring/i2c_mcp23017/interferer.cpp
  user/tests/wiring/i2c_mcp23017/interferer.h
Labels: internal, needs review

#1948 [nrf52840] platform: disable clock driver in Reset_System() before jumping into system firmware
  platform/MCU/nRF52840/src/hw_config.c
Labels: bug, ready to merge
