Repository particle-iot/device-os, pull requests merged in 2019-03, with the labels that each got.

#1662 Feature/mesh som
  .buildpackrc
  .travis.yml
  bootloader/src/nRF52840/usbd_device.cpp
  build/module.mk
  build/platform-id.mk
  ci/enumerate_build_matrix.sh
  communication/src/build.mk
  hal/inc/hal_dynalib_can.h
  hal/inc/hal_dynalib_wlan.h
  hal/inc/pinmap_hal.h
  hal/network/lwip/nat64.cpp
  hal/network/lwip/wiznet/wiznetif.cpp
  hal/network/openthread/border_router_manager.cpp
  hal/shared/platforms.h
  hal/src/argon/app_usbd_string_config.h
  hal/src/argon/bootloader_platform_22.c
  hal/src/argon/include.mk
  hal/src/argon/network/network.cpp
  hal/src/argon/user_platform_22.c
  hal/src/boron/app_usbd_string_config.h
  hal/src/boron/bootloader_platform_23.c
  hal/src/boron/hal_platform_config.h
  hal/src/boron/include.mk
  hal/src/boron/network/network.cpp
  hal/src/boron/user_platform_23.c
  hal/src/nRF52840/lwip/lwippppopts.h
  hal/src/nRF52840/openthread/system.c
  hal/src/nRF52840/pinmap_hal.c
  hal/src/nRF52840/rgbled_hal.c
  hal/src/nRF52840/spi_hal.cpp
  hal/src/nRF52840/usart_hal.cpp
  hal/src/xenon/app_usbd_string_config.h
  hal/src/xenon/bootloader_platform_24.c
  hal/src/xenon/include.mk
  hal/src/xenon/network/network.cpp
  hal/src/xenon/user_platform_24.c
  main/makefile
  modules/boron/modular.mk
  newlib_nano/src/sources.mk
  platform/MCU/nRF52840/inc/platform_config.h
  release-mesh.sh
  system/src/build.mk
  system/src/control/wifi.cpp
  system/src/system_task.cpp
  wiring/inc/fast_pin.h
Labels: feature, mesh, ready to merge

#1707 [hal] Fixes USBSerial SOS issue when removing USB cable from battery …
  hal/src/argon/network/esp32_ncp_client.cpp
  hal/src/boron/network/sara_ncp_client.cpp
  hal/src/nRF52840/usb_hal_cdc.c
Labels: bug, mesh, ready to merge

#1696 Fix/gen3 spi ss pin occupied
  hal/network/lwip/wiznet/wiznetif.cpp
  hal/src/nRF52840/spi_hal.cpp
Labels: bug, mesh, ready to merge

#1694 Fix/gen3 fix no fixture unit test
  hal/inc/pinmap_hal.h
  user/tests/wiring/no_fixture/gpio.cpp
  user/tests/wiring/no_fixture/led.cpp
  user/tests/wiring/no_fixture_long_running/pwm.cpp
  user/tests/wiring/no_fixture_long_running/ticks.cpp
  wiring/src/spark_wiring_wifitester.cpp
Labels: mesh, ready to merge

#1713 [core] system: disable logs
  system/src/build.mk
Labels: needs review

#1714 Update release scripts for Gen3
  build/make_release.sh
  build/release-publish.sh
  build/release-tests.sh
  build/release.sh
  release-mesh.sh
  user/tests/release-tests.json
Labels: internal, ready to merge

#1708 [Internal] Fix `brew install gcc-arm-none-eabi-53` formula
  docs/dependencies.md
Labels: documentation, internal, ready to merge

#1715 Fixes recent merge issues with `system-versions.md` [ci skip]
  system/system-versions.md
Labels: documentation, ready to merge

#1712 [CI] Build time optimizations
  .travis.yml
  build/platform-id.mk
  ci/enumerate_build_matrix.sh
  ci/functions.sh
  dynalib/import.mk
  hal/inc/hal_platform_compat.h
  hal/src/gcc/socket_hal.cpp
  hal/src/newhal/button_hal_impl.h
  hal/src/newhal/concurrent_hal_impl.h
  hal/src/newhal/dct.h
  hal/src/newhal/eeprom_emulation_impl.h
  hal/src/newhal/flash_storage_impl.h
  hal/src/newhal/include.mk
  hal/src/newhal/interrupts_irq.h
  hal/src/newhal/miniz_config.h
  hal/src/newhal/ota_flash_hal_stm32f2xx.h
  hal/src/newhal/platform_config.h
  hal/src/newhal/rgbled_hal_impl.h
  hal/src/template/wlan_hal.cpp
  modules/argon/user-part/makefile
  modules/boron/user-part/makefile
  modules/electron/system-part1/makefile
  modules/electron/system-part2/makefile
  modules/photon/system-part1/makefile
  modules/shared/nRF52840/build_linker_script.mk
  modules/shared/nRF52840/part1_build.mk
  modules/shared/nRF52840/user_build.mk
  modules/xenon/user-part/makefile
  platform/MCU/newhal-mcu/inc/hw_config.h
  scripts/fetch-buildpack
  services-dynalib/import.mk
  third_party/freertos/build.mk
  third_party/nrf5_sdk/build.mk
  wiring/src/spark_wiring_time.cpp
Labels: bug, internal, ready to merge

#1720 [Gen 2] Binary size optimizations
  hal/inc/hal_platform.h
  hal/inc/hal_platform_compat.h
  hal/src/nRF52840/hal_platform_nrf52840_config.h
  hal/src/photon/include.mk
  hal/src/photon/newlib_stubs.cpp
  hal/src/stm32/newlib.cpp
  modules/electron/system-part2/src/import_rt.c
  modules/photon/system-part1/src/import_rt.c
  modules/photon/system-part1/src/wifi_resources.c
  rt-dynalib/inc/rt_dynalib.h
  system/src/build.mk
  system/src/control/storage.cpp
  system/src/system_cloud_connection.cpp
  system/src/system_task.cpp
Labels: ready to merge

#1717 Tinker update
  modules/shared/system_module_version.mk
  user/applications/tinker-serial-debugging/tinker-serial-debugging.mk
  user/applications/tinker-serial1-debugging/tinker-serial1-debugging.cpp
  user/applications/tinker-serial1-debugging/tinker-serial1-debugging.mk
  user/applications/tinker/application.cpp
  user/applications/tinker/tinker.mk
  user/src/application.cpp
  user/tests/app/blank/blank.cpp
Labels: enhancement, ready to merge

#1590 Bootloader and Device OS use same HAL driver, Implement mirror button…
  bootloader/src/nRF52840/button.c
  bootloader/src/nRF52840/nrf_it.c
  bootloader/src/nRF52840/sources.mk
  hal/inc/button_hal.h
  hal/inc/hal_platform.h
  hal/inc/interrupts_hal.h
  hal/inc/rgbled_hal.h
  hal/src/nRF52840/button_hal.c
  hal/src/nRF52840/button_hal_impl.h
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/hal_platform_nrf52840_config.h
  hal/src/nRF52840/interrupts_hal.cpp
  hal/src/nRF52840/pinmap.cpp
  hal/src/nRF52840/pinmap_hal.c
  hal/src/nRF52840/pwm_hal.cpp
  hal/src/nRF52840/rgbled_hal.c
  hal/src/nRF52840/rgbled_hal_impl.h
  platform/MCU/nRF52840/inc/platform_config.h
  platform/MCU/nRF52840/inc/sdk_config_bootloader.h
  platform/MCU/nRF52840/inc/sdk_config_system.h
  platform/MCU/nRF52840/src/hw_config.c
  services/inc/rgbled.h
  system/src/main.cpp
  user/tests/wiring/no_fixture/gpio.cpp
  user/tests/wiring/no_fixture/led.cpp
  user/tests/wiring/no_fixture/pwm.cpp
  user/tests/wiring/no_fixture_long_running/pwm.cpp
Labels: enhancement, mesh, ready to merge

#1722 [Boron SoM] Disables system power management
  hal/src/boron/hal_platform_config.h
  system/src/system_power.cpp
  system/src/system_power_manager.cpp
Labels: enhancement, ready to merge

#1721 [Electron] [G350] fixes Cellular.RSSI() issues due to unknown RAT
  hal/src/electron/modem/mdm_hal.cpp
Labels: bug, ready to merge

#1723 [Boron/LTE] Enable Cat M1-only mode
  hal/network/ncp/at_parser/at_response.cpp
  hal/network/ncp/at_parser/at_response.h
  hal/src/boron/network/sara_ncp_client.cpp
  wiring/inc/spark_wiring_vector.h
Labels: enhancement, mesh, ready to merge

#1725 Power leakage from external flash
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/exflash_hal.c
Labels: bug, enhancement, ready to merge

#1731 Parameter check for SPI slave mode with HAL_SPI_INTERFACE1
  hal/src/nRF52840/spi_hal.cpp
Labels: enhancement, ready to merge

#1733 [SoM] Runtime power management IC detection
  hal/inc/hal_platform.h
  hal/inc/pinmap_hal.h
  hal/src/argon/hal_platform_config.h
  hal/src/boron/hal_platform_config.h
  hal/src/xenon/hal_platform_config.h
  modules/argon/system-part1/makefile
  modules/xenon/system-part1/makefile
  platform/MCU/nRF52840/inc/dct.h
  system/inc/system_update.h
  system/src/system_power_manager.cpp
  system/src/system_power_manager.h
  system/src/system_update.cpp
  user/applications/tinker/application.cpp
Labels: feature, ready to merge

#1735 [ci] disables shallow submodule checkouts
  .travis.yml
Labels: ready to merge
