Repository particle-iot/device-os, pull requests merged in 2019-12, with the labels that each got.

#1976 [Photon/P1] Fixes handling of invalid WiFi access point config entries in DCT
  hal/src/photon/dct_prep.bin
  hal/src/photon/wlan_hal.cpp
Labels: bug, ready to merge

#1949 [photon] wlan: add wiced_wlan_connectivity_initialized() check in wlan_fetch_ipconfig()
  hal/src/photon/wlan_hal.cpp
  user/tests/wiring/no_fixture/wifi.cpp
Labels: bug, ready to merge

#1965 Refactors system sleep implementation
  hal/inc/hal_dynalib_core.h
  hal/inc/sleep_hal.h
  hal/src/core/sleep_hal.cpp
  hal/src/gcc/sleep_hal.cpp
  hal/src/nRF52840/sleep_hal.cpp
  hal/src/stm32f2xx/sleep_hal.cpp
  system/inc/system_dynalib.h
  system/inc/system_sleep.h
  system/src/system_sleep.cpp
  wiring/inc/spark_wiring_system.h
  wiring/src/spark_wiring_system.cpp
Labels: DO NOT MERGE, in progress, internal, realm/embedded-platform

#1975 Gen3 devices now can be woken up by BLE.
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/sleep_hal.cpp
  system/inc/system_sleep.h
Labels: ble, feature, realm/embedded-platform

#1977 Implements that Gen3 platforms can be woken up by multiple pins when they are in standby mode.
  hal/inc/interrupts_hal.h
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/sleep_hal.cpp
  hal/src/stm32f2xx/sleep_hal.cpp
  system/inc/system_sleep.h
  wiring/src/spark_wiring_system.cpp
Labels: feature, ready to merge, realm/embedded-platform

#1982 Validates sleep configuration before entering sleep mode
  hal/inc/hal_dynalib_core.h
  hal/inc/sleep_hal.h
  hal/src/core/sleep_hal.cpp
  hal/src/gcc/sleep_hal.cpp
  hal/src/nRF52840/sleep_hal.cpp
  hal/src/stm32f2xx/sleep_hal.cpp
  system/inc/system_sleep.h
  system/src/system_sleep.cpp
  wiring/src/spark_wiring_system.cpp
Labels: enhancement, ready to merge, realm/embedded-platform

#1974 Export sendmsg() and recvmsg() systems calls
  hal/inc/hal_dynalib_socket_posix.h
  hal/inc/socket_hal_posix.h
  hal/network/lwip/posix/sys/socket.h
  hal/network/lwip/socket_hal.cpp
Labels: enhancement, ready to merge

#1987 Add support for control requests sent by the test runner
  user/build.mk
  user/tests/integration/application/include/test.h
  user/tests/integration/application/src/application.cpp
  user/tests/integration/application/src/request_handler.cpp
  user/tests/integration/application/src/request_handler.h
  user/tests/integration/application/src/test_suite.cpp
  user/tests/integration/application/src/test_suite.h
  user/tests/integration/communication/events/events.cpp
  user/tests/integration/communication/events/events.spec.js
  user/tests/integration/test.mk
  user/tests/libraries/unit-test/FakeStream.h
  user/tests/libraries/unit-test/ParticleFunbag.cpp
  user/tests/libraries/unit-test/unit-test.cpp
  user/tests/libraries/unit-test/unit-test.h
  user/tests/tests.mk
Labels: enhancement, ready to merge

#1991 Add support for chunked transfer of USB request/reply data
  system/inc/system_control.h
  system/src/control/config.cpp
  system/src/control/config.h
  system/src/control/mesh.cpp
  system/src/system_control_internal.cpp
  system/src/usb_control_request_channel.cpp
  system/src/usb_control_request_channel.h
  user/tests/unit/led_service.cpp
  user/tests/unit/usb_control_request_channel.cpp
Labels: enhancement, needs review

#1978 Implements bitwise operants for enum class
  services/inc/enumclass.h
  services/inc/enumflags.h
  wiring/inc/spark_wiring_ble.h
  wiring/src/spark_wiring_ble.cpp
Labels: feature, ready to merge, realm/embedded-platform
