Repository particle-iot/device-os, pull requests merged in 2019-01, with the labels that each got.

#1666 Fixes unique stale socket issue with LTE devices
  hal/src/electron/modem/mdm_hal.cpp
Labels: bug

#1670 Fix Travis badge
  README.md
Labels: ready to merge

#1674 Mojave doesn't ship with `wget`
  hal/src/gcc/readme.md
Labels: documentation

#1661 Fix/argon netif deadlock
  hal/network/lwip/esp32/esp32ncpnetif.cpp
Labels: bug, mesh, ready to merge

#1681 [Boron] Ensure that the modem is on before trying to retrieve IMEI and ICCID
  hal/src/boron/cellular_hal.cpp
Labels: bug, mesh, ready to merge

#1653 [Mesh] Fixes WCID in bootloader
  bootloader/src/nRF52840/usbd_device.cpp
  bootloader/src/nRF52840/usbd_dfu.cpp
  bootloader/src/nRF52840/usbd_wcid.h
Labels: bug, mesh, ready to merge

#1658 CH26714: Arduino compatibility for mesh platforms.
  user/inc/Arduino.h
Labels: enhancement, mesh, ready to merge

#1672 Fix/hal/spi default config
  hal/src/nRF52840/spi_hal.cpp
  platform/MCU/nRF52840/inc/sdk_config_system.h
Labels: enhancement, mesh, ready to merge

#1667 Implement standby mode
  hal/inc/core_hal.h
  hal/inc/hal_dynalib_core.h
  hal/src/core/core_hal.c
  hal/src/gcc/core_hal.cpp
  hal/src/mesh-virtual/core_hal.cpp
  hal/src/nRF52840/core_hal.c
  hal/src/stm32f2xx/core_hal_stm32f2xx.c
  hal/src/template/core_hal.cpp
  platform/MCU/nRF52840/src/hw_config.c
  system/inc/system_dynalib.h
  system/inc/system_sleep.h
  system/src/system_sleep.cpp
  wiring/inc/spark_wiring_system.h
  wiring/src/spark_wiring_system.cpp
Labels: feature, mesh, ready to merge

#1655 [Gen 3] Control requests over USB
  hal/inc/hal_platform.h
  hal/inc/hal_platform_compat.h
  hal/inc/usb_config_hal.h
  hal/src/argon/app_usbd_string_config.h
  hal/src/boron/app_usbd_string_config.h
  hal/src/nRF52840/hal_platform_nrf52840_config.h
  hal/src/nRF52840/usb_hal.cpp
  hal/src/nRF52840/usb_hal_cdc.c
  hal/src/nRF52840/usb_hal_control.cpp
  hal/src/nRF52840/usb_hal_hid.cpp
  hal/src/nRF52840/usbd_wcid.h
  hal/src/xenon/app_usbd_string_config.h
  platform/MCU/nRF52840/inc/sdk_config_system.h
  system/src/usb_control_request_channel.cpp
Labels: feature, mesh, ready to merge
