Repository particle-iot/device-os, pull requests merged in 2019-07, with the labels that each got.

#1841 fixes RSSI regression on G350 (2G) devices [ch35194]
  hal/src/electron/modem/mdm_hal.cpp
  user/tests/wiring/no_fixture/cellular.cpp
Labels: bug, ready to merge, regression

#1848 fixes RSSI regression on G350 (2G) devices [ch35194] (original PR #1841)
  hal/src/electron/modem/mdm_hal.cpp
  user/tests/wiring/no_fixture/cellular.cpp
Labels: bug, ready to merge, regression

#1849 v1.2.1 default version bump
  CHANGELOG.md
  build/release.sh
  build/version.mk
  hal/src/stm32f2xx/bootloader_platform_10.c
  hal/src/stm32f2xx/bootloader_platform_6.c
  hal/src/stm32f2xx/bootloader_platform_8.c
  modules/shared/system_module_version.mk
  system/inc/system_version.h
  system/system-versions.md
  user/tests/scripts/country-updown/country-updown.sh
  user/tests/scripts/upgrade-downgrade/upgrade-downgrade.sh
Labels: ready to merge

#1850 Fix to ensure device resets after bootloader update
  system/src/main.cpp
Labels: bug

#1862 [electron, gen3] Temporarily increase IDLE task priority whenever a thread exits (calls vTaskDelete)
  hal/src/electron/FreeRTOSConfig.h
  hal/src/electron/rtos_hook.cpp
  hal/src/nRF52840/freertos/FreeRTOSConfig.h
  hal/src/nRF52840/rtos_hook.cpp
Labels: bug, ready to merge

#1839 [Gen 3] Fixes mesh pub/sub socket consuming all packet buffers
  hal/src/nRF52840/lwip/lwipopts.h
  user/tests/wiring/no_fixture/mesh.cpp
  wiring/inc/spark_wiring_mesh.h
  wiring/inc/spark_wiring_thread.h
  wiring/inc/spark_wiring_udp.h
  wiring/src/spark_wiring_mesh.cpp
Labels: bug, ready to merge

#1867 Pull test implementation out of source file
  system/src/system_publish_vitals.cpp
  test/unit_tests/cloud/publish_vitals.cpp
  test/unit_tests/mock/mock_types.h
Labels: enhancement, needs review

#1868 Fix/reload dct functions
  bootloader/src/main.c
  bootloader/src/photon/bootloader_dct.c
  bootloader/src/photon/bootloader_dct.h
  platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc/dct.h
  platform/MCU/STM32F2xx/STM32_USB_Device_Driver/src/usbd_flash_if.c
Labels: bootloader, bug, ready to merge

#1846 Fixes Boron charging current limitation when powered by VUSB
  hal/inc/hal_platform.h
  hal/inc/usb_hal.h
  hal/src/nRF52840/hal_platform_nrf52840_config.h
  hal/src/nRF52840/usb_hal.cpp
  hal/src/nRF52840/usb_hal_cdc.c
  hal/src/nRF52840/usb_hal_cdc.h
  system/src/system_power_manager.cpp
  system/src/system_power_manager.h
Labels: enhancement, ready to merge

#1857 [system] disconnect the cloud when calling Mesh.off()
  wiring/inc/spark_wiring_mesh.h
Labels: bug, ready to merge

#1837 [gen3] hal: change wakeup pin for SoM boards
  hal/inc/pinmap_hal.h
Labels: ready to merge
