Repository particle-iot/device-os, pull requests merged in 2019-05, with the labels that each got.

#1774 Rename SoM platform names [ch32184]
  .buildpackrc
  .travis.yml
  CHANGELOG.md
  bootloader/src/nRF52840/usbd_device.cpp
  build/make_release.sh
  build/platform-id.mk
  build/release-publish.sh
  build/release-tests.sh
  build/release.sh
  hal/inc/pinmap_hal.h
  hal/network/lwip/nat64.cpp
  hal/network/openthread/border_router_manager.cpp
  hal/shared/platforms.h
  hal/src/argon/app_usbd_string_config.h
  hal/src/argon/hal_platform_config.h
  hal/src/argon/network/network.cpp
  hal/src/boron/app_usbd_string_config.h
  hal/src/boron/hal_platform_config.h
  hal/src/boron/network/network.cpp
  hal/src/nRF52840/lwip/lwippppopts.h
  hal/src/nRF52840/openthread/system.c
  hal/src/nRF52840/pinmap_hal.c
  hal/src/nRF52840/usart_hal.cpp
  hal/src/xenon/app_usbd_string_config.h
  hal/src/xenon/hal_platform_config.h
  hal/src/xenon/network/network.cpp
  modules/argon/system-part1/makefile
  modules/xenon/system-part1/makefile
  newlib_nano/src/sources.mk
  platform/MCU/nRF52840/inc/platform_config.h
  system/src/system_task.cpp
  user/applications/tinker/application.cpp
  user/tests/wiring/no_fixture/pwm.cpp
  user/tests/wiring/no_fixture_long_running/pwm.cpp
  user/tests/wiring/spi_master_slave/spi_master/spi_master.cpp
  user/tests/wiring/spi_master_slave/spi_slave/spi_slave.cpp
  user/tests/wiring/spi_master_slave_alt/spi_master/spi_master.cpp
  user/tests/wiring/spi_master_slave_alt/spi_slave/spi_slave.cpp
  wiring/inc/fast_pin.h
Labels: internal, needs review

#1757 Sets C++ and C standard versions in a single location (C++14 and C11)
  bootloader/build.mk
  build/arm-tlm.mk
  build/lang-std.mk
  build/module-defaults.mk
  communication/src/build.mk
  communication/tests.mk
  communication/tests/catch/makefile
  crypto/src/build.mk
  gsm0710muxer/build.mk
  hal/src/core/tlm.mk
  hal/src/electron/tlm.mk
  hal/src/gcc/sources.mk
  hal/src/mesh-virtual/sources.mk
  hal/src/nRF52840/sources.mk
  hal/src/newhal/sources.mk
  hal/src/photon/tlm.mk
  modules/shared/nRF52840/part1_build.mk
  modules/shared/stm32f2xx/part2_build.mk
  modules/shared/stm32f2xx/part3_build.mk
  platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/sources.mk
  services/src/build.mk
  system/src/build.mk
  test/unit_tests/CMakeLists.txt
  user/build.mk
  user/tests/unit/makefile
  wiring/src/build.mk
  wiring_globals/src/build.mk
Labels: enhancement, ready to merge

#1758 [Gen 3] Always check ongoing RX DMA transaction when reporting number of bytes available in RX buffer
  hal/src/nRF52840/usart_hal.cpp
  user/tests/wiring/serial_loopback2/README.md
  user/tests/wiring/serial_loopback2/application.cpp
  user/tests/wiring/serial_loopback2/loopback.cpp
Labels: enhancement, ready to merge

#1761 Introduce safety checks on heap usage from ISRs
  hal/src/electron/core_hal.c
  hal/src/nRF52840/core_hal.c
  newlib_nano/makefile
  newlib_nano/src/malloc.c
  services/inc/panic_codes.h
Labels: enhancement, ready to merge

#1773 [system] network manager: allows to clear interface-specific credentials notwithstanding interface state, except for Mesh
  system/src/system_network_manager.cpp
Labels: bug, ready to merge

#1777 Fix/hal/gen3 pinmode
  hal/src/nRF52840/gpio_hal.cpp
  hal/src/nRF52840/pinmap_hal.c
  platform/MCU/STM32F1xx/SPARK_Firmware_Driver/src/hw_config.c
  platform/MCU/nRF52840/src/hw_config.c
Labels: bug, ready to merge

#1776 expires a session after 3 unsuccessful attempts at connecting to the cloud
  communication/src/dtls_message_channel.cpp
  communication/src/dtls_message_channel.h
  communication/src/dtls_protocol.cpp
  communication/src/dtls_session_persist.h
Labels: enhancement

#1759 Integrate cellular network vitals data into `DESCRIBE_x` message
  communication/src/protocol.cpp
  hal/inc/cellular_hal.h
  hal/inc/cellular_hal_cellular_global_identity.h
  hal/inc/hal_dynalib_cellular.h
  hal/inc/net_hal.h
  hal/src/boron/cellular_hal.cpp
  hal/src/boron/modem/enums_hal.h
  hal/src/boron/network/cellular_ncp_client.h
  hal/src/boron/network/sara_ncp_client.cpp
  hal/src/boron/network/sara_ncp_client.h
  hal/src/electron/cellular_hal.cpp
  hal/src/electron/cellular_internal.cpp
  hal/src/electron/modem/enums_hal.h
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
  services/inc/diagnostics.h
  system/src/system_network_compat.cpp
  system/src/system_network_diagnostics.cpp
  user/tests/accept/hal-api-test-plan.md
  user/tests/app/band_select/band_select.cpp
  user/tests/app/cellular_global_identity/cellular_global_identity.cpp
  user/tests/wiring/no_fixture/cellular.cpp
Labels: enhancement, ready to merge

#1780 [gen 2] adds Kore Vodafone SIM support & removes Twilio SIM support (…
  hal/inc/cellular_hal_constants.h
  hal/src/electron/cellular_hal.cpp
  hal/src/electron/cellular_internal.cpp
  user/tests/unit/cellular.cpp
Labels: enhancement, ready to merge

#1767 Wait for confirmable messages when entering the deep sleep mode
  communication/src/dtls_protocol.cpp
  system/inc/system_sleep.h
  system/src/system_sleep.cpp
  user/tests/wiring/api/system.cpp
  wiring/inc/spark_wiring_system.h
Labels: bug, ready to merge

#1770 Fixes Spark Core function calls broken in 0.8.0-rc.4 [ch32050]
  communication/src/core_protocol.cpp
  communication/src/core_protocol.h
  communication/src/functions.h
  user/tests/accept/features/cloud/README.md
  user/tests/accept/features/cloud/cloud.bats
  user/tests/accept/features/cloud/cloudtest.cpp
  user/tests/accept/features/cloud/debug.log
  user/tests/accept/features/cloud/fillbyte
  user/tests/accept/features/cloud/list.txt
  user/tests/accept/features/cloud/zerobyte
  user/tests/app/cloudtest/cloud.bats
  user/tests/app/cloudtest/cloudtest.cpp
Labels: bug, ready to merge

#1742 Reserve memory for system-part1 SRAM
  modules/electron/system-part1/linker.ld
  modules/electron/system-part1/module_system_part3_export.ld
  modules/electron/system-part2/module_system_part1_export.ld
  modules/electron/system-part3/module_system_part2_export.ld
  modules/electron/user-part/module_user_memory.ld
  modules/photon/system-part1/module_system_part1_export.ld
  modules/photon/system-part2/module_system_part2_export.ld
  modules/shared/stm32f2xx/inc/system_part1_loader.c
  modules/shared/stm32f2xx/inc/system_part2_loader.c
  modules/shared/stm32f2xx/inc/system_part3_loader.c
  modules/shared/stm32f2xx/part2.ld
Labels: enhancement, ready to merge

#1762 [Electron/LTE] disables all eDRX AcT types [ch32051]
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
Labels: bug, ready to merge

#1779 [Electron/LTE] Make sure that the RAT information is actual before calculating signal strength (RSSI) and quality
  hal/src/electron/modem/enums_hal.h
  hal/src/electron/modem/mdm_hal.cpp
Labels: bug, ready to merge

#1784 intelligent update flags synchronization
  system/src/system_cloud_internal.cpp
Labels: bug, ready to merge

#1783 [Photon / P1] Fixes MAC address info not being available in listening mode
  system/src/system_network_compat.cpp
Labels: bug, needs review

#1782 [wiring] Make sure that `Serial` and `SerialX` methods are in sync with the documentation and don't return unexpected values
  wiring/src/spark_wiring_usartserial.cpp
  wiring/src/spark_wiring_usbserial.cpp
Labels: bug, needs review

#1785 [gen 3] update bootloader dependency to v302
  build/platform-id.mk
  modules/shared/system_module_version.mk
Labels: enhancement, ready to merge

#1787 [Gen3] Fixes HAL_USB_USART_Send_Data() returning incorrect values
  hal/src/nRF52840/usb_hal_cdc.c
Labels: bug

#1794 [system] Fixes radio initialization sequence for Softdevice S140v6.1.1
  system/src/main.cpp
Labels: bug, ready to merge

#1792 [Gen 2] Fix ABI compatibility issue in cellular HAL
  hal/src/boron/cellular_hal.cpp
  hal/src/boron/modem/enums_hal.h
  hal/src/electron/cellular_hal.cpp
Labels: bug, ready to merge

#1799 [gen 3] [bootloader] External flash sleep refactoring
  hal/inc/exflash_hal.h
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/exflash_hal.c
Labels: bootloader, bug, needs review

#1606 Feature/hal/nfc
  hal-dynalib/src/hal_nfc.c
  hal/inc/hal_dynalib_nfc.h
  hal/inc/hal_platform.h
  hal/inc/nfc_hal.h
  hal/src/nRF52840/hal_dynalib_export.cpp
  hal/src/nRF52840/hal_platform_nrf52840_config.h
  hal/src/nRF52840/nfc_hal.cpp
  hal/src/nRF52840/usart_hal.cpp
  modules/argon/system-part1/module_system_part1_export.ld
  modules/boron/system-part1/module_system_part1_export.ld
  modules/shared/nRF52840/inc/system-part1/module_system_part1.inc
  modules/xenon/system-part1/module_system_part1_export.ld
  platform/MCU/nRF52840/inc/sdk_config_system.h
  third_party/nrf5_sdk/build.mk
  third_party/nrf5_sdk/include.mk
  user/inc/application.h
  user/tests/wiring/nfc/application.cpp
  wiring/inc/spark_wiring.h
  wiring/inc/spark_wiring_nfc.h
  wiring/inc/spark_wiring_platform.h
  wiring/src/spark_wiring_nfc.cpp
Labels: feature, mesh, ready to merge

#1802 Building platform BSOM results flash overflow.
  hal/build.mk
Labels: bug, ready to merge

#1803 [gen3] hal: fixes early wakeup by RTC from STOP sleep mode
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/openthread/alarm.c
Labels: bug

#1800 [docs] Updates `spark_publish_vitals` and build scripts documentation.
  build/make_release.sh
  build/release-publish.sh
  build/release-tests.sh
  build/release.sh
  system/inc/system_cloud.h
  wiring/inc/spark_wiring_cloud.h
Labels: documentation, internal, ready to merge

#1683 update the test documentation
  user/tests/readme.md
Labels: documentation, internal, ready to merge
