Repository particle-iot/device-os, pull requests merged in 2019-11, with the labels that each got.

#1957 Enable Workbench DeviceOS local development
  .workbench/manifest.json
Labels: enhancement, needs review, realm/dev-experience

#1961 Fix call to objdump
  modules/shared/nRF52840/build_linker_script.mk
Labels: bug, ready to merge

#1959 Update manifest platforms
  .workbench/manifest.json
Labels: bug, realm/dev-experience

#1963 Ensure gpio pin map is initialized on first use for gcc build
  hal/src/gcc/gpio_hal.cpp
Labels: bug

#1969 [Gen 3] Fix too many connection events with deactivated SIM [ch40865]
  hal/src/boron/network/sara_ncp_client.cpp
Labels: bug, ready to merge

#1970 [Gen 2] Fixes thread-safety issues in libc functions
  hal/src/electron/FreeRTOSConfig.h
  hal/src/photon/lib/FreeRTOS/FreeRTOS.a
  hal/src/photon/wiced/RTOS/FreeRTOS/WWD/ARM_CM3/FreeRTOSConfig.h
Labels: bug, ready to merge
