Repository particle-iot/device-os, pull requests merged in 2019-08, with the labels that each got.

#1870 [hal] Fixes Argon cannot be reset by external gpio
  hal/src/argon/network/esp32_ncp_client.cpp
Labels: bug, ready to merge

#1854 [Electron/LTE] devices drop Cloud connection every time user firmware opens and closes a TCP socket [ch34976]
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
  user/tests/wiring/no_fixture/cellular.cpp
  wiring/src/spark_wiring_tcpclient.cpp
Labels: bug, ready to merge

#1863 communications public interface
  communication/inc/coap.h
  communication/inc/communication_dynalib.h
  communication/inc/dsakeygen.h
  communication/inc/dtls_session_persist.h
  communication/inc/eckeygen.h
  communication/inc/events.h
  communication/inc/file_transfer.h
  communication/inc/protocol.h
  communication/inc/protocol_defs.h
  communication/inc/protocol_selector.h
  communication/inc/spark_descriptor.h
  communication/inc/spark_protocol_functions.h
  communication/inc/tls_callbacks.h
  communication/src/build.mk
  communication/src/include.mk
  hal/src/nRF52840/ota_flash_hal.cpp
  test/unit_tests/cloud/CMakeLists.txt
  test/unit_tests/communication/CMakeLists.txt
  test/unit_tests/wiring/CMakeLists.txt
  user/tests/unit/makefile
Labels: internal, ready to merge

#1830 Cancel network connection when processing a USB request that resets the device
  system/src/usb_control_request_channel.cpp
  user/tests/unit/stubs/system_cloud.cpp
  user/tests/unit/stubs/system_network.cpp
Labels: enhancement, ready to merge

#1829 [gen2] hal: Fixes I2C bus missing stretch configuration
  hal/src/stm32f2xx/i2c_hal.c
  user/tests/wiring/i2c_master_slave/i2c_master/i2c_master.cpp
Labels: bug, ready to merge

#1873 Fixes from 1.2.1
  hal/src/core/ota_flash_hal.c
  system/src/main.cpp
Labels: bug, ready to merge

#1872 Set path to Boost libraries
  ci/build_boost.sh
  ci/install_boost.sh
  ci/run_tests.sh
  test/unit_tests/CMakeLists.txt
Labels: internal, needs review

#1825 Particle.connected() should return true only after handshake messages are acknowledged
  communication/inc/communication_dynalib.h
  communication/inc/protocol.h
  communication/inc/spark_protocol_functions.h
  communication/src/coap_channel.cpp
  communication/src/coap_channel.h
  communication/src/core_protocol.cpp
  communication/src/core_protocol.h
  communication/src/dtls_message_channel.h
  communication/src/dtls_protocol.cpp
  communication/src/dtls_protocol.h
  communication/src/lightssl_message_channel.h
  communication/src/lightssl_protocol.h
  communication/src/message_channel.h
  communication/src/spark_protocol_functions.cpp
  system/inc/system_cloud.h
  system/inc/system_task.h
  system/src/system_cloud.cpp
  system/src/system_cloud_internal.cpp
  system/src/system_cloud_internal.h
  system/src/system_publish_vitals.cpp
  system/src/system_task.cpp
  system/src/system_update.cpp
  test/unit_tests/communication/coap_reliability.cpp
  test/unit_tests/communication/forward_message_channel.h
  test/unit_tests/communication/protocol.cpp
  wiring/inc/spark_wiring_cloud.h
  wiring/src/spark_wiring_cloud.cpp
Labels: enhancement, ready to merge

#1871 [hal] Fixes USB send failed
  hal/inc/usb_hal.h
  hal/src/nRF52840/usb_hal.cpp
  hal/src/nRF52840/usb_hal_cdc.c
  system/src/system_power_manager.cpp
Labels: bug, ready to merge

#1875 Fix/gen3 i2c timeout
  hal/src/nRF52840/i2c_hal.cpp
  user/tests/wiring/i2c_master_slave/i2c_slave/i2c_slave.cpp
Labels: enhancement, ready to merge

#1847 BLE: updates for v1.3.1-rc.1
  build/arm/linker/nrf52840/platform_ram.ld
  build/arm/linker/nrf52840/softdevice.ld
  communication/src/dtls_message_channel.cpp
  hal/inc/ble_hal.h
  hal/inc/hal_dynalib_ble.h
  hal/src/nRF52840/ble_hal.cpp
  hal/src/nRF52840/ble_hal_impl.h
  hal/src/nRF52840/mbedtls/mbedtls_config_platform.h
  modules/shared/nRF52840/build_linker_script.mk
  platform/MCU/nRF52840/inc/sdk_config_system.h
  services/inc/system_error.h
  system/src/ble_control_request_channel.cpp
  system/src/ble_control_request_channel.h
  user/tests/app/ble/ibeacon/application.cpp
  user/tests/app/ble/scanner/application.cpp
  user/tests/app/ble/uart_central/application.cpp
  user/tests/app/ble/uart_peripheral/application.cpp
  wiring/inc/spark_wiring_ble.h
  wiring/src/spark_wiring_ble.cpp
Labels: ble, enhancement, ready to merge

#1878 [gcc] fixes virtual platform exception on startup #1878 [ch35243]
  hal/src/gcc/ota_flash_hal.cpp
Labels: bug

#1886 Ensure AT interface is responsive
  hal/src/electron/modem/mdm_hal.cpp
Labels: enhancement, ready to merge, realm/cellular

#1889 [hal] Fixes WIFIEN pin mode for ASoM
  hal/src/argon/network/esp32_ncp_client.cpp
Labels: bug

#1894 [user] fixes weird alignment error with the dynalib table location
  modules/shared/nRF52840/user.ld
  modules/shared/stm32f2xx/user.ld
Labels: bug, ready to merge

#1887 Changes to support building combined Photon and P1 images for the recent releases
  bootloader/build.mk
  bootloader/makefile
  bootloader/src/main.c
  bootloader/src/stm32f2xx/module.c
  bootloader/src/stm32f2xx/module.h
  build/release.sh
  hal/src/electron/combined.mk
  hal/src/nRF52840/image_bootloader.sh
  hal/src/photon/core_hal.c
  hal/src/photon/make_combined.sh
  hal/src/photon/sources.mk
  hal/src/photon/wiced_test_mfg_combined.mk
  hal/src/stm32/combined.mk
  platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc/flash_mal.h
  platform/MCU/nRF52840/inc/flash_mal.h
Labels: bootloader, internal, ready to merge

#1882 BLE: alternately broadcast user's and Particle-specific advertising d…
  hal/inc/ble_hal.h
  hal/inc/hal_dynalib_ble.h
  hal/src/nRF52840/ble_hal.cpp
  system/src/ble_listening_mode_handler.cpp
  system/src/ble_listening_mode_handler.h
  wiring/inc/spark_wiring_ble.h
  wiring/src/spark_wiring_ble.cpp
Labels: ble, ready to merge, refactor

#1891 BLE: minor fixes
  hal/src/nRF52840/ble_hal.cpp
  wiring/inc/spark_wiring_ble.h
  wiring/src/spark_wiring_ble.cpp
Labels: ble, bug, ready to merge

#1895 Expose select() and poll() to apps
  hal/inc/hal_dynalib_socket_posix.h
  hal/inc/socket_hal_posix.h
  hal/network/lwip/posix/poll.h
  hal/network/lwip/posix/sys/socket.h
  hal/network/lwip/socket_hal.cpp
Labels: enhancement, in progress, ready to merge

#1897 Fixes SoftDevice OTA updates
  hal/src/argon/platform_ncp_argon.cpp
  hal/src/nRF52840/platform_radio_stack.cpp
  platform/MCU/nRF52840/src/flash_mal.c
Labels: bootloader, bug, needs review

#1896 Update Travis CI for Coveralls
  .travis.yml
  ci/install_gcovr.sh
  ci/report/LICENSE
  ci/report/report.py
  ci/unit_tests.sh
  scripts/fetch-buildpack
  test/unit_tests/CMakeLists.txt
Labels: feature, needs review

#1898 Fixes issues encountered during 1.4.0 rc.1 testing
  communication/src/dtls_message_channel.cpp
  crypto/inc/mbedtls_config_photon.h
  hal/src/boron/cellular_hal.cpp
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/mbedtls/mbedtls_config_platform.h
  user/applications/tinker/tinker.mk
  user/tests/wiring/no_fixture/cellular.cpp
  user/tests/wiring/no_fixture/mesh.cpp
  user/tests/wiring/no_fixture/pwm.cpp
  user/tests/wiring/no_fixture/system.cpp
  user/tests/wiring/no_fixture/thread.cpp
  user/tests/wiring/no_fixture/wifi.cpp
Labels: bug, needs review
