Repository particle-iot/device-os, pull requests merged in 2019-06, with the labels that each got.

#1804 Add two-digit mnc diagnostic flag
  hal/inc/cellular_hal.h
  hal/inc/cellular_hal_cellular_global_identity.h
  hal/src/boron/cellular_hal.cpp
  hal/src/boron/network/sara_ncp_client.cpp
  hal/src/boron/network/sara_ncp_client.h
  hal/src/electron/cellular_hal.cpp
  hal/src/electron/modem/mdm_hal.cpp
  system/src/system_network_diagnostics.cpp
  user/tests/accept/hal-api-test-plan.md
  user/tests/app/cellular_global_identity/cellular_global_identity.cpp
Labels: bug, ready to merge

#1807 Add two-digit mnc diagnostic flag
  hal/inc/cellular_hal.h
  hal/inc/cellular_hal_cellular_global_identity.h
  hal/src/boron/cellular_hal.cpp
  hal/src/boron/network/sara_ncp_client.cpp
  hal/src/boron/network/sara_ncp_client.h
  hal/src/electron/cellular_hal.cpp
  hal/src/electron/modem/mdm_hal.cpp
  system/src/system_network_diagnostics.cpp
  user/tests/accept/hal-api-test-plan.md
  user/tests/app/cellular_global_identity/cellular_global_identity.cpp
Labels: bug, ready to merge

#1810 Cache cellular diagnostics
  system/src/system_network_diagnostics.cpp
Labels: enhancement

#1820 Cellular Global Identity diagnostic cache
  system/src/system_network_diagnostics.cpp
Labels: enhancement, ready to merge

#1817 Fix/ble/v1.3.0 rc.1
  build/arm/linker/nrf52840/softdevice.ld
  hal/src/nRF52840/ble_hal.cpp
  modules/shared/nRF52840/build_linker_script.mk
  modules/shared/nRF52840/module_user_export.ld
  platform/MCU/nRF52840/inc/sdk_config_system.h
  wiring/inc/spark_wiring_ble.h
  wiring/src/spark_wiring_ble.cpp
Labels: ble, bug, ready to merge

#1818 [NFC] Context parameter is missing and NFC.update() will remove callback
  wiring/inc/spark_wiring_nfc.h
  wiring/src/spark_wiring_nfc.cpp
Labels: bug, ready to merge

#1824 [lte] cellular fixes
  hal/src/boron/network/cellular_ncp_client.h
  hal/src/boron/network/sara_ncp_client.cpp
  hal/src/boron/network/sara_ncp_client.h
  hal/src/electron/modem/electronserialpipe_hal.cpp
  hal/src/electron/modem/electronserialpipe_hal.h
  hal/src/electron/modem/enums_hal.h
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
  hal/src/electron/modem/pipe_hal.h
Labels: bug, enhancement, ready to merge

#1822 fixes #1811 - increases the number of event handlers to 6 to accommod…
  communication/src/core_protocol.h
  communication/src/protocol_defs.h
  communication/src/subscriptions.h
  communication/tests/catch/protocol.cpp
Labels: bug, ready to merge

#1819 [Gen 3] Fix memory usage diagnostics
  hal/src/nRF52840/core_hal.c
  modules/shared/nRF52840/part1.ld
Labels: bug, ready to merge

#1801 System.disableUpdates() operates asynchronously
  ci/enumerate_build_matrix.sh
  communication/src/events.h
  system/inc/system_cloud.h
  system/src/system_cloud.cpp
  system/src/system_update.cpp
Labels: bug, ready to merge

#1788 allow the bootloader to be flashed over DFU
  hal/inc/hal_dynalib_ota.h
  hal/inc/ota_flash_hal.h
  hal/src/core/ota_flash_hal.c
  hal/src/gcc/ota_flash_hal.cpp
  hal/src/nRF52840/ota_flash_hal.cpp
  hal/src/stm32f2xx/ota_flash_hal_stm32f2xx.cpp
  platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc/dct.h
  platform/MCU/nRF52840/inc/dct.h
  system/src/main.cpp
  system/src/system_update.cpp
Labels: enhancement, ready to merge

#1826 Backport fixes for 1.2.1-rc.3
  ci/enumerate_build_matrix.sh
  communication/src/core_protocol.h
  communication/src/events.h
  communication/src/protocol_defs.h
  communication/src/subscriptions.h
  communication/tests/catch/protocol.cpp
  hal/inc/hal_dynalib_ota.h
  hal/inc/ota_flash_hal.h
  hal/src/boron/network/cellular_ncp_client.h
  hal/src/boron/network/sara_ncp_client.cpp
  hal/src/boron/network/sara_ncp_client.h
  hal/src/core/ota_flash_hal.c
  hal/src/electron/modem/electronserialpipe_hal.cpp
  hal/src/electron/modem/electronserialpipe_hal.h
  hal/src/electron/modem/enums_hal.h
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
  hal/src/electron/modem/pipe_hal.h
  hal/src/gcc/ota_flash_hal.cpp
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/ota_flash_hal.cpp
  hal/src/stm32f2xx/ota_flash_hal_stm32f2xx.cpp
  modules/shared/nRF52840/part1.ld
  platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc/dct.h
  platform/MCU/nRF52840/inc/dct.h
  system/inc/system_cloud.h
  system/src/main.cpp
  system/src/system_cloud.cpp
  system/src/system_update.cpp
Labels: bug, enhancement, needs review

#1827 Backport fixes for 1.1.1-rc.1
  hal/src/boron/network/cellular_ncp_client.h
  hal/src/boron/network/sara_ncp_client.cpp
  hal/src/boron/network/sara_ncp_client.h
  hal/src/electron/modem/electronserialpipe_hal.cpp
  hal/src/electron/modem/electronserialpipe_hal.h
  hal/src/electron/modem/enums_hal.h
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
  hal/src/electron/modem/pipe_hal.h
  services/inc/system_error.h
Labels: bug, enhancement, needs review
