Repository particle-iot/device-os, pull requests merged in 2019-09, with the labels that each got.

#1905 Various bugfixes
  communication/src/protocol.cpp
  hal/network/lwip/ifapi.cpp
  hal/src/nRF52840/core_hal.c
  hal/src/stm32f2xx/core_hal_stm32f2xx.c
  system/src/active_object.cpp
  system/src/usb_control_request_channel.cpp
Labels: bug, ready to merge

#1907 Backports into 1.3.1
  communication/src/protocol.cpp
  hal/network/lwip/ifapi.cpp
  hal/src/argon/platform_ncp_argon.cpp
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/platform_radio_stack.cpp
  hal/src/stm32f2xx/core_hal_stm32f2xx.c
  modules/shared/nRF52840/user.ld
  modules/shared/stm32f2xx/user.ld
  platform/MCU/nRF52840/src/flash_mal.c
  system/src/active_object.cpp
  system/src/usb_control_request_channel.cpp
  user/applications/tinker/tinker.mk
  user/tests/wiring/no_fixture/cellular.cpp
  user/tests/wiring/no_fixture/mesh.cpp
  user/tests/wiring/no_fixture/pwm.cpp
  user/tests/wiring/no_fixture/system.cpp
  user/tests/wiring/no_fixture/thread.cpp
  user/tests/wiring/no_fixture/wifi.cpp
Labels: backport, ready to merge

#1903 [ch34058] update release script to include Electron without DEBUG_BUILD=y and tinker-serial-debugging apps for Gen 3
  build/release.sh
Labels: internal, ready to merge

#1909 Do not mix logging and serial console output
  wiring/src/spark_wiring_logging.cpp
Labels: bug, ready to merge

#1902 BLE: wiring minor fixes
  wiring/inc/spark_wiring_ble.h
  wiring/src/spark_wiring_ble.cpp
Labels: ble, bug, ready to merge

#1901 BLE: user can optionally send characteristic value with/without ACK.
  hal/inc/ble_hal.h
  hal/inc/ble_hal_defines.h
  hal/inc/hal_dynalib_ble.h
  hal/src/nRF52840/ble_hal.cpp
  system/src/ble_control_request_channel.cpp
  user/tests/release-tests.json
  user/tests/wiring/ble_central_peripheral/ble_central/application.cpp
  user/tests/wiring/ble_central_peripheral/ble_central/central.cpp
  user/tests/wiring/ble_central_peripheral/ble_peripheral/application.cpp
  user/tests/wiring/ble_central_peripheral/ble_peripheral/peripheral.cpp
  user/tests/wiring/ble_scanner_broadcaster/ble_broadcaster/broadcaster.cpp
  user/tests/wiring/ble_scanner_broadcaster/ble_scanner/application.cpp
  user/tests/wiring/ble_scanner_broadcaster/ble_scanner/scanner.cpp
  user/tests/wiring/no_fixture_ble/application.cpp
  user/tests/wiring/no_fixture_ble/ble.cpp
  user/tests/wiring/no_fixture_ble/test.mk
  wiring/inc/spark_wiring_ble.h
  wiring/src/spark_wiring_ble.cpp
Labels: ble, enhancement, ready to merge

#1910 Git: fix submodules whitespace
  .gitmodules
Labels: ready to merge

#1911 [gen 2][lte] TCP socket closing slowly and TCPClient::connect() return values are incorrect
  hal/src/electron/modem/mdm_hal.cpp
  user/tests/wiring/no_fixture/tcp.cpp
  wiring/src/spark_wiring_tcpclient.cpp
  wiring/src/spark_wiring_tcpclient_posix.cpp
Labels: bug, ready to merge

#1912 Minor test fixes for 1.4.0
  user/tests/wiring/no_fixture/gpio.cpp
  user/tests/wiring/no_fixture_long_running/network.cpp
  wiring/src/spark_wiring_ipaddress.cpp
Labels: bug, internal, ready to merge

#1917 [electron, gen2] fixes RSSI failing due to Power Saving mode active [ch38428]
  hal/src/boron/network/sara_ncp_client.cpp
  hal/src/electron/modem/mdm_hal.cpp
Labels: bug, ready to merge, regression

#1920 Increase VitalsPublisher coverage
  system/src/system_publish_vitals.cpp
  system/src/system_publish_vitals.h
  test/unit_tests/cloud/publish_vitals.cpp
Labels: clubhouse, internal, needs review, realm/cloud-platform

#1709 Enable chrono string literals for time units
  user/inc/application.h
  user/tests/app/chrono_literals/chrono_literals.cpp
  user/tests/wiring/api/cellular.cpp
  user/tests/wiring/api/cloud.cpp
  user/tests/wiring/api/system.cpp
  user/tests/wiring/api/timedelay.cpp
  user/tests/wiring/api/wifi.cpp
  wiring/inc/spark_wiring_cellular.h
  wiring/inc/spark_wiring_cloud.h
  wiring/inc/spark_wiring_system.h
  wiring/inc/spark_wiring_ticks.h
  wiring/inc/spark_wiring_timer.h
  wiring/inc/spark_wiring_watchdog.h
  wiring/inc/spark_wiring_wifi.h
Labels: feature, needs review

#1915 BLE: fixes that setValue() doesn't work with BleTxRxType::AUTO if characteristic has WRITE property.
  user/tests/wiring/ble_central_peripheral/ble_central/central.cpp
  user/tests/wiring/ble_central_peripheral/ble_peripheral/peripheral.cpp
  wiring/src/spark_wiring_ble.cpp
Labels: ble, bug, ready to merge

#1916 BLE: discovered descriptor is incorrect
  hal/src/nRF52840/ble_hal.cpp
Labels: ble, bug, ready to merge

#1927 Feature/gen2 otp store
  bootloader/src/stm32f2xx/deviceid_hal.cpp
  bootloader/src/stm32f2xx/sources.mk
  hal/network/lwip/ublox/pppncpnetif.cpp
  hal/shared/platform_ncp.cpp
  hal/shared/platform_ncp.h
  hal/src/argon/network/esp32_ncp_client.h
  hal/src/argon/platform_ncp_argon.cpp
  hal/src/boron/cellular_hal.cpp
  hal/src/boron/network/cellular_ncp_client.h
  hal/src/boron/network/sara_ncp_client.cpp
  hal/src/boron/platform_ncp_boron.cpp
  hal/src/nRF52840/platform_ncp.h
  hal/src/stm32f2xx/deviceid_hal.cpp
  hal/src/stm32f2xx/ota_flash_hal_stm32f2xx.cpp
  hal/src/xenon/platform_ncp_xenon.cpp
  platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc/dct.h
  platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc/flash_mal.h
  platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/flash_mal.c
  platform/MCU/shared/STM32/inc/flash_access.h
Labels: feature, ready to merge

#1929 Fix: BLE scanning memory leak
  hal/src/nRF52840/ble_hal.cpp
  wiring/src/spark_wiring_ble.cpp
Labels: ble, bug, needs review

#1921 [system] Increase the input current limit from 900mA to 1500mA
  system/src/system_power_manager.cpp
  system/src/system_power_manager.h
Labels: bug, ready to merge

#1703 Define versions
  docs/artifacts.md
Labels: documentation, needs review

#1931 [gen 2] hal: enables reporting of serial and mobile secret from OTP area in listening mode (`i` command)
  hal/src/electron/ota_flash_hal.cpp
  hal/src/photon/ota_flash_hal.cpp
  hal/src/stm32f2xx/ota_flash_hal_stm32f2xx.h
Labels: bug
