Repository particle-iot/device-os, pull requests merged in 2019-02, with the labels that each got.

#1664 Bypass git dependency in build
  build/checks.mk
Labels: internal

#1688 [LTE/Electron] Fixes software Timer()'s halting after millis() overflows (every 49.7 days)
  hal/src/electron/rtos/FreeRTOSv8.2.2/FreeRTOS/Source/timers.c
Labels: bug

#1689 [LTE/Electron] bug fixes and enhancements
  hal/src/electron/modem/electronserialpipe_hal.cpp
  hal/src/electron/modem/electronserialpipe_hal.h
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
  hal/src/electron/modem/pipe_hal.h
  user/tests/wiring/no_fixture/cellular.cpp
  user/tests/wiring/no_fixture/pwm.cpp
Labels: bug, enhancement

#1651 Basic implementation for cellular command
  hal/src/boron/cellular_hal.cpp
  user/tests/hal/cellular/application.cpp
  user/tests/hal/cellular/test_cellular_command.cpp
Labels: in progress, mesh, needs review

#1682 [Gen 3] STOP sleep mode support
  hal/inc/core_hal.h
  hal/inc/exflash_hal.h
  hal/inc/hal_dynalib_core.h
  hal/inc/timer_hal.h
  hal/src/core/core_hal.c
  hal/src/gcc/core_hal.cpp
  hal/src/mesh-virtual/core_hal.cpp
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/exflash_hal.c
  hal/src/nRF52840/interrupts_hal.cpp
  hal/src/nRF52840/openthread/alarm.c
  hal/src/stm32f2xx/core_hal_stm32f2xx.c
  hal/src/template/core_hal.cpp
  platform/MCU/nRF52840/inc/sdk_config_system.h
  platform/MCU/nRF52840/src/hw_config.c
  system/src/system_network_manager_api.cpp
  system/src/system_sleep.cpp
  user/tests/app/sleep_multiple_pins/application.cpp
  user/tests/wiring/sleep/sleep.cpp
Labels: feature, mesh, needs review

#1691 0.9.0-rc.2
  CHANGELOG.md
  build/release.sh
  build/version.mk
  hal/inc/hal_platform.h
  hal/network/lwip/ipsockaddr.h
  hal/network/lwip/ppp_client.cpp
  hal/network/lwip/wiznet/wiznetif.cpp
  hal/src/nRF52840/concurrent_hal_impl.h
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/hal_platform_nrf52840_config.h
  modules/shared/system_module_version.mk
  release-mesh.sh
  system/inc/system_version.h
  system/system-versions.md
Labels: mesh, needs review

#1692 Fixes the order of functions exported in system dynalib
  hal/inc/hal_platform.h
  hal/inc/hal_platform_compat.h
  system/inc/system_dynalib.h
Labels: bug, mesh

#1698 [Internal] Adds missing Device OS release tests
  user/tests/readme.md
  user/tests/scripts/country-updown/country-updown.sh
  user/tests/scripts/p1sflashtest/p1sflashtest.sh
  user/tests/scripts/upgrade-downgrade/upgrade-downgrade.sh
  user/tests/wiring/spi_master_slave_alt/spi_master/application.cpp
  user/tests/wiring/spi_master_slave_alt/spi_master/spi_master.cpp
  user/tests/wiring/spi_master_slave_alt/spi_master/test.mk
  user/tests/wiring/spi_master_slave_alt/spi_slave/application.cpp
  user/tests/wiring/spi_master_slave_alt/spi_slave/spi_slave.cpp
  user/tests/wiring/spi_master_slave_alt/spi_slave/test.mk
Labels: internal

#1705 [Gen 3] NCP state reset
  hal/src/argon/network/esp32_ncp_client.cpp
  hal/src/boron/network/sara_ncp_client.cpp
Labels: bug, mesh, ready to merge
