Repository particle-iot/device-os, pull requests merged in 2020-01, with the labels that each got.

#1996 [gen3] fixes .particle/toolchains/gcc-arm/5.3.1/bin/objdump: not found issues in WB
  modules/shared/nRF52840/build_linker_script.mk
Labels: bug

#1994 [Gen 3] Logging modem AT commands and data TX/RX by default on modular Boron/B SoM [ch33624]
  hal/network/lwip/ppp_client.cpp
  hal/network/ncp/at_parser/at_parser_impl.cpp
  hal/src/boron/network/sara_ncp_client.cpp
Labels: enhancement, needs review

#1930 Improves cellular test coverage [ch35587]
  ci/unit_tests.sh
  hal/src/electron/cellular_internal.cpp
  test/unit_tests/cellular/cellular.cpp
Labels: internal, ready to merge

#1999 [b5som] Temporarily disables HW Flow Control
  hal/src/b5som/network/quectel_ncp_client.cpp
Labels: internal, ready to merge

#2000 [Gen3] Frees up some flash space
  hal/src/nRF52840/ble_hal.cpp
  hal/src/nRF52840/mbedtls/mbedtls_config_platform.h
Labels: internal, needs review

#2001 [Gen 3] Fix retained values not initializing correctly [ch42294]
  hal/inc/hal_platform.h
  hal/inc/hal_platform_compat.h
  hal/src/nRF52840/hal_platform_nrf52840_config.h
  wiring/src/user.cpp
Labels: bug, ready to merge

#1992 [Boron/Electron] Reverts defaults PMIC settings changes, adds higher level power config API
  hal/inc/hal_platform.h
  hal/inc/power_hal.h
  hal/inc/usb_hal.h
  hal/shared/power_hal.cpp
  hal/src/electron/sources.mk
  hal/src/nRF52840/hal_platform_nrf52840_config.h
  hal/src/nRF52840/i2c_hal.cpp
  hal/src/nRF52840/sources.mk
  hal/src/nRF52840/usb_hal.cpp
  platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc/dct.h
  platform/MCU/nRF52840/inc/dct.h
  services/inc/static_assert.h
  system/inc/system_dynalib.h
  system/inc/system_power.h
  system/src/system_power.cpp
  system/src/system_power_manager.cpp
  system/src/system_power_manager.h
  system/src/system_update.cpp
  user/tests/wiring/api/system.cpp
  user/tests/wiring/power_management/power.cpp
  wiring/inc/spark_wiring_power.h
  wiring/inc/spark_wiring_system.h
  wiring/inc/spark_wiring_system_power.h
  wiring/src/spark_wiring_power.cpp
Labels: enhancement, feature, ready to merge

#2007 Adds internal function to modify cellular registration timeout
  hal/inc/cellular_hal.h
  hal/inc/hal_dynalib_cellular.h
  hal/network/ncp/cellular/cellular_hal.cpp
  hal/network/ncp/cellular/cellular_ncp_client.h
  hal/src/b5som/network/quectel_ncp_client.cpp
  hal/src/b5som/network/quectel_ncp_client.h
  hal/src/boron/network/sara_ncp_client.cpp
  hal/src/boron/network/sara_ncp_client.h
  hal/src/electron/cellular_hal.cpp
  user/tests/wiring/api/cellular.cpp
Labels: internal, ready to merge

#2006 [b5som] hal: quectel modems don't support CHAP:<APN> in CGDCONT
  hal/src/b5som/network/quectel_ncp_client.cpp
Labels: bug, ready to merge

#2009 Don't check and write protect the system firmware on boot
  hal/src/stm32f2xx/core_hal_stm32f2xx.c
Labels: enhancement, ready to merge

#2008 [Gen 3] Boron 2G/3G fixes
  hal/src/boron/network/sara_ncp_client.cpp
Labels: bug, ready to merge
