Repository particle-iot/device-os, pull requests merged in 2020-12, with the labels that each got.

#2246 [gen3] bootloader: add workaround for MODULE_DROP_MODULE_INFO
  platform/MCU/nRF52840/src/flash_mal.c
Labels: bug

#2251 Always inline fastPinGetPinmap to speed pin sets
  user/tests/wiring/no_fixture/fastpin.cpp
  wiring/inc/fast_pin.h
Labels: enhancement

#2254 [gen3] bootloader: workaround incompatibility that required intermediate update through 1.1.0
  modules/shared/system_module_version.mk
  platform/MCU/nRF52840/inc/sdk_config_bootloader.h
  platform/MCU/nRF52840/src/hw_config.c
Labels: enhancement

#2248 [hal] sleep: allows the network to stay standby in HIBERNATE mode.
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
  hal/src/nRF52840/sleep_hal.cpp
  hal/src/stm32f2xx/sleep_hal.cpp
  user/tests/wiring/sleep20/sleep20.cpp
Labels: enhancement, ready to merge

#2256 [gen2] usart: fix D0 AF unconditionally being changed in hal_usart_end()
  hal/src/stm32f2xx/usart_hal.c
  user/tests/wiring/no_fixture/uart.cpp
Labels: bug

#2196 Gen3: SPI.transfer() supports accepting const void* parameter.
  hal/inc/hal_dynalib_spi.h
  hal/inc/spi_hal.h
  hal/src/nRF52840/spi_hal.cpp
  hal/src/stm32f2xx/spi_hal.c
  user/tests/wiring/no_fixture_spi/spix.cpp
  user/tests/wiring/spi_master_slave/spi_master/spi_master.cpp
  user/tests/wiring/spi_master_slave/spi_slave/spi_slave.cpp
  wiring/inc/spark_wiring_spi.h
  wiring/inc/spark_wiring_spi_proxy.h
  wiring/src/spark_wiring_spi.cpp
Labels: feature, needs review

#2237 BLE: supports legacy pairing.
  hal/inc/ble_hal.h
  hal/inc/ble_hal_defines.h
  hal/inc/hal_dynalib_ble.h
  hal/src/nRF52840/ble_hal.cpp
  user/tests/wiring/api/ble.cpp
  user/tests/wiring/ble_central_peripheral/ble_central/central.cpp
  user/tests/wiring/ble_central_peripheral/ble_peripheral/peripheral.cpp
  wiring/inc/spark_wiring_ble.h
  wiring/src/spark_wiring_ble.cpp
Labels: feature, needs review

#2205 [wiring] Network: introduce isOn() and isOff() APIs to enquiry the modem power state
  hal/inc/cellular_hal.h
  hal/inc/hal_dynalib_cellular.h
  hal/network/api/ifapi.h
  hal/network/lwip/basenetif.h
  hal/network/lwip/cellular/pppncpnetif.cpp
  hal/network/lwip/cellular/pppncpnetif.h
  hal/network/lwip/esp32/esp32ncpnetif.cpp
  hal/network/lwip/esp32/esp32ncpnetif.h
  hal/network/lwip/ifapi.cpp
  hal/network/lwip/wiznet/wiznetif.cpp
  hal/network/lwip/wiznet/wiznetif.h
  hal/network/ncp_client/quectel/quectel_ncp_client.cpp
  hal/network/ncp_client/sara/sara_ncp_client.cpp
  hal/src/electron/cellular_hal.cpp
  hal/src/electron/modem/mdm_hal.h
  system/inc/system_dynalib_net.h
  system/inc/system_network.h
  system/src/system_network_cellular.h
  system/src/system_network_compat.cpp
  system/src/system_network_internal.h
  system/src/system_network_manager.cpp
  system/src/system_network_manager.h
  system/src/system_network_manager_api.cpp
  system/src/system_network_wifi.h
  user/tests/unit/stubs/system_network.cpp
  user/tests/wiring/api/cellular.cpp
  user/tests/wiring/api/wifi.cpp
  user/tests/wiring/no_fixture/cellular.cpp
  wiring/inc/spark_wiring_network.h
  wiring/inc/spark_wiring_wifi.h
  wiring/src/spark_wiring_network.cpp
Labels: feature, needs review

#2257 Allow power manager to disable charging
  hal/inc/power_hal.h
  system/inc/system_dynalib.h
  system/inc/system_power.h
  system/src/system_power.cpp
  system/src/system_power_manager.cpp
  system/src/system_power_manager.h
  user/tests/wiring/power_management/power.cpp
  wiring/inc/spark_wiring_power.h
  wiring/inc/spark_wiring_system.h
  wiring/inc/spark_wiring_system_power.h
  wiring/src/spark_wiring_power.cpp
Labels: feature, needs review

#2217 Gen3: Network management improvement
  hal/network/lwip/cellular/pppncpnetif.cpp
  hal/network/lwip/cellular/pppncpnetif.h
  hal/network/lwip/esp32/esp32ncpnetif.cpp
  hal/network/lwip/esp32/esp32ncpnetif.h
  hal/network/ncp_client/quectel/quectel_ncp_client.cpp
  hal/network/ncp_client/sara/sara_ncp_client.cpp
Labels: enhancement, needs review

#2236 Signal values to percentage mapping
  hal/inc/cellular_hal.h
  hal/network/ncp/cellular/cellular_hal.cpp
  hal/shared/cellular_sig_perc_mapping.cpp
  hal/shared/cellular_sig_perc_mapping.h
  hal/src/electron/cellular_internal.cpp
  hal/src/electron/cellular_internal.h
  modules/electron/system-part1/src/cellular_hal.cpp
  test/unit_tests/cellular/CMakeLists.txt
  test/unit_tests/cellular/cellular.cpp
  user/tests/unit/makefile
Labels: needs review

#2258 Wiznetif: report module power state.
  hal/network/lwip/wiznet/wiznetif.cpp
  hal/network/lwip/wiznet/wiznetif.h
  system/src/system_sleep.cpp
Labels: bug, needs review
