Repository particle-iot/device-os, pull requests merged in 2020-09, with the labels that each got.

#2172 Support woken up by analog pin on Gen2 platforms.
  hal/src/stm32f2xx/sleep_hal.cpp
Labels: feature, needs review

#2173 Support woken up by USART on Gen2 platforms.
  hal/src/stm32f2xx/sleep_hal.cpp
Labels: feature, needs review

#2184 Gen2 I2C: fix the issue #2093.
  hal/src/stm32f2xx/i2c_hal.c
Labels: bug, ready to merge

#2194 [wiring] fastpin: use function with static variable to overcome initialization order woes
  wiring/inc/fast_pin.h
Labels: bug

#2195 [Gen 3] Add ftruncate() and truncate() support
  hal/inc/hal_dynalib_posix_syscall.h
  hal/src/nRF52840/posix/syscalls_posix.cpp
  user/tests/wiring/filesystem/posix.cpp
Labels: feature, ready to merge

#2190 [hal] core: expose functions to fetch serial/secret through dynalib
  hal/inc/hal_dynalib_core.h
Labels: feature

#2185 Twilio Fixes
  ci/unit_tests.sh
  hal/inc/cellular_hal.h
  hal/inc/cellular_hal_constants.h
  hal/inc/cellular_hal_utilities.h
  hal/network/ncp/cellular/cellular_network_manager.h
  hal/network/ncp/cellular/network_config_db.cpp
  hal/network/ncp/cellular/network_config_db.h
  hal/network/ncp_client/quectel/quectel_ncp_client.cpp
  hal/network/ncp_client/quectel/quectel_ncp_client.h
  hal/network/ncp_client/sara/sara_ncp_client.cpp
  hal/network/ncp_client/sara/sara_ncp_client.h
  hal/src/electron/cellular_hal.cpp
  hal/src/electron/cellular_hal_utilities.cpp
  hal/src/electron/cellular_internal.cpp
  hal/src/electron/cellular_internal.h
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
  modules/electron/system-part1/src/cellular_hal.cpp
  test/unit_tests/cellular/CMakeLists.txt
  test/unit_tests/cellular/cellular.cpp
  user/tests/unit/fuel_gauge.cpp
  wiring/inc/spark_wiring_fuel.h
  wiring/src/spark_wiring_fuel.cpp
  wiring/src/spark_wiring_wifi.cpp
Labels: bug

#2191 [electron] network: abort poweron/initialization sequence
  system/src/system_network_cellular.h
Labels: bug

#2198 [Electron] Recovery mechanics if modem becomes unresponsive
  hal/inc/cellular_hal.h
  hal/inc/hal_dynalib_cellular.h
  hal/inc/net_hal.h
  hal/shared/cellular_enums_hal.h
  hal/src/electron/cellular_hal.cpp
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
  system/src/system_network_cellular.h
  system/src/system_network_compat.cpp
  system/src/system_network_internal.h
  system/src/system_network_wifi.h
  user/tests/wiring/no_fixture/cellular.cpp
  user/tests/wiring/no_fixture_long_running/network.cpp
Labels: needs review

#2201 Add printf attributes to appropriate wiring functions, change Time::now() to use time32_t
  wiring/inc/fast_pin.h
  wiring/inc/spark_wiring_logging.h
  wiring/inc/spark_wiring_print.h
  wiring/inc/spark_wiring_spi.h
  wiring/inc/spark_wiring_time.h
  wiring/src/spark_wiring_print.cpp
  wiring/src/spark_wiring_time.cpp
Labels: needs review

#2197 Gen2: fix the electron power leakage issue when device is asleep.
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
  system/src/system_network_internal.h
Labels: bug, needs review

#2193 Test: add test case for I2C restarted transaction.
  user/tests/wiring/i2c_master_slave/i2c_master/i2c_master.cpp
  user/tests/wiring/i2c_master_slave/i2c_slave/i2c_slave.cpp
Labels: internal, needs review

#2186 Gen2: supports network wakeup source for Electron specifically.
  hal/src/nRF52840/sleep_hal.cpp
  hal/src/stm32f2xx/sleep_hal.cpp
  system/src/system_sleep.cpp
Labels: feature, needs review

#2202 Fix issue with serviceUUID not returning UUID when there is an array
  wiring/src/spark_wiring_ble.cpp
Labels: bug, needs review
