Repository particle-iot/device-os, pull requests merged in 2020-08, with the labels that each got.

#2169 [gen 2][electron] fixes timestamp wrapping at boot
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
Labels: bug, ready to merge

#2176 Clear OTA slots after updating firmware modules
  bootloader/src/main.c
  bootloader/src/stm32f2xx/core_hal.c
  platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/flash_mal.c
  platform/MCU/nRF52840/src/flash_mal.c
Labels: bug

#2178 Allowing the ALT server public key to be set in DCT programatically
  hal/inc/core_hal.h
  hal/src/nRF52840/ota_flash_hal.cpp
  hal/src/stm32f2xx/ota_flash_hal_stm32f2xx.cpp
Labels: bug

#2180 Gen3: fixes USART wakeup source for the ULP mode
  hal/src/nRF52840/sleep_hal.cpp
Labels: bug, ready to merge

#2183 [gen3] tone: fixes behavior with duration = 0
  hal/src/nRF52840/tone_hal.cpp
  user/tests/wiring/no_fixture/tone.cpp
Labels: bug, ready to merge

#2182 [wiring] cellular: mark CellularSignal::rssi and CellularSignal::qual as deprecated
  wiring/inc/spark_wiring_cellular_printable.h
  wiring/src/spark_wiring_cellular.cpp
  wiring/src/spark_wiring_cellular_printable.cpp
Labels: deprecation

#2181 [wiring] print: exclude printable objects from an overload taking integral and uint convertible types
  test/unit_tests/wiring/print.cpp
  wiring/inc/spark_wiring_print.h
Labels: bug, ready to merge
