Repository particle-iot/device-os, pull requests merged in 2020-05, with the labels that each got.

#2095 [wiring] spi: an attempt to bring back compatibility with SPIClass
  user/tests/wiring/api/spi.cpp
  wiring/inc/spark_wiring_spi.h
  wiring/inc/spark_wiring_spi_proxy.h
Labels: enhancement, needs review

#2100 Boron LTE-M1 radio unresponsive when sending large data continuously
  hal/inc/hal_platform.h
  hal/network/ncp/cellular/cellular_ncp_client.h
  hal/src/b5som/network/quectel_ncp_client.cpp
  hal/src/b5som/network/quectel_ncp_client.h
  hal/src/boron/hal_platform_config.h
  hal/src/boron/network/sara_ncp_client.cpp
  hal/src/boron/network/sara_ncp_client.h
  system/src/system_cloud_internal.cpp
Labels: bug, ready to merge

#2103 GCC 9 support
  .buildpackrc
  .workbench/manifest.json
  bootloader/src/main.c
  hal/inc/spi_hal.h
  hal/src/electron/core_hal.c
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/interrupts_hal.cpp
  hal/src/nRF52840/sleep_hal.cpp
  hal/src/nRF52840/spi_hal.cpp
  hal/src/nRF52840/timer_hal.cpp
  hal/src/newhal/concurrent_hal_impl.h
  hal/src/photon/core_hal.c
  scripts/fetch-buildpack
  user/tests/wiring/api/arduino.cpp
  user/tests/wiring/api/cloud.cpp
  user/tests/wiring/api/led.cpp
  user/tests/wiring/api/network.cpp
  user/tests/wiring/api/string.cpp
  user/tests/wiring/api/system.cpp
  user/tests/wiring/api/wifi.cpp
  user/tests/wiring/no_fixture/spi.cpp
  user/tests/wiring/no_fixture/system.cpp
  user/tests/wiring/no_fixture/thread.cpp
  wiring/inc/spark_wiring_print.h
  wiring/inc/spark_wiring_string.h
  wiring/src/spark_wiring_string.cpp
  wiring/src/spark_wiring_usartserial.cpp
  wiring_globals/src/wiring_globals_i2c.cpp
Labels: enhancement, ready to merge

#2105 [Boron] Radio unresponsive when sending large data or application desc msgs
  hal/src/boron/network/sara_ncp_client.cpp
  hal/src/boron/network/sara_ncp_client.h
Labels: bug, ready to merge

#2094 FuelGauge: return error if it failed to read/write registers.
  wiring/inc/spark_wiring_fuel.h
  wiring/src/spark_wiring_fuel.cpp
Labels: enhancement, ready to merge

#2096 [wiring]: change I2C timeout in FuelGauge and PMIC to a more manageab…
  wiring/inc/spark_wiring_fuel.h
  wiring/inc/spark_wiring_power.h
  wiring/src/spark_wiring_fuel.cpp
  wiring/src/spark_wiring_power.cpp
Labels: enhancement, ready to merge

#2080 [hal] i2c: bus is driven low if building with JTAG/SWD enabled.
  hal/src/electron/pinmap_defines.h
  hal/src/photon/pinmap_defines.h
  hal/src/stm32f2xx/core_hal_stm32f2xx.c
Labels: bug, ready to merge

#2104 [boron] forward compatibility with 460800 baudrate on SARA R4
  hal/src/boron/network/sara_ncp_client.cpp
Labels: enhancement, ready to merge

#2107 [boron] fixes SARA R4 power on sequence in light of recent baudrate c…
  hal/src/boron/network/sara_ncp_client.cpp
  hal/src/boron/network/sara_ncp_client.h
Labels: bug, ready to merge

#2098 Add a new member to differentiate internal and wiring setSecurity
  hal/src/photon/softap.cpp
  system/src/system_setup.cpp
  user/tests/wiring/api/wifi.cpp
  wiring/inc/spark_wiring_wifi_credentials.h
Labels: enhancement, ready to merge

#2112 [hal] Forbid BG96 falling back to 2G network
  hal/src/b5som/network/quectel_ncp_client.cpp
Labels: enhancement, ready to merge

#2115 [Gen2] Fix buffer overrun in modem hal
  hal/shared/cellular_enums_hal.h
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
Labels: bug, ready to merge

#2116 Fixes the issue that FuelGauge doesn't work as expected after being woken up
  system/src/system_power_manager.cpp
Labels: bug, ready to merge
