Repository particle-iot/device-os, pull requests merged in 2020-07, with the labels that each got.

#2141 [gen3] syscall: our newlib variant implements rename as _link + _unlink
  hal/src/nRF52840/posix/syscalls_posix.cpp
  user/tests/wiring/filesystem/posix.cpp
Labels: bug, ready to merge

#2143 Add unit tests for SPISettings
  user/tests/wiring/api/spi.cpp
  user/tests/wiring/no_fixture_spi/spi.cpp
  user/tests/wiring/spi1_stress/application.cpp
  user/tests/wiring/spi1_stress/port.cpp
Labels: internal, ready to merge

#2140 Some changes in order to run no fixture tests under test runner / CI
  build/release.sh
  build/version.mk
  modules/shared/system_module_version.mk
  system/inc/system_version.h
  system/system-versions.md
  user/tests/integration/application/src/application.cpp
  user/tests/integration/wiring/no_fixture
  user/tests/wiring/no_fixture/application.cpp
  user/tests/wiring/no_fixture/cellular.cpp
  user/tests/wiring/no_fixture/led.cpp
  user/tests/wiring/no_fixture/no_fixture.spec.js
  user/tests/wiring/no_fixture/system.cpp
  user/tests/wiring/no_fixture/time.cpp
  user/tests/wiring/no_fixture/wifi.cpp
Labels: internal

#2134 Fixes the issue that gen3 devices cannot be woken up by RTC.
  hal/src/nRF52840/sleep_hal.cpp
  hal/src/nRF52840/timer_hal.cpp
Labels: bug, ready to merge

#2144 Support for super APN based on Twilio ICCID
  hal/inc/cellular_hal.h
  hal/inc/cellular_hal_constants.h
  hal/inc/concurrent_hal.h
  hal/inc/hal_dynalib_cellular.h
  hal/network/ncp/cellular/cellular_hal.cpp
  hal/network/ncp/cellular/network_config_db.cpp
  hal/network/ncp/cellular/network_config_db.h
  hal/network/ncp_client/quectel/quectel_ncp_client.cpp
  hal/network/ncp_client/sara/sara_ncp_client.cpp
  hal/network/util/simple_ntp_client.cpp
  hal/src/electron/cellular_hal.cpp
  hal/src/electron/cellular_internal.cpp
  hal/src/electron/cellular_internal.h
  system/src/system_publish_vitals.cpp
  test/unit_tests/CMakeLists.txt
  test/unit_tests/cellular/CMakeLists.txt
  test/unit_tests/cellular/cellular.cpp
  test/unit_tests/cloud/CMakeLists.txt
  test/unit_tests/communication/CMakeLists.txt
  test/unit_tests/hal/simple_ntp_client/posix/socket_hal_posix_impl.h
  test/unit_tests/services/CMakeLists.txt
  test/unit_tests/wiring/CMakeLists.txt
  wiring/inc/spark_wiring_timer.h
Labels: feature, needs review

#2110 Fix the power leakage issue when putting Cellular device …
  crypto/inc/mbedtls_config_photon.h
  hal/build.mk
  hal/inc/sleep_hal.h
  hal/network/api/ifapi.h
  hal/network/lwip/basenetif.h
  hal/network/lwip/cellular/pppncpnetif.cpp
  hal/network/lwip/cellular/pppncpnetif.h
  hal/network/lwip/esp32/esp32ncpnetif.cpp
  hal/network/lwip/esp32/esp32ncpnetif.h
  hal/network/lwip/ifapi.cpp
  hal/network/lwip/wiznet/wiznetif.cpp
  hal/network/lwip/wiznet/wiznetif.h
  hal/network/ncp/cellular/cellular_hal.cpp
  hal/network/ncp/ncp_client.h
  hal/network/ncp_client/esp32/esp32_ncp_client.cpp
  hal/network/ncp_client/esp32/esp32_ncp_client.h
  hal/network/ncp_client/quectel/quectel_ncp_client.cpp
  hal/network/ncp_client/quectel/quectel_ncp_client.h
  hal/network/ncp_client/sara/sara_ncp_client.cpp
  hal/network/ncp_client/sara/sara_ncp_client.h
  hal/src/nRF52840/radio_common.cpp
  hal/src/nRF52840/radio_common.h
  hal/src/nRF52840/serial_stream.cpp
  hal/src/nRF52840/serial_stream.h
  hal/src/nRF52840/sleep_hal.cpp
  system/inc/system_network.h
  system/inc/system_sleep_configuration.h
  system/src/system_network_compat.cpp
  system/src/system_network_manager.cpp
  system/src/system_network_manager.h
  system/src/system_network_manager_api.cpp
  system/src/system_sleep.cpp
  system/src/system_sleep_compat.cpp
  wiring/inc/spark_wiring_system.h
  wiring/src/spark_wiring_system.cpp
Labels: bug, ready to merge

#2133 Implement sleep API for ADC on Gen2 and Gen3 device
  hal/inc/adc_hal.h
  hal/inc/hal_dynalib_gpio.h
  hal/src/nRF52840/adc_hal.cpp
  hal/src/stm32f2xx/adc_hal.c
  hal/src/template/adc_hal.cpp
  user/tests/hal/adc/test_adc.cpp
  wiring/src/spark_wiring.cpp
  wiring_globals/src/spark_wiring_gpio.cpp
Labels: feature, ready to merge

#2132 [Gen3] Implement sleep function for PWM peripheral
  hal/inc/hal_dynalib_gpio.h
  hal/inc/pwm_hal.h
  hal/src/nRF52840/pinmap_hal.c
  hal/src/nRF52840/pwm_hal.cpp
  hal/src/nRF52840/rgbled_hal.c
  hal/src/nRF52840/servo_hal.cpp
  hal/src/nRF52840/tone_hal.cpp
  hal/src/stm32/pwm_hal.c
  hal/src/stm32f2xx/rgbled_hal.cpp
  hal/src/template/pwm_hal.cpp
  user/tests/hal/pwm/test_pwm.cpp
  user/tests/wiring/no_fixture/led.cpp
  user/tests/wiring/no_fixture_long_running/pwm.cpp
  wiring_globals/src/spark_wiring_gpio.cpp
Labels: feature, ready to merge

#2129 Implement sleep function for I2C peripheral
  hal/inc/hal_dynalib_i2c.h
  hal/inc/i2c_hal.h
  hal/src/nRF52840/i2c_hal.cpp
  hal/src/nRF52840/usart_hal.cpp
  hal/src/stm32f2xx/i2c_hal.c
  hal/src/template/i2c_hal.cpp
  hal/src/tracker/am18x5.cpp
  hal/src/tracker/am18x5.h
  user/tests/wiring/i2c_master_slave/common/common.inc
  user/tests/wiring/i2c_master_slave/i2c_master/i2c_master.cpp
  wiring/inc/spark_wiring_i2c.h
  wiring/src/spark_wiring_i2c.cpp
  wiring_globals/src/wiring_globals_i2c.cpp
Labels: feature, ready to merge

#2130 Implement sleep function for SPI peripheral
  hal/inc/hal_dynalib_spi.h
  hal/inc/spi_hal.h
  hal/network/lwip/wiznet/wiznetif.cpp
  hal/network/lwip/wiznet/wiznetif.h
  hal/src/nRF52840/spi_hal.cpp
  hal/src/stm32f2xx/spi_hal.c
  hal/src/template/spi_hal.cpp
  hal/src/tracker/mcp23s17.cpp
  hal/src/tracker/mcp23s17.h
  user/tests/hal/spi/test_spi.cpp
  user/tests/wiring/no_fixture_spi/spi.cpp
  user/tests/wiring/spi_master_slave/spi_master/spi_master.cpp
  user/tests/wiring/spi_master_slave/spi_master_ethernet_concurrency/spi_master.cpp
  user/tests/wiring/spi_master_slave/spi_slave/spi_slave.cpp
  wiring/inc/spark_wiring_spi.h
  wiring/inc/spark_wiring_spi_proxy.h
  wiring/src/spark_wiring_spi.cpp
Labels: feature, needs review

#2125 Implement sleep function for UART peripheral.
  hal/inc/hal_dynalib_usart.h
  hal/inc/usart_hal.h
  hal/inc/usart_hal_private.h
  hal/src/electron/modem/electronserialpipe_hal.cpp
  hal/src/gcc/usart_hal.cpp
  hal/src/nRF52840/i2c_hal.cpp
  hal/src/nRF52840/serial_stream.cpp
  hal/src/nRF52840/serial_stream.h
  hal/src/nRF52840/sleep_hal.cpp
  hal/src/nRF52840/usart_hal.cpp
  hal/src/stm32f2xx/sleep_hal.cpp
  hal/src/stm32f2xx/usart_hal.c
  hal/src/template/usart_hal.cpp
  services/inc/ringbuffer.h
  user/libraries/Serial2/Serial2.h
  user/libraries/Serial3/Serial3.h
  user/libraries/Serial4/Serial4.h
  user/libraries/Serial5/Serial5.h
  user/tests/hal/uart/test_uart.cpp
  user/tests/wiring/no_fixture_long_running/network.cpp
  user/tests/wiring/serial_loopback2/loopback.cpp
  wiring/inc/spark_wiring_usartserial.h
  wiring/src/spark_wiring_usartserial.cpp
Labels: feature, ready to merge

#2136 Implement sleep function for external flash
  hal/inc/exflash_hal.h
  hal/src/nRF52840/exflash_hal.c
Labels: feature, ready to merge

#2147 Enable the buck converter of PMIC by default.
  system/src/system_power_manager.cpp
Labels: bug, ready to merge

#2146 [Boron LTE] Muxer resumption to be checked at multiple baud rates as needed
  hal/network/ncp_client/sara/sara_ncp_client.cpp
  hal/network/ncp_client/sara/sara_ncp_client.h
Labels: bug, needs review

#2152 Workaround for Gen 3 devices not connecting to the cloud in non-automatic threaded mode
  system/src/system_network_manager_api.cpp
Labels: bug

#2149 Implement the Ultra-low Power mode
  hal/inc/hal_platform.h
  hal/inc/hal_platform_compat.h
  hal/inc/sleep_hal.h
  hal/inc/usart_hal.h
  hal/network/ncp_client/quectel/quectel_ncp_client.cpp
  hal/network/ncp_client/sara/sara_ncp_client.cpp
  hal/src/argon/hal_platform_config.h
  hal/src/b5som/hal_platform_config.h
  hal/src/boron/hal_platform_config.h
  hal/src/nRF52840/exflash_hal.c
  hal/src/nRF52840/i2c_hal.cpp
  hal/src/nRF52840/radio_common.cpp
  hal/src/nRF52840/serial_stream.cpp
  hal/src/nRF52840/sleep_hal.cpp
  hal/src/nRF52840/spi_hal.cpp
  hal/src/nRF52840/usart_hal.cpp
  hal/src/stm32f2xx/i2c_hal.c
  hal/src/stm32f2xx/sleep_hal.cpp
  hal/src/stm32f2xx/spi_hal.c
  hal/src/stm32f2xx/usart_hal.c
  hal/src/tracker/hal_platform_config.h
  services/inc/services2_dynalib.h
  system/src/system_sleep.cpp
  user/tests/wiring/api/system.cpp
  user/tests/wiring/sleep20/sleep20.cpp
Labels: feature, needs review

#2154 [gen2] rtc: hal_rtc_get_time() is not thread-safe
  hal/src/stm32f2xx/rtc_hal.c
Labels: bug

#2155 BLE cannot restart advertising when it is asleep.
  hal/src/nRF52840/sleep_hal.cpp
Labels: bug, needs review

#2151 [gen3] bootloader updates through MBR
  bootloader/src/main.c
  build/arm/linker/nrf52840/softdevice.ld
  hal/src/nRF52840/ota_flash_hal.cpp
  modules/shared/system_module_version.mk
  platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/flash_mal.c
  platform/MCU/nRF52840/inc/flash_access.h
  platform/MCU/nRF52840/inc/flash_mal.h
  platform/MCU/nRF52840/src/flash_mal.c
  platform/MCU/nRF52840/src/hw_config.c
  platform/MCU/shared/STM32/inc/flash_access.h
  third_party/nrf5_sdk/include.mk
Labels: feature, needs review

#2153 [gen3] cellular: parser should not be accessed without a lock
  hal/network/ncp/cellular/cellular_hal.cpp
Labels: bug

#2159 FuelGauge waking up enhancement
  system/src/system_power_manager.cpp
  system/src/system_power_manager.h
Labels: enhancement, needs review

#2164 Only run AT+COPS=0 if currently de-registered, to avoid PLMN reselection
  hal/network/ncp_client/quectel/quectel_ncp_client.cpp
  hal/network/ncp_client/sara/sara_ncp_client.cpp
  hal/src/electron/modem/mdm_hal.cpp
Labels: enhancement

#2163 Supports waking up from STOP/ULP/Hibernate mode by analog pin on Gen3 platforms
  hal/inc/sleep_hal.h
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/sleep_hal.cpp
  system/inc/system_sleep_configuration.h
  user/tests/wiring/api/system.cpp
  user/tests/wiring/sleep20/sleep20.cpp
Labels: feature, ready to merge

#2162 Supports waking up from STOP/ULP mode by USART/Wi-FI/Cellular on Gen3 platforms
  hal/inc/hal_platform.h
  hal/inc/hal_platform_compat.h
  hal/inc/sleep_hal.h
  hal/src/argon/hal_platform_config.h
  hal/src/b5som/hal_platform_config.h
  hal/src/boron/hal_platform_config.h
  hal/src/nRF52840/sleep_hal.cpp
  hal/src/stm32f2xx/sleep_hal.cpp
  hal/src/tracker/hal_platform_config.h
  system/inc/system_sleep_configuration.h
  system/src/system_sleep.cpp
  user/tests/wiring/api/system.cpp
  user/tests/wiring/sleep20/sleep20.cpp
  wiring/inc/spark_wiring_system.h
Labels: feature, ready to merge
