Repository particle-iot/device-os, pull requests merged in 2020-02, with the labels that each got.

#2014 Minimum registration timeout is 5 minutes
  hal/inc/cellular_hal.h
  hal/src/b5som/network/quectel_ncp_client.cpp
  hal/src/boron/network/sara_ncp_client.cpp
Labels: internal, ready to merge

#2012 prevent expansion of `EXTRA_CFLAGS` build env var
  user/build.mk
Labels: internal, ready to merge

#2015 Adds SystemPowerFeature::DISABLE to disable system power management
  hal/inc/power_hal.h
  hal/src/nRF52840/usb_hal_cdc.c
  system/src/system_power_manager.cpp
  system/src/system_power_manager.h
  user/tests/wiring/api/system.cpp
  user/tests/wiring/power_management/power.cpp
  wiring/inc/spark_wiring_system_power.h
Labels: enhancement, ready to merge

#2010 [Gen 3] Workaround for QSPI/XIP nRF52840 hardware anomaly 215
  hal/src/nRF52840/exflash_hal.c
  hal/src/nRF52840/ota_flash_hal.cpp
  hal/src/stm32f2xx/ota_flash_hal_stm32f2xx.cpp
  user/tests/release-tests.json
  user/tests/wiring/no_fixture_stress/application.cpp
  user/tests/wiring/no_fixture_stress/exflash.cpp
  user/tests/wiring/no_fixture_stress/test.mk
Labels: bug, needs review

#2011 Removes asom and xsom platforms
  .buildpackrc
  .travis.yml
  .workbench/manifest.json
  bootloader/src/nRF52840/usbd_device.cpp
  build/create_module.py
  build/make_release.sh
  build/module.mk
  build/platform-id.mk
  build/release-publish.sh
  build/release-tests.sh
  build/release.sh
  ci/enumerate_build_matrix.sh
  hal/network/openthread/border_router_manager.cpp
  hal/shared/platforms.h
  hal/src/argon/app_usbd_string_config.h
  hal/src/argon/bootloader_platform_22.c
  hal/src/argon/hal_platform_config.h
  hal/src/argon/network/esp32_ncp_client.cpp
  hal/src/argon/network/network.cpp
  hal/src/argon/pinmap_defines.h
  hal/src/argon/pinmap_hal.c
  hal/src/argon/user_platform_22.c
  hal/src/gcc/platform_config.h
  hal/src/nRF52840/radio_common.cpp
  hal/src/nRF52840/usart_hal.cpp
  hal/src/xenon/app_usbd_string_config.h
  hal/src/xenon/bootloader_platform_24.c
  hal/src/xenon/hal_platform_config.h
  hal/src/xenon/network/network.cpp
  hal/src/xenon/pinmap_defines.h
  hal/src/xenon/pinmap_hal.c
  hal/src/xenon/user_platform_24.c
  main/makefile
  modules/argon/system-part1/makefile
  modules/xenon/system-part1/makefile
  newlib_nano/src/sources.mk
  platform/MCU/nRF52840/inc/platform_config.h
  system/src/control/wifi.cpp
  system/src/system_network_diagnostics.cpp
  system/src/system_update.cpp
  user/applications/tinker/application.cpp
  user/tests/release-tests.json
  user/tests/wiring/no_fixture/pwm.cpp
  user/tests/wiring/no_fixture_long_running/pwm.cpp
  user/tests/wiring/spi_master_slave/spi_master/spi_master.cpp
  user/tests/wiring/spi_master_slave/spi_slave/spi_slave.cpp
  user/tests/wiring/spi_master_slave_alt/spi_master/spi_master.cpp
  user/tests/wiring/spi_master_slave_alt/spi_slave/spi_slave.cpp
  wiring/inc/fast_pin.h
  wiring/src/spark_wiring_wifitester.cpp
Labels: internal, needs review, ready to merge

#1973 Add boundary checking to format string copy
  wiring/src/spark_wiring_time.cpp
Labels: bug, ready to merge

#1986 Feature/sleep20
  hal/inc/ble_hal.h
  hal/inc/hal_dynalib_core.h
  hal/inc/hal_platform.h
  hal/inc/hal_platform_compat.h
  hal/inc/sleep_hal.h
  hal/src/argon/hal_platform_config.h
  hal/src/gcc/sleep_hal.cpp
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/hal_platform_nrf52840_config.h
  hal/src/nRF52840/sleep_hal.cpp
  hal/src/stm32f2xx/core_hal_stm32f2xx.c
  hal/src/stm32f2xx/sleep_hal.cpp
  hal/src/template/sleep_hal.cpp
  services/inc/enumflags.h
  services/inc/system_defs.h
  system/inc/system_dynalib.h
  system/inc/system_network.h
  system/inc/system_sleep.h
  system/inc/system_sleep_configuration.h
  system/src/system_power_manager.cpp
  system/src/system_sleep.cpp
  system/src/system_sleep_compat.cpp
  user/tests/wiring/api/system.cpp
  user/tests/wiring/sleep20/application.cpp
  user/tests/wiring/sleep20/sleep20.cpp
  user/tests/wiring/sleep20/test.mk
  wiring/inc/spark_wiring_network.h
  wiring/inc/spark_wiring_system.h
  wiring/src/spark_wiring_system.cpp
Labels: feature, needs review, realm/embedded-platform

#2016 Clear WLAN WD so it does not interfere with Particle.connect()
  system/src/system_network_internal.h
  user/tests/wiring/cell_connect_after_off/application.cpp
  user/tests/wiring/cell_connect_after_off/cellular_conn_after_off.cpp
  user/tests/wiring/cell_connect_after_off/readme.md
Labels: bug, ready to merge, realm/cellular, realm/embedded-platform

#2020 update workbench manifest with latest `buildscripts` dependency
  .workbench/manifest.json
Labels: enhancement, ready to merge

#2023 [wiring] Fixes a regression in SPI due to thread-safety additions from #1879
  wiring/inc/spark_wiring_arduino.h
  wiring/inc/spark_wiring_spi.h
  wiring/src/spark_wiring_spi.cpp
  wiring_globals/src/wiring_globals_spi.cpp
Labels: bug, ready to merge, regression

#1997 Fixes BLE UUID conversion issue.
  user/tests/wiring/no_fixture_ble/application.cpp
  user/tests/wiring/no_fixture_ble/ble.cpp
  wiring/inc/spark_wiring_ble.h
  wiring/src/spark_wiring_ble.cpp
Labels: ble, bug, ready to merge

#1998 Thread-safe cloud variables
  communication/inc/coap.h
  communication/inc/protocol.h
  communication/inc/protocol_defs.h
  communication/inc/spark_descriptor.h
  communication/src/build.mk
  communication/src/coap.cpp
  communication/src/messages.cpp
  communication/src/messages.h
  communication/src/protocol.cpp
  communication/src/protocol_defs.cpp
  communication/src/variables.cpp
  communication/src/variables.h
  system/inc/system_cloud.h
  system/src/system_cloud_internal.cpp
  system/src/system_cloud_internal.h
  test/unit_tests/communication/CMakeLists.txt
  user/tests/integration/communication/variables/variables.cpp
  user/tests/integration/communication/variables/variables.spec.js
  user/tests/wiring/api/cloud.cpp
  wiring/inc/spark_wiring_cloud.h
Labels: bug, enhancement, ready to merge

#2030 Change the prefix of BLE broadcasting name for B5SoM.
  hal/inc/hal_platform.h
  hal/inc/hal_platform_compat.h
  hal/src/argon/hal_platform_config.h
  hal/src/b5som/hal_platform_config.h
  hal/src/boron/hal_platform_config.h
  hal/src/nRF52840/device_code.cpp
  hal/src/xenon/hal_platform_config.h
Labels: bug, ready to merge

#2034 [hal] usb serial: return -1 instead of 0 when there's no data to read
  hal/src/nRF52840/usb_hal.cpp
Labels: bug, ready to merge

#2027 [test] unit: fixes Print tests failing
  test/unit_tests/wiring/print.cpp
Labels: bug, internal, ready to merge

#2031 [Gen 2] Fixes socket leak in UDP.begin()
  user/tests/wiring/no_fixture/cellular.cpp
  user/tests/wiring/no_fixture/network.cpp
  wiring/src/spark_wiring_udp.cpp
Labels: bug, ready to merge

#2022 Introduce configurable I2C buffer
  hal/inc/hal_dynalib_i2c.h
  hal/inc/i2c_hal.h
  hal/src/nRF52840/i2c_hal.cpp
  hal/src/stm32f2xx/i2c_hal.c
  hal/src/template/i2c_hal.cpp
  user/tests/wiring/i2c_master_slave/common/common.inc
  user/tests/wiring/i2c_master_slave/i2c_master/i2c_master.cpp
  user/tests/wiring/i2c_master_slave/i2c_master/test.mk
  user/tests/wiring/i2c_master_slave/i2c_slave/i2c_slave.cpp
  user/tests/wiring/i2c_master_slave/i2c_slave/test.mk
  wiring/inc/spark_wiring_i2c.h
  wiring/src/spark_wiring_i2c.cpp
  wiring_globals/src/wiring_globals_i2c.cpp
Labels: enhancement, ready to merge

#2019 Fix CGI for Quectel modems
  hal/src/b5som/network/quectel_ncp_client.cpp
  hal/src/boron/network/sara_ncp_client.cpp
Labels: bug, ready to merge

#2026 String::substring() unnecessarily modifies the source buffer
  user/tests/unit/string.cpp
  wiring/src/spark_wiring_string.cpp
Labels: enhancement, ready to merge

#2017 Fix parsing of large AT command responses
  hal/network/ncp/at_parser/at_response.cpp
  hal/network/ncp/at_parser/at_response.h
Labels: bug, ready to merge

#2029 [Gen 3] Fixes renegotiation of options and adds IPCP packet parsing
  hal/network/lwip/ppp_client.cpp
  hal/network/lwip/ppp_configuration_option.h
  hal/network/lwip/ppp_ipcp.cpp
  hal/network/lwip/ppp_ipcp.h
  hal/network/lwip/ppp_ipcp_options.cpp
  hal/network/lwip/ppp_ipcp_options.h
  hal/network/lwip/ppp_ncp.h
  hal/src/b5som/network/quectel_ncp_client.cpp
  hal/src/nRF52840/lwip/lwippppopts.h
Labels: bug, enhancement

#2041 [gcc] fixes builds on osx and enables usage of the latest gcc versions
  ci/install_boost.sh
  crypto/inc/mbedtls_config_default.h
  hal/src/gcc/boost_posix_time_wrap.h
  hal/src/gcc/delay_hal.cpp
  hal/src/gcc/ota_flash_hal.cpp
  hal/src/gcc/pinger.cpp
  hal/src/gcc/rtc_hal.cpp
  hal/src/gcc/sleep_hal.cpp
  hal/src/gcc/socket_hal.cpp
  hal/src/gcc/timer_hal.cpp
  hal/src/gcc/wlan_hal.cpp
  services/inc/atclient.h
  services/src/atclient.cpp
  services/src/panic.c
  system/inc/system_setup.h
  system/inc/system_update.h
  system/src/system_listening_mode.cpp
  system/src/system_setup.cpp
  test/unit_tests/CMakeLists.txt
  user/tests/unit/makefile
  wiring/inc/spark_wiring_vector.h
Labels: enhancement, internal, needs review
