Repository particle-iot/device-os, pull requests merged in 2020-04, with the labels that each got.

#2067 [Cellular] Fixes an issue with CGI (Cellular Global Identity) not available on some devices
  hal/network/ncp/cellular/cellular_hal.cpp
  hal/src/electron/cellular_hal.cpp
Labels: bug, ready to merge, regression

#2069 Enable HW Flow control on Quectel modems earlier in the init process
  hal/src/b5som/network/quectel_ncp_client.cpp
Labels: enhancement, needs review

#2071 Move code to wait for AT after setting run time baud
  hal/src/b5som/network/quectel_ncp_client.cpp
Labels: needs review

#2070 [electron] cellular: compat rssi/qual for LTE devices using UCGED
  hal/src/electron/modem/mdm_hal.cpp
Labels: bug, ready to merge, regression

#2075 Increase the size of the ARP queue
  hal/src/nRF52840/lwip/lwipopts.h
Labels: bug

#2043 Adding diag id for transmitted msgs, and changing name of resend to r…
  ci/enumerate_build_matrix.sh
  communication/src/coap_channel.h
  communication/src/communication_diagnostic.cpp
  communication/src/communication_diagnostic.h
  services/inc/diagnostics.h
  system/src/main.cpp
  system/src/system_cloud_internal.h
  system/src/system_network_diagnostics.cpp
  system/src/system_network_internal.h
  system/src/system_update.cpp
  user/tests/unit/diagnostics.cpp
  wiring/inc/spark_wiring_diagnostics.h
Labels: feature, ready to merge

#2050 Add diag for coap latency
  communication/src/coap_channel.cpp
  communication/src/coap_channel.h
  communication/src/communication_diagnostic.cpp
  communication/src/communication_diagnostic.h
  services/inc/diagnostics.h
Labels: enhancement, ready to merge

#2072 [cellular] increase registartion timeout to 10 minutes
  hal/src/b5som/network/quectel_ncp_client.cpp
  hal/src/boron/network/sara_ncp_client.cpp
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
Labels: enhancement, ready to merge

#2045 OTA adjustments for Argon
  communication/inc/protocol.h
  communication/inc/protocol_defs.h
  communication/src/chunked_transfer.cpp
  communication/src/chunked_transfer.h
Labels: bug, ready to merge

#2024 Describe message fixes
  communication/inc/dtls_session_persist.h
  communication/inc/protocol.h
  communication/inc/protocol_defs.h
  communication/inc/spark_descriptor.h
  communication/inc/spark_protocol_functions.h
  communication/src/coap_channel.h
  communication/src/dtls_message_channel.cpp
  communication/src/dtls_message_channel.h
  communication/src/dtls_protocol.cpp
  communication/src/lightssl_message_channel.h
  communication/src/lightssl_protocol.h
  communication/src/message_channel.h
  communication/src/messages.cpp
  communication/src/messages.h
  communication/src/protocol.cpp
  communication/src/spark_protocol_functions.cpp
  communication/src/subscriptions.h
  platform/MCU/nRF52840/inc/hw_system_flags.h
  platform/MCU/newhal-mcu/inc/hw_config.h
  system/inc/system_task.h
  system/src/main.cpp
  system/src/system_cloud.cpp
  system/src/system_cloud_internal.cpp
  system/src/system_cloud_internal.h
  system/src/system_task.cpp
  test/unit_tests/communication/coap_reliability.cpp
  test/unit_tests/communication/forward_message_channel.h
  user/tests/app/device_initiated_describe/device_initiated_describe.cpp
  user/tests/app/device_initiated_describe/test.mk
Labels: bug, enhancement, ready to merge

#2078 Invalidate value of '0' for RSRP and RSRQ on B5SoM
  hal/src/b5som/network/quectel_ncp_client.cpp
Labels: bug, ready to merge

#2081 [wiring] BLE: use 'delete' in corresponding to the 'new' keyword
  wiring/src/spark_wiring_ble.cpp
Labels: bug, needs review

#2083 Map AccessTechnology correctly on SARA R410M
  hal/network/ncp/cellular/cellular_hal.cpp
  hal/network/ncp/cellular/cellular_ncp_client.h
  hal/shared/cellular_enums_hal.h
  hal/src/b5som/network/quectel_ncp_client.cpp
  hal/src/boron/network/sara_ncp_client.cpp
  hal/src/electron/modem/mdm_hal.cpp
Labels: enhancement, needs review

#2084 Gen3: fixes I2C hang up issue
  hal/src/nRF52840/i2c_hal.cpp
Labels: bug, ready to merge

#2086 [hal] sleep: allow to enter hibernate mode without specifying any wak…
  hal/src/nRF52840/sleep_hal.cpp
  hal/src/stm32f2xx/sleep_hal.cpp
  user/tests/wiring/sleep20/sleep20.cpp
Labels: bug, ready to merge

#2090 [nrf52840] fix an issue with platform_user_ram.ld generation when path contains 'data'
  modules/shared/nRF52840/build_linker_script.mk
Labels: bug, ready to merge

#2088 Removes locking in some of the SPI and I2C APIs to improve performance
  hal/src/nRF52840/i2c_hal.cpp
  hal/src/nRF52840/spi_hal.cpp
  hal/src/nRF52840/usart_hal.cpp
  hal/src/stm32f2xx/i2c_hal.c
  hal/src/stm32f2xx/spi_hal.c
  hal/src/stm32f2xx/usart_hal.c
  user/tests/wiring/no_fixture_spi/spi.cpp
  wiring/src/spark_wiring_spi.cpp
Labels: enhancement, ready to merge

#2085 Particle.process() is a no-op when called from a custom thread.
  system/src/system_cloud.cpp
  user/tests/wiring/no_fixture/thread.cpp
Labels: bug, ready to merge

#2087 [electron] Fix "Sim not inserted" debug log when modem is not responsive
  system/src/system_network_cellular.h
Labels: bug, ready to merge
