Repository particle-iot/device-os, pull requests merged in 2020-10, with the labels that each got.

#2207 Set pin mode for PMIC and fuel gauge interrupts
  system/src/system_power_manager.cpp
Labels: needs review

#2206 Disconnect from the cloud before going to sleep
  system/src/system_cloud_internal.cpp
  system/src/system_cloud_internal.h
  system/src/system_sleep.cpp
  system/src/system_sleep_compat.cpp
Labels: bug, ready to merge

#2204 HAL: add always_inline attribute for deprecated APIs
  hal/inc/adc_hal_compat.h
  hal/inc/i2c_hal_compat.h
  hal/inc/pwm_hal_compat.h
  hal/inc/rtc_hal_compat.h
  hal/inc/spi_hal_compat.h
  hal/inc/usart_hal_compat.h
Labels: enhancement, ready to merge

#2211 [gen3] Allow UMNOPROF SIM_SELECT to default back to SW_DEFAULT
  hal/network/ncp_client/sara/sara_ncp_client.cpp
  hal/src/electron/modem/mdm_hal.cpp
Labels: bug

#2209 [Wiring] Remove warning for publish scope deprecation
  wiring/inc/spark_wiring_cloud.h
Labels: enhancement, ready to merge

#2213 [u-blox] older modem firmware does not have UMNOPROF=100 available [ch64670]
  hal/network/ncp_client/sara/sara_ncp_client.cpp
  hal/network/ncp_client/sara/sara_ncp_client.h
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
Labels: bug, ready to merge

#2221 Fix CellularSignal deprecation messages
  wiring/inc/spark_wiring_cellular_printable.h
Labels: documentation

#2225 Export some common stdlib functions from system parts
  build/module-defaults.mk
  hal/inc/hal_platform.h
  hal/src/nRF52840/hal_platform_nrf52840_config.h
  modules/electron/user-part/src/import_services2.c
  rt-dynalib/inc/rt_dynalib.h
  rt-dynalib/makefile
  services/inc/services2_dynalib.h
  wiring/inc/spark_wiring_thread.h
Labels: enhancement, needs review

#2215 [Cellular] Fixes PMIC reducing current on warm boot and causing modem brownouts
  hal/inc/hal_platform.h
  system/src/system_power_manager.cpp
  system/src/system_power_manager.h
  user/tests/wiring/power_management/power.cpp
  wiring/inc/spark_wiring_power.h
  wiring/src/spark_wiring_power.cpp
Labels: bug, needs review

#2219 [gen2][electron] modem brownout or unexpected reset causes system to think it still is connected [ch64465]
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
  user/tests/wiring/no_fixture_long_running/cellular.cpp
Labels: enhancement, needs review

#2218 [Electron] Workaround for modem HAL relying on system networking code to re-attempt initialization
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
  system/src/system_network_cellular.h
  system/src/system_network_internal.h
Labels: bug, needs review

#2227 [hal] sleep: restore waleup sources' interrupt priority appropriately
  hal/src/nRF52840/sleep_hal.cpp
  hal/src/stm32f2xx/sleep_hal.cpp
Labels: bug, ready to merge

#2230 [system] network diagnostics for Gen 3 platforms
  system/src/system_network_diagnostics.cpp
  system/src/system_network_diagnostics.h
  system/src/system_network_internal.cpp
  system/src/system_network_internal.h
  system/src/system_network_manager.cpp
  system/src/system_network_manager.h
  system/src/system_network_manager_api.cpp
Labels: enhancement

#2229 [hal] electron: use AT+CPWROFF to turn off the modem completely
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
  services/inc/services2_dynalib.h
  user/tests/wiring/no_fixture_long_running/cellular.cpp
Labels: bug, ready to merge
