Repository particle-iot/device-os, pull requests merged in 2020-03, with the labels that each got.

#2042 Enable hwfc for Quectel modem during runtime and add support for EG91-EX
  hal/inc/deviceid_hal.h
  hal/network/ncp/cellular/cellular_hal.cpp
  hal/shared/cellular_enums_hal.h
  hal/shared/platform_ncp.cpp
  hal/shared/platform_ncp.h
  hal/src/b5som/network/quectel_ncp_client.cpp
  hal/src/b5som/platform_ncp_quectel.cpp
  hal/src/nRF52840/deviceid_hal.cpp
  user/tests/wiring/no_fixture/cellular.cpp
Labels: enhancement, ready to merge

#2039 Redo: Fixes the issue that SPI default SS pin is not configured
  hal/inc/pinmap_hal.h
  hal/src/nRF52840/spi_hal.cpp
  hal/src/stm32f2xx/spi_hal.c
  user/tests/wiring/no_fixture_spi/application.cpp
  user/tests/wiring/no_fixture_spi/spi.cpp
  user/tests/wiring/no_fixture_spi/test.mk
  wiring/inc/spark_wiring_spi.h
  wiring/src/spark_wiring_spi.cpp
Labels: bug, ready to merge

#2036 [stm32f2xx] platform: fix FLASH_Update() for unaligned writes
  platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/flash_mal.c
Labels: bug, ready to merge

#2033 Replace CSQ on Gen2 with UCGED (mode 5)
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
Labels: bug, ready to merge

#2038 Adding changes for R410M to use UCGED instead of CESQ
  hal/src/boron/network/sara_ncp_client.cpp
  user/tests/wiring/no_fixture/cellular.cpp
Labels: enhancement, ready to merge

#2051 Fix YModem transfer
  communication/inc/file_transfer.h
Labels: bug, needs review

#2052 [hal] concurrent: expose full concurrent APIs.
  hal/inc/hal_dynalib_concurrent.h
Labels: feature, ready to merge

#2053 [wiring] Thread: fixes memory leakage due to mutex not being destroyed.
  wiring/inc/spark_wiring_thread.h
Labels: bug, ready to merge

#2056 [system] close cloud socket on errors
  hal/inc/hal_platform.h
  hal/inc/hal_platform_compat.h
  system/src/system_cloud_internal.cpp
Labels: bug, ready to merge

#2057 [b5som] fixes a hardfault with Ethernet enabled
  hal/network/lwip/wiznet/wiznetif.cpp
  hal/src/b5som/hal_platform_config.h
  hal/src/boron/hal_platform_config.h
Labels: bug, ready to merge

#2058 [P1] Enable power save clock (32KHz) only if not disable by feature flag
  hal/src/photon/lib/FreeRTOS/WWD_for_SDIO_FreeRTOS.a
  user/tests/wiring/no_fixture_long_running/pwm.cpp
Labels: bug, ready to merge

#2059 [wiring] Wire.requestFrom() multiple conflicting candidates
  user/tests/wiring/api/wiring.cpp
  wiring/inc/spark_wiring_i2c.h
  wiring/src/spark_wiring_i2c.cpp
Labels: bug, needs review

#2060 [Gen 2] Fixes SPI.beginTransaction() deadlocking
  user/tests/wiring/no_fixture/spi.cpp
  wiring/inc/spark_wiring_spi.h
Labels: bug, needs review

#2049 Ensure NCP connection state is processed when changed by the muxer [ch48825]
  hal/src/argon/network/esp32_ncp_client.cpp
  hal/src/b5som/network/quectel_ncp_client.cpp
  hal/src/boron/network/sara_ncp_client.cpp
  user/tests/wiring/no_fixture_long_running/network.cpp
Labels: bug, needs review

#2062 [Boron/B SoM/B5 SoM] Fix Cellular Global Identity generation
  hal/src/b5som/network/quectel_ncp_client.cpp
  hal/src/b5som/network/quectel_ncp_client.h
  hal/src/boron/network/sara_ncp_client.cpp
  hal/src/boron/network/sara_ncp_client.h
Labels: bug, needs review

#2064 Remove support for unused control requests
  hal/inc/bootloader_hal.h
  hal/src/nRF52840/bootloader.cpp
  hal/src/nRF52840/hal_platform_nrf52840_config.h
  hal/src/stm32f2xx/bootloader.cpp
  system/inc/system_control.h
  system/src/control/config.cpp
  system/src/control/network.cpp
  system/src/control/network.h
  system/src/control/storage.cpp
  system/src/control/storage.h
  system/src/control/wifi.cpp
  system/src/control/wifi.h
  system/src/system_control_internal.cpp
Labels: internal, ready to merge
