Repository particle-iot/device-os, pull requests merged in 2020-06, with the labels that each got.

#2120 [Gen3] Hide wifi wiring API that are not supported
  user/tests/wiring/api/wifi.cpp
  user/tests/wiring/no_fixture/wifi.cpp
  wiring/inc/spark_wiring_wifi.h
Labels: enhancement, needs review

#2123 32/64-bit time_t compatibility and RTC HAL refactoring
  build/arm-tools.mk
  communication/inc/communication_dynalib.h
  communication/inc/spark_protocol_functions.h
  communication/src/spark_protocol_functions.cpp
  communication/src/timesyncmanager.h
  communication/tests/ConstructorFixture.cpp
  communication/tests/ConstructorFixture.h
  communication/tests/TestSparkProtocol.cpp
  hal/inc/exrtc_hal.h
  hal/inc/hal_dynalib.h
  hal/inc/hal_dynalib_socket_posix.h
  hal/inc/rtc_hal.h
  hal/network/lwip/socket_hal.cpp
  hal/network/lwip/socket_hal_posix_impl.h
  hal/shared/time_compat.cpp
  hal/shared/time_compat.h
  hal/src/electron/rtc_hal.c
  hal/src/gcc/core_hal.cpp
  hal/src/gcc/rtc_hal.cpp
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/exrtc_hal.cpp
  hal/src/nRF52840/posix/syscalls_posix.cpp
  hal/src/nRF52840/rtc_hal.cpp
  hal/src/nRF52840/sleep_hal.cpp
  hal/src/stm32f2xx/core_hal_stm32f2xx.c
  hal/src/stm32f2xx/rtc_hal.c
  hal/src/stm32f2xx/sleep_hal.cpp
  hal/src/template/rtc_hal.c
  hal/src/template/rtc_hal.cpp
  hal/src/tracker/am18x5.cpp
  hal/src/tracker/am18x5.h
  modules/electron/system-part1/src/time_compat.cpp
  modules/electron/system-part3/makefile
  services/inc/services2_dynalib.h
  system/inc/system_cloud.h
  system/inc/system_dynalib_cloud.h
  system/src/system_cloud.cpp
  system/src/system_cloud_internal.cpp
  system/src/system_cloud_internal.h
  system/src/system_sleep_compat.cpp
  user/tests/unit/makefile
  user/tests/wiring/no_fixture/time.cpp
  user/tests/wiring/time_compat/application.cpp
  user/tests/wiring/time_compat/import_services2.c
  user/tests/wiring/time_compat/test.mk
  user/tests/wiring/time_compat/time_compat.cpp
  wiring/inc/spark_wiring_cloud.h
  wiring/src/spark_wiring_time.cpp
Labels: needs review

#2122 [Gen2] Fix sprintf compile err on gcc9
  hal/src/electron/modem/mdm_hal.cpp
  user/tests/app/band_select/band_select.cpp
Labels: internal, ready to merge

#2119 Process 'CEREG: 0' URCs on R410M
  hal/src/electron/modem/mdm_hal.cpp
Labels: bug, needs review

#2131 Fix firmware updates via control requests
  system/src/control/storage.cpp
Labels: bug

#2137 [build] Fixes monolithic build on photon
  hal/src/photon/include.mk
Labels: bug, ready to merge

#2138 Add SPISettings while keeping __SPISettings as an alias for wiring layer
  wiring/inc/spark_wiring_spi.h
Labels: enhancement, needs review

#2139 [ublox] Do not run AT+COPS=0 when performing warm bootup if already registering/registered
  hal/network/ncp_client/quectel/quectel_ncp_client.cpp
  hal/network/ncp_client/sara/sara_ncp_client.cpp
Labels: enhancement, ready to merge

#2142 Allow resetting the device via a low-level vendor-specific USB request
  system/src/usb_control_request_channel.cpp
Labels: enhancement, ready to merge
