Repository particle-iot/device-os, pull requests merged in 2020-11, with the labels that each got.

#2228 [wiring] system: configure multiple pins as wakeup source at a time.
  system/inc/system_sleep_configuration.h
Labels: feature, needs review

#2231 [wiring] system: minor fix for sleep configuration method
  system/inc/system_sleep_configuration.h
  user/tests/wiring/api/system.cpp
Labels: bug, ready to merge

#2212 [Cellular/Wiring] Remove rssi and qual from Cellular.RSSI()
  hal/inc/cellular_hal.h
  hal/inc/cellular_hal_constants.h
  hal/inc/hal_dynalib_cellular.h
  hal/network/ncp/cellular/cellular_hal.cpp
  hal/shared/cellular_enums_hal.h
  hal/src/electron/cellular_hal.cpp
  hal/src/electron/cellular_internal.cpp
  hal/src/electron/cellular_internal.h
  hal/src/electron/modem/mdm_hal.cpp
  test/unit_tests/cellular/cellular.cpp
  user/tests/wiring/no_fixture/cellular.cpp
  wiring/inc/spark_wiring_cellular.h
  wiring/inc/spark_wiring_cellular_printable.h
  wiring/src/spark_wiring_cellular.cpp
  wiring/src/spark_wiring_cellular_printable.cpp
Labels: enhancement, needs review

#2226 System.on() can accept a std::function instance as callback
  system/inc/system_dynalib.h
  system/inc/system_event.h
  system/src/system_event.cpp
  user/tests/wiring/api/system.cpp
  wiring/inc/spark_wiring_system.h
Labels: enhancement, ready to merge

#2216 [wiring] add more operators for BleAddress/BleUuid/IPAddress.
  user/tests/wiring/api/ble.cpp
  wiring/inc/spark_wiring_ble.h
  wiring/inc/spark_wiring_ipaddress.h
  wiring/src/spark_wiring_ble.cpp
  wiring/src/spark_wiring_ipaddress.cpp
Labels: feature, ready to merge

#2200 Tracker: an easy way to configure Wi-Fi/GNSS/FuelGauge as a wakeup source
  hal/src/nRF52840/sleep_hal.cpp
  hal/src/tracker/mcp23s17.cpp
  hal/src/tracker/mcp23s17.h
  system/inc/system_power.h
  system/inc/system_sleep_configuration.h
  system/src/system_power.cpp
  system/src/system_power_manager.cpp
  system/src/system_power_manager.h
  system/src/system_sleep.cpp
  system/src/system_sleep_compat.cpp
  user/tests/app/tracker_wakeup/esp32_soch.h
  user/tests/app/tracker_wakeup/port.cpp
  user/tests/app/tracker_wakeup/port.h
  user/tests/app/tracker_wakeup/sdspi_host.cpp
  user/tests/app/tracker_wakeup/sdspi_host.h
  user/tests/app/tracker_wakeup/tracker_wakeup.cpp
  user/tests/wiring/sleep20/sleep20.cpp
Labels: feature, ready to merge

#2220 Fixes the issue that BLE.scan() might hang the device.
  hal/src/nRF52840/ble_hal.cpp
  hal/src/nRF52840/ble_hal_impl.h
  user/tests/wiring/ble_scanner_broadcaster/ble_scanner/scanner.cpp
Labels: bug, needs review

#2232 Query cellular signal while module tries to register
  hal/network/ncp_client/quectel/quectel_ncp_client.cpp
  hal/network/ncp_client/sara/sara_ncp_client.cpp
  hal/src/electron/modem/mdm_hal.cpp
Labels: enhancement

#2222 Wiring BLE APIs consistency improvements
  user/tests/app/ble/scanner/application.cpp
  user/tests/app/ble/uart_central/application.cpp
  user/tests/wiring/api/ble.cpp
  user/tests/wiring/ble_central_peripheral/ble_central/central.cpp
  user/tests/wiring/ble_scanner_broadcaster/ble_scanner/scanner.cpp
  user/tests/wiring/no_fixture_ble/ble.cpp
  wiring/inc/spark_wiring_ble.h
  wiring/src/spark_wiring_ble.cpp
Labels: enhancement, needs review

#2223 [wiring] BLE: implement BLE scanning filter.
  user/tests/wiring/api/ble.cpp
  user/tests/wiring/ble_central_peripheral/ble_peripheral/peripheral.cpp
  user/tests/wiring/ble_scanner_broadcaster/ble_broadcaster/application.cpp
  user/tests/wiring/ble_scanner_broadcaster/ble_broadcaster/broadcaster.cpp
  user/tests/wiring/ble_scanner_broadcaster/ble_scanner/scanner.cpp
  wiring/inc/spark_wiring_ble.h
  wiring/src/spark_wiring_ble.cpp
Labels: ble, feature, needs review

#2224 BLE: Scanned/Connected/Disconnected/Data Received callback in C++ style
  user/tests/wiring/api/ble.cpp
  user/tests/wiring/no_fixture_ble/ble.cpp
  wiring/inc/spark_wiring_ble.h
  wiring/src/spark_wiring_ble.cpp
Labels: ble, feature, needs review

#2203 Add characteristic discovery to BleService
  user/tests/wiring/api/ble.cpp
  user/tests/wiring/ble_central_peripheral/ble_central/central.cpp
  user/tests/wiring/ble_central_peripheral/ble_peripheral/peripheral.cpp
  wiring/inc/spark_wiring_ble.h
  wiring/src/spark_wiring_ble.cpp
Labels: ble, enhancement, needs review

#2238 Gen2: platforms calling sleep20 API to enter stop/ulp mode may block user application.
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
  system/src/system_sleep.cpp
  system/src/system_sleep_compat.cpp
  user/tests/wiring/sleep20/sleep20.cpp
Labels: bug, needs review

#2239 [electron] modem: fix C*REG URC parsing
  hal/src/electron/modem/mdm_hal.cpp
Labels: bug
