Repository particle-iot/device-os, pull requests merged in 2021-04, with the labels that each got.

#2288 Enable LTO for Photon system firmware
  .buildpackrc
  .workbench/manifest.json
  bootloader/src/nRF52840/nrf_it.c
  build/arm-tools.mk
  build/common-tools.mk
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/posix/syscalls_posix.cpp
  hal/src/nRF52840/spi_hal.cpp
  hal/src/stm32f2xx/core_hal_stm32f2xx.c
  modules/photon/system-part1/makefile
  modules/photon/system-part2/makefile
  newlib_nano/src/mallocr.c
  platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/hw_config.c
  scripts/fetch-buildpack
Labels: enhancement

#2293 Particle.unsubscribe() doesn't preserve system subscriptions
  system/src/system_cloud.cpp
  system/src/system_cloud_internal.cpp
  system/src/system_cloud_internal.h
Labels: bug

#2297 Querying the value of an empty string variable causes an error
  system/src/system_cloud_internal.cpp
  user/tests/integration/communication/variables/variables.cpp
  user/tests/integration/communication/variables/variables.spec.js
Labels: bug

#2249 Support for DTLS connection IDs
  communication/inc/dtls_session_persist.h
  communication/src/dtls_message_channel.cpp
  crypto/inc/mbedtls_config_default.h
  hal/src/nRF52840/mbedtls/mbedtls_config_platform.h
Labels: enhancement

#2280 Allow clearing session data and running custom setup code in integration tests
  system/inc/system_cloud.h
  system/inc/system_threading.h
  system/src/active_object.cpp
  system/src/main.cpp
  system/src/system_cloud.cpp
  system/src/system_cloud_connection.cpp
  system/src/system_cloud_internal.cpp
  system/src/system_cloud_internal.h
  system/src/system_event.cpp
  system/src/system_task.cpp
  system/src/system_threading.cpp
  test/unit_tests/cloud/publish_vitals.cpp
  user/tests/integration/application/include/test.h
  user/tests/integration/application/src/application.cpp
  user/tests/integration/application/src/test_suite.cpp
  user/tests/unit/usb_control_request_channel.cpp
  wiring/inc/spark_wiring_cloud.h
  wiring/src/spark_wiring_cloud.cpp
Labels: enhancement

#2306 Fixes the issue that the Particle.disconnect() doesn't clear the auto…
  system/src/system_cloud.cpp
Labels: bug, needs review

#2307 Gen2: fixes the issue that the cellular modem is reset unexpectedly.
  system/src/system_network_cellular.h
Labels: bug, ready to merge

#2308 Restores the modem state after device is woken up.
  system/src/system_network_manager_api.cpp
  system/src/system_sleep.cpp
  user/tests/wiring/sleep20/sleep20.cpp
Labels: bug, needs review

#2309 Gen2: network connection is established unexpectedly.
  system/inc/system_task.h
  system/src/system_network_compat.cpp
  system/src/system_network_internal.h
  system/src/system_network_manager_api.cpp
  system/src/system_sleep.cpp
  system/src/system_sleep_compat.cpp
Labels: bug, needs review
