Repository particle-iot/device-os, pull requests merged in 2021-01, with the labels that each got.

#2265 Send modem firmware version to cloud
  hal/inc/cellular_hal_constants.h
  hal/network/ncp/cellular/cellular_hal.cpp
  hal/network/ncp_client/sara/sara_ncp_client.cpp
  hal/src/b5som/ota_flash_hal.cpp
  hal/src/boron/ota_flash_hal.cpp
  hal/src/electron/cellular_hal.cpp
  hal/src/electron/modem/mdm_hal.h
  hal/src/electron/ota_flash_hal.cpp
  hal/src/tracker/ota_flash_hal.cpp
  system/src/system_setup.cpp
Labels: ready to merge

#2266 [wiring] BLE: return false if expected characteristic is not found.
  wiring/src/spark_wiring_ble.cpp
Labels: ble, bug, ready to merge

#2264 [Gen 3] Fixes UART RX DMA transfer size issues
  hal/src/nRF52840/usart_hal.cpp
  test/unit_tests/CMakeLists.txt
Labels: bug

#2268 [gen2] speed up cellular modem powerOn time
  hal/src/electron/modem/mdm_hal.cpp
  hal/src/electron/modem/mdm_hal.h
Labels: enhancement, ready to merge

#2269 [Gen 3] Fix warm boot; [Tracker] Cache ESP32 firmware version
  hal/network/lwip/cellular/pppncpnetif.cpp
  hal/network/lwip/esp32/esp32ncpnetif.cpp
  hal/network/ncp/wifi/platform_ncp_update.cpp
  hal/network/ncp_client/esp32/esp32_ncp_client.cpp
  services/inc/system_cache.h
  services/src/system_cache.cpp
  system/src/control/cellular.cpp
  system/src/control/config.cpp
  system/src/control/wifi_new.cpp
Labels: bug, enhancement, needs review

#2270 Disconnect from the server on OTA update errors
  communication/inc/protocol_defs.h
  communication/src/firmware_update.cpp
  communication/src/firmware_update.h
  communication/src/protocol_defs.cpp
  services/inc/system_error.h
  system/src/system_update.cpp
  test/unit_tests/communication/firmware_update.cpp
Labels: bug
