Repository particle-iot/device-os, pull requests merged in 2021-11, with the labels that each got.

#2372 fix the issue that BLE setup fails on Wi-Fi platform.
  hal/network/lwip/esp32/esp32ncpnetif.cpp
  system/src/control/wifi_new.cpp
Labels: bug, needs review

#2331 Add ability to set and scan extended advertisement size (when using Coded PHY)
  hal/src/nRF52840/ble_hal.cpp
  hal/src/nRF52840/ble_hal_impl.h
  user/tests/wiring/ble_scanner_broadcaster/ble_broadcaster/broadcaster.cpp
  user/tests/wiring/ble_scanner_broadcaster/ble_scanner/scanner.cpp
  wiring/inc/spark_wiring_ble.h
  wiring/src/spark_wiring_ble.cpp
Labels: feature, ble

#2376 Fixes copy-constructor woes in Wiring BLE API; Migrate BLE tests to be runnable under device-os-test-runner
  services/inc/enumflags.h
  user/tests/integration/wiring/ble_central_peripheral
  user/tests/integration/wiring/ble_scanner_broadcaster
  user/tests/integration/wiring/no_fixture_wifi
  user/tests/unit/json.cpp
  user/tests/wiring/ble_central_peripheral/ble_central/application.cpp
  user/tests/wiring/ble_central_peripheral/ble_central/central.cpp
  user/tests/wiring/ble_central_peripheral/ble_central/util.h
  user/tests/wiring/ble_central_peripheral/ble_central_peripheral.config.js
  user/tests/wiring/ble_central_peripheral/ble_central_peripheral.spec.js
  user/tests/wiring/ble_central_peripheral/ble_peripheral/application.cpp
  user/tests/wiring/ble_central_peripheral/ble_peripheral/peripheral.cpp
  user/tests/wiring/ble_central_peripheral/ble_peripheral/util.h
  user/tests/wiring/ble_common/util.h
  user/tests/wiring/ble_scanner_broadcaster/ble_broadcaster/application.cpp
  user/tests/wiring/ble_scanner_broadcaster/ble_broadcaster/broadcaster.cpp
  user/tests/wiring/ble_scanner_broadcaster/ble_broadcaster/util.h
  user/tests/wiring/ble_scanner_broadcaster/ble_scanner/application.cpp
  user/tests/wiring/ble_scanner_broadcaster/ble_scanner/scanner.cpp
  user/tests/wiring/ble_scanner_broadcaster/ble_scanner/util.h
  user/tests/wiring/ble_scanner_broadcaster/ble_scanner_broadcaster.config.js
  user/tests/wiring/ble_scanner_broadcaster/ble_scanner_broadcaster.spec.js
  user/tests/wiring/no_fixture/cloud.cpp
  user/tests/wiring/no_fixture/thread.cpp
  user/tests/wiring/no_fixture_wifi/application.cpp
  user/tests/wiring/no_fixture_wifi/no_fixture_wifi.spec.js
  user/tests/wiring/no_fixture_wifi/test.mk
  user/tests/wiring/no_fixture_wifi/wifi.cpp
  wiring/inc/spark_wiring_ble.h
  wiring/src/spark_wiring_ble.cpp
Labels: bug, enhancement, internal
