Repository particle-iot/device-os, pull requests merged in 2021-02, with the labels that each got.

#2276 Add new Kore SIMs to static APN map
  hal/network/ncp/cellular/network_config_db.cpp
  hal/src/electron/cellular_hal_utilities.cpp
  test/unit_tests/cellular/cellular.cpp
  test/unit_tests/services/simple_file_storage.cpp
Labels: in progress

#2275 Fix default assignment for SPI chip select
  hal/network/lwip/wiznet/wiznetif.cpp
  hal/shared/spi_lock.h
Labels: bug

#2279 Make sure that ESP32 NCP power state is correctly initialized on boot
  hal/network/ncp_client/esp32/esp32_ncp_client.cpp
Labels: needs review

#2273 [gen3] disable some of the elliptic-curves not in use to save flash space
  hal/src/nRF52840/mbedtls/ecp_curves_enable.c
Labels: enhancement

#2281 [u-blox][gen2] COPS_TIMEOUT increased to 5 minutes
  hal/src/electron/modem/mdm_hal.cpp
Labels: bug

#2285 Modify mapping for LTE signal values to percentages
  hal/shared/cellular_sig_perc_mapping.cpp
  test/unit_tests/cellular/cellular.cpp
Labels: ready to merge

#2272 System power management inprovements
  system/src/system_power_manager.cpp
  system/src/system_power_manager.h
  wiring/inc/spark_wiring_power.h
  wiring/inc/spark_wiring_system_power.h
  wiring/src/spark_wiring_power.cpp
Labels: enhancement

#2284 [gen2, threading] Fixes Cellular taking up to 10 minutes to shutoff modem with Cellular.off() / System.sleep(config) if there is no cell connection [ch73242]
  system/src/system_network_cellular.h
  system/src/system_sleep.cpp
  user/tests/wiring/cell_connect_after_off/application.cpp
  user/tests/wiring/cell_connect_after_off/cellular_conn_after_off.cpp
  user/tests/wiring/cell_connect_after_off/readme.md
  user/tests/wiring/cellular_no_antenna/application.cpp
  user/tests/wiring/cellular_no_antenna/cellular_no_antenna.cpp
  user/tests/wiring/cellular_no_antenna/test.mk
  user/tests/wiring/sleep20/sleep20.cpp
Labels: bug

#2277 Ch72460/more startup slos
  user/tests/integration/startup-slos/README.md
  user/tests/integration/startup-slos/startup-slos.cpp
  user/tests/integration/startup-slos/startup-slos.spec.js
Labels: ready to merge
