Repository particle-iot/device-os, pull requests merged in 2022-10, with the labels that each got.

#2553 Backports of 5.1.0 and other issues into 4.x
  .circleci/config.yml
  bootloader/src/nRF52840/usbd_device.cpp
  bootloader/src/nRF52840/usbd_dfu_mal.cpp
  bootloader/src/nRF52840/usbd_dfu_mal.h
  ci/test-build-tasks.ps1
  ci/test-build-tasks.sh
  hal/inc/storage_hal.h
  hal/inc/wlan_hal.h
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/dct_hal.cpp
  hal/src/nRF52840/storage_hal.cpp
  hal/src/tracker/platform_ncp_quectel.cpp
  platform/MCU/nRF52840/inc/dcd_flash_impl.h
  platform/MCU/nRF52840/inc/flash_storage_impl.h
  services/inc/dcd.h
  services/inc/dct_file.h
  system/src/ble_control_request_channel.cpp
  system/src/system_cloud_internal.cpp
  test/unit_tests/services/CMakeLists.txt
  test/unit_tests/services/dcd.cpp
  user/tests/wiring/no_fixture/thread.cpp
  wiring/inc/spark_wiring_thread.h
  wiring/inc/spark_wiring_watchdog.h
  wiring_globals/src/spark_wiring_watchdog.cpp
Labels: bootloader

#2562 [p2] WiFi bugfixes
  hal/network/ncp_client/realtek/rtl_ncp_client.cpp
Labels: bug, 5.x, 5.x-only

#2564 [CI] fixes
  build/release-publish.sh
  ci/cf_generate_message.sh
Labels: internal, 4.x, 5.x

#2567 [TrackerM] Prevent connection over wifi when configured in SCAN_ONLY mode
  system/src/system_network_manager.cpp
Labels: bug, 5.x-only
