Repository particle-iot/device-os, pull requests merged in 2022-08, with the labels that each got.

#2503 [p2][gen3] fixes for attachInterrupt() / noInterrupts() / interrupts() APIs
  hal/src/nRF52840/interrupts_hal.cpp
  hal/src/rtl872x/interrupts_hal.cpp
  user/tests/app/interrupts/interrupts.cpp
Labels: bug

#2504 [4.x] [gen3] fixes interrupts() API, should not clear pending interrupts
  hal/src/nRF52840/interrupts_hal.cpp
  user/tests/app/interrupts/interrupts.cpp
Labels: bug

#2505 [esomx] Remove undefined pins from esomx pinmap
  hal/src/boron/network/network.cpp
  hal/src/boron/pinmap_defines.h
  hal/src/boron/pinmap_hal.c
  platform/MCU/nRF52840/inc/platform_config.h
  user/applications/product_id_and_version/application.cpp
  user/applications/tinker/application.cpp
  user/inc/Arduino.h
Labels: breaking change

#2506 [esomx] Remove undefined pins from esomx pinmap
  hal/src/boron/network/network.cpp
  hal/src/boron/pinmap_defines.h
  hal/src/boron/pinmap_hal.c
  platform/MCU/nRF52840/inc/platform_config.h
  user/applications/product_id_and_version/application.cpp
  user/applications/tinker/application.cpp
  user/inc/Arduino.h
Labels: breaking change

#2493 RTL872x: Implement HAL event group for UART
  hal/src/rtl872x/usart_hal.cpp
Labels: in progress, feature, DO NOT MERGE

#2507 [p2] attachInterrupt() should not configure input pullup/pulldown/nopull
  hal/src/rtl872x/interrupts_hal.cpp
  user/tests/app/input_pinmode/input_pinmode.cpp
  user/tests/wiring/no_fixture/interrupts.cpp
Labels: bug

#2509 [ci] branch pattern changes for test-build-system
  .circleci/config.yml
Labels: internal

#2510 [ci][4x] branch pattern changes for test-build-system
  .circleci/config.yml
Labels: internal

#2511 P2 PWM fixture tests. PWM HAL fixes
  hal/src/rtl872x/pinmap_hal.cpp
  hal/src/rtl872x/pwm_hal.cpp
  user/tests/wiring/no_fixture_long_running/pwm.cpp
  user/tests/wiring/pwm/application.cpp
  user/tests/wiring/pwm/pwm.cpp
  user/tests/wiring/pwm/test.mk
Labels: enhancement, internal

#2508 RTL872x: Implement APIs to set/get BLE address
  hal/inc/deviceid_hal.h
  hal/src/gcc/deviceid_hal_impl.h
  hal/src/nRF52840/deviceid_hal_impl.h
  hal/src/newhal/deviceid_hal_impl.h
  hal/src/rtl872x/ble_hal.cpp
  hal/src/rtl872x/deviceid_hal.cpp
  hal/src/rtl872x/deviceid_hal_impl.h
  hal/src/trackerm/network/network.cpp
  hal/src/tron/network/network.cpp
Labels: feature

#2513 [test] fixes race condition with wiring/no_fixture TIME_17
  user/tests/wiring/no_fixture/time.cpp
Labels: internal

#2514 [test][4x] fixes race condition with wiring/no_fixture TIME_17
  user/tests/wiring/no_fixture/time.cpp
Labels: internal

#2516 [tests] integration: bump binary-version-reader and device-constants dependency for P2-related module manipulationfixes
  user/tests/integration/package-lock.json
  user/tests/integration/package.json
Labels: internal

#2519 Ensure task yield and system thread pump in system_delay_pump
  system/src/system_task.cpp
  user/tests/wiring/no_fixture/time.cpp
Labels: bug

#2521 [tests] restores accuracy of system_delay_pump for DELAY_01 test
  system/src/system_task.cpp
Labels: internal

#2522 [rtl872x] adds Tracker M in release.sh for prebootloader build
  build/release.sh
  ci/enumerate_build_matrix.sh
Labels: internal

#2524 [tests][4x] restores accuracy of system_delay_pump for DELAY_01 test
  system/src/system_task.cpp
Labels: internal

#2526 [wiring] System.hardwareInfo()
  hal/inc/deviceid_hal.h
  hal/inc/hal_dynalib_core.h
  hal/shared/platform_ncp.h
  hal/src/b5som/platform_ncp_quectel.cpp
  hal/src/boron/platform_ncp_boron.cpp
  hal/src/gcc/deviceid_hal.cpp
  hal/src/nRF52840/deviceid_hal.cpp
  hal/src/rtl872x/deviceid_hal.cpp
  hal/src/rtl872x/deviceid_hal_impl.h
  hal/src/template/deviceid_hal.cpp
  hal/src/tracker/hal_platform_config.h
  hal/src/tracker/platform_ncp_quectel.cpp
  hal/src/trackerm/hal_platform_config.h
  hal/src/trackerm/platform_ncp_quectel.cpp
  hal/src/tron/platform_ncp.cpp
  user/tests/wiring/api/system.cpp
  user/tests/wiring/no_fixture/system.cpp
  wiring/inc/spark_wiring_system.h
Labels: 4.x, 5.x

#2529 [wiring] System.hardwareInfo()
  hal/inc/deviceid_hal.h
  hal/inc/hal_dynalib_core.h
  hal/shared/platform_ncp.h
  hal/src/b5som/platform_ncp_quectel.cpp
  hal/src/boron/platform_ncp_boron.cpp
  hal/src/gcc/deviceid_hal.cpp
  hal/src/gcc/deviceid_hal_impl.h
  hal/src/nRF52840/deviceid_hal.cpp
  hal/src/nRF52840/deviceid_hal_impl.h
  hal/src/newhal/deviceid_hal_impl.h
  hal/src/template/deviceid_hal.cpp
  hal/src/tracker/hal_platform_config.h
  hal/src/tracker/platform_ncp_quectel.cpp
  system/inc/system_version.h
  user/tests/wiring/api/system.cpp
  user/tests/wiring/no_fixture/system.cpp
  wiring/inc/spark_wiring_system.h
Labels: backport, 4.x
