Repository particle-iot/device-os, pull requests merged in 2022-07, with the labels that each got.

#2463 [tests] Change PWM pins to better match e-series pinout for E SoM X. Fix other tests
  build/create_module.py
  hal/src/boron/hal_platform_config.h
  hal/src/boron/pinmap_hal.c
  system/src/ble_provisioning_mode_handler.cpp
  user/tests/wiring/no_fixture/fastpin.cpp
  user/tests/wiring/no_fixture/gpio.cpp
  user/tests/wiring/no_fixture/i2c.cpp
  user/tests/wiring/no_fixture/led.cpp
  user/tests/wiring/no_fixture_long_running/pwm.cpp
  user/tests/wiring/no_fixture_long_running/servo.cpp
  user/tests/wiring/no_fixture_long_running/tone.cpp
Labels: internal

#2404 Register without waiting for CSD connections [sc-96611]
  hal/network/ncp_client/quectel/quectel_ncp_client.cpp
  hal/network/ncp_client/sara/sara_ncp_client.cpp
Labels: enhancement

#2471 feature/sc-106677/stop-ignoring-device-os-scripts-directory
  .bundleignore
  .circleci/config.yml
  ci/test-build-tasks.ps1
  ci/test-build-tasks.sh
Labels: internal

#2472 [linker] make sure that FreeRTOS task/timer symbols are coalesced in bss section, disable LTO for FreeRTOS sources as well
  build/arm-tools.mk
  build/arm/linker/linker_freertos_task_symbols.ld
  modules/shared/nRF52840/linker_system_part1_common.ld
  modules/shared/rtl872x/linker_system_part1_common.ld
  third_party/freertos/build.mk
  third_party/freertos/makefile
Labels: bug

#2477 [rtl872x] usart: flush DMA FIFO data when required
  hal/inc/hal_platform.h
  hal/inc/usart_hal.h
  hal/src/rtl872x/usart_hal.cpp
  third_party/freertos/include.mk
Labels: bug

#2474 [p2][wifi] Add more complete WiFi network configuration information for P2
  hal/network/ncp_client/realtek/rtl_ncp_client.cpp
Labels: enhancement, ready to merge

#2482 [p2][photon2] Add VBAT_MEAS pin and charging indication pin for Photon2
  hal/src/rtl872x/gpio_hal.cpp
  hal/src/tron/pinmap_defines.cpp
  hal/src/tron/pinmap_defines.h
Labels: ready to merge

#2476 [rtl872x] DCache alignment requirement
  bootloader/prebootloader/src/tron/part1/sleep_handler.cpp
  bootloader/prebootloader/src/tron/part1/update_handler.c
  hal/src/rtl872x/km0_km4_ipc.cpp
  hal/src/rtl872x/km0_km4_ipc.h
  hal/src/rtl872x/sleep_hal.cpp
  hal/src/rtl872x/spi_hal.cpp
  hal/src/rtl872x/usart_hal.cpp
  platform/MCU/rtl872x/inc/platform_flash_modules.h
  platform/MCU/rtl872x/src/flash_mal.c
  services/inc/align_util.h
Labels: bug

#2494 [tests] [esomx] disable RGB pwm channel(s) when running pwm tests
  hal/src/boron/pinmap_hal.c
  user/tests/wiring/no_fixture/gpio.cpp
  user/tests/wiring/no_fixture_long_running/pwm.cpp
Labels: internal

#2495 [esomx] map ADC channels to the correct pins
  hal/src/boron/pinmap_hal.c
Labels: bug

#2496 chore/sc-107395/v4.x-bundleignore
  .bundleignore
Labels: internal
