Repository particle-iot/device-os, pull requests merged in 2022-03, with the labels that each got.

#2401 [gen3] adds SystemPowerConfiguration::socBitPrecision(uint8_t bits)) API [sc-94643]
  hal/inc/power_hal.h
  system/inc/system_power.h
  system/src/system_power_manager.cpp
  test/unit_tests/wiring/fuel_gauge.cpp
  user/tests/wiring/api/system.cpp
  user/tests/wiring/power_management/power.cpp
  user/tests/wiring/power_management_long_running/power.cpp
  wiring/inc/spark_wiring_fuel.h
  wiring/inc/spark_wiring_system_power.h
  wiring/src/spark_wiring_fuel.cpp
Labels: enhancement

#2406 Improves reliability of a few wiring/no_fixture tests
  user/tests/wiring/no_fixture/system.cpp
  user/tests/wiring/no_fixture/time.cpp
Labels: internal

#2408 [app] BLE provisioning mode for manual testing
  user/tests/app/ble/prov_mode/application.cpp
Labels: internal

#2409 [ci] fixes gcovr report generation
  ci/install_gcovr.sh
Labels: internal

#2411 [gen3] Dummy setup code should not return error
  hal/src/nRF52840/device_code.cpp
Labels: bug

#2412 [test] fixes integration slo/connect_time
  user/tests/integration/slo/connect_time/connect_time.cpp
  user/tests/integration/slo/connect_time/connect_time.spec.js
Labels: internal

#2416 [test] fix listening network tests
  user/tests/wiring/no_fixture/ble_provisioning.cpp
  user/tests/wiring/no_fixture/network.cpp
Labels: internal

#2417 [test] communication/functions communication/variables fixes for large describes
  user/tests/integration/communication/functions/functions.spec.js
  user/tests/integration/communication/variables/variables.spec.js
Labels: internal
