Repository particle-iot/device-os, pull requests merged in 2022-12, with the labels that each got.

#2592 Use compatible pins for PWM tests on TrackerM
  hal/src/trackerm/pinmap_defines.cpp
  user/tests/wiring/no_fixture_long_running/pwm.cpp
  user/tests/wiring/no_fixture_long_running/servo.cpp
  user/tests/wiring/no_fixture_long_running/tone.cpp
Labels: internal, 5.x-only

#2596 [rtl872x] Fixes a deadlock when requiring to enable RSIP
  hal/src/rtl872x/core_hal.c
  hal/src/rtl872x/exflash_hal.cpp
  platform/MCU/rtl872x/src/flash_mal.c
  user/tests/wiring/no_fixture/thread.cpp
Labels: bug, 5.x-only

#2600 [rtl872x] fixes System.ticks()
  hal/inc/hal_platform.h
  hal/src/nRF52840/hal_platform_nrf52840_config.h
  platform/MCU/newhal-mcu/inc/hw_ticks.h
  platform/MCU/rtl872x/inc/hw_ticks.h
  platform/MCU/rtl872x/src/hw_ticks.c
  user/tests/wiring/no_fixture/system.cpp
  user/tests/wiring/no_fixture_spi/spix.cpp
  wiring/inc/spark_wiring_system.h
Labels: bug, 5.x-only

#2602 [TrackerM] Collect cellular properties with system info
  hal/src/trackerm/ota_flash_hal.cpp
Labels: internal, 5.x-only

#2604 [rtl872x] Support IO wakeup sources through IO expander.
  bootloader/prebootloader/src/rtl872x/part1/sleep_handler.cpp
  hal/src/rtl872x/interrupts_hal.cpp
  hal/src/rtl872x/sleep_hal.cpp
Labels: feature, 5.x-only

#2606 fix overflow error in HAL_Delay_Microseconds
  hal/src/rtl872x/delay_hal.cpp
Labels: bug, 5.x-only

#2607 [bootloader] remove nanopb dependency
  bootloader/makefile
Labels: bug
