Repository particle-iot/device-os, pull requests merged in 2022-04, with the labels that each got.

#2420 [gen3] suppress certain reviewed GCC warnings [sc-100940]
  bootloader/src/nRF52840/usbd_dfu_mal.cpp
  platform/MCU/nRF52840/src/flash_mal.c
Labels: internal

#2419 Return relevant error from control request to enter listening mode
  system/inc/system_network.h
  system/src/system_control_internal.cpp
  system/src/system_network_compat.cpp
  system/src/system_network_manager_api.cpp
  test/unit_tests/stub/system_network.cpp
Labels: bug

#2431 Update dependencies for ARM GCC 10.2.1
  docs/dependencies.md
Labels: documentation

#2434 chore/ci-less-frequent-cross-platform-build-checks
  .circleci/config.yml
Labels: internal

#2446 [deprecation] PRODUCT_ID macro
  docs/build.md
  hal/inc/deviceid_hal.h
  user/applications/product_id_and_version/application.cpp
  user/applications/tinker/application.cpp
  user/tests/app/immediate_updates/immediate_updates.cpp
  wiring/inc/spark_wiring_version.h
Labels: breaking change, deprecation

#2445 [deprecation] Adds warning to some deprecated API's that will be removed in Device OS 5.x
  communication/src/spark_protocol_functions.cpp
  hal/inc/adc_hal_compat.h
  hal/inc/hal_platform.h
  hal/inc/i2c_hal_compat.h
  hal/inc/pwm_hal_compat.h
  hal/inc/rtc_hal_compat.h
  hal/inc/spi_hal_compat.h
  hal/inc/usart_hal_compat.h
  hal/src/nRF52840/bootloader.cpp
  hal/src/nRF52840/mesh_hal_deprecated.cpp
  system/src/control/config.cpp
  system/src/control/storage.cpp
  user/tests/wiring/api/adc.cpp
  user/tests/wiring/api/ble.cpp
  user/tests/wiring/api/i2c.cpp
  user/tests/wiring/api/pwm.cpp
  user/tests/wiring/api/rtc.cpp
  user/tests/wiring/api/spi.cpp
  user/tests/wiring/api/system.cpp
  user/tests/wiring/api/usart.cpp
  wiring/inc/spark_wiring_system.h
Labels: deprecation

#2447 [deprecation] remove setup_done flag and add deprecation notice
  hal/inc/hal_platform.h
  hal/src/nRF52840/hal_platform_nrf52840_config.h
  platform/MCU/nRF52840/inc/dct.h
  system/src/control/config.cpp
  system/src/system_network_manager_api.cpp
Labels: deprecation
