Repository particle-iot/device-os, pull requests merged in 2022-05, with the labels that each got.

#2449 [ci] minor update sc-101315/device-os-manifest
  .workbench/manifest.json
Labels: internal

#2441 Use a custom content type with CID packets when resuming the session
  communication/src/dtls_message_channel.cpp
Labels: enhancement

#2448 [gen3] fixes hardfault during low level USB peripheral initialization under an atomic section
  hal/src/nRF52840/usb_hal.cpp
Labels: bug
