Repository particle-iot/device-os, pull requests merged in 2022-11, with the labels that each got.

#2569 [rtl872x] prebootloader: enable BOR with lowest available thresholds
  bootloader/prebootloader/src/rtl872x/part1/rtl_support.c
Labels: bug, enhancement, bootloader, 5.x-only

#2573 [Cellular] R410 initialization SIM failure workaround
  hal/network/ncp/cellular/cellular_ncp_client.h
  hal/network/ncp_client/sara/sara_ncp_client.cpp
  hal/network/ncp_client/sara/sara_ncp_client.h
Labels: bug, backport

#2561 P2: Fixes the conflict between Flash API and XIP
  dynalib/inc/dynalib.h
  hal/src/rtl872x/core_hal.c
  hal/src/rtl872x/exflash_hal.cpp
  platform/MCU/rtl872x/src/flash_mal.c
  platform/MCU/rtl872x/src/hw_config.c
Labels: 5.x, 5.x-only

#2591 [test] bump fastpin max limit to 10%
  user/tests/wiring/no_fixture/fastpin.cpp
Labels: internal, 5.x-only

#2555 Initial support for BG95-M6 modem [sc-110723]
  hal/network/ncp_client/quectel/quectel_ncp_client.cpp
  hal/network/ncp_client/quectel/quectel_ncp_client.h
  hal/shared/cellular_enums_hal.h
  hal/shared/cellular_ncp_dev_mapping.h
  hal/shared/platform_ncp.h
  hal/src/b5som/platform_ncp_quectel.cpp
  hal/src/tracker/platform_ncp_quectel.cpp
  hal/src/trackerm/platform_ncp_quectel.cpp
Labels: feature, backport, 4.x, 5.x

#2594 [rtl872x] hal: remove an assert in read()/peek() and instead adjust read/peek size
  hal/src/rtl872x/usart_hal.cpp
Labels: bug, 5.x-only
