Repository particle-iot/device-os, pull requests merged in 2022-09, with the labels that each got.

#2530 Secures DCT initialization from getting interrupted between creating DCT file and filling it with 0xff to default state
  bootloader/src/nRF52840/usbd_device.cpp
  bootloader/src/nRF52840/usbd_dfu_mal.cpp
  bootloader/src/nRF52840/usbd_dfu_mal.h
  bootloader/src/rtl872x/usb_hal.cpp
  bootloader/src/rtl872x/usbd_dfu_mal.cpp
  bootloader/src/rtl872x/usbd_dfu_mal.h
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/dct_hal.cpp
  hal/src/rtl872x/core_hal.c
  hal/src/rtl872x/dct_hal.cpp
  platform/MCU/nRF52840/inc/dcd_flash_impl.h
  platform/MCU/nRF52840/inc/flash_storage_impl.h
  platform/MCU/rtl872x/inc/dcd_flash_impl.h
  platform/MCU/rtl872x/inc/flash_storage_impl.h
  services/inc/dcd.h
  services/inc/dct_file.h
  system/src/system_cloud_internal.cpp
  test/unit_tests/services/CMakeLists.txt
  test/unit_tests/services/dcd.cpp
Labels: 4.x, 5.x

#2532 fix issue with platform_ncp_get_info(0) for some of the platforms
  hal/src/tracker/platform_ncp_quectel.cpp
  hal/src/trackerm/platform_ncp_quectel.cpp
  hal/src/tron/platform_ncp.cpp
Labels: bug, 4.x, 5.x

#2525 [rtl8721x] update rtl872x.tcl script for latest openocd version
  scripts/rtl872x.tcl
Labels: internal, 5.x

#2537 [rtl872x] hal: fix fetching of MAC addresses
  hal/src/rtl872x/deviceid_hal.cpp
Labels: bug, 5.x

#2538 Fix BLE control request channel sending malformed packets
  system/src/ble_control_request_channel.cpp
Labels: bug, 4.x, 5.x

#2536 [wiring] ApplicationWatchdog: fixes potential 2x timeout required to fire
  user/tests/wiring/no_fixture/thread.cpp
  wiring/inc/spark_wiring_thread.h
  wiring/inc/spark_wiring_watchdog.h
  wiring_globals/src/spark_wiring_watchdog.cpp
Labels: bug, 4.x, 5.x

#2539 [hal] wifi: add generic 'world' country code as not every country code is exposed through API
  hal/inc/wlan_hal.h
  hal/network/ncp_client/realtek/rtl_ncp_client.cpp
Labels: 4.x, 5.x

#2541 [rtl872x] usb: make sure CDC line coding struct is packed
  hal/src/rtl872x/usbd_cdc.h
Labels: bug, 5.x

#2546 [rtl872x] ADC accuracy
  hal/inc/adc_hal.h
  hal/inc/hal_dynalib_gpio.h
  hal/src/nRF52840/adc_hal.cpp
  hal/src/rtl872x/adc_hal.cpp
  hal/src/template/adc_hal.cpp
  services/inc/system_cache.h
  wiring/inc/spark_wiring.h
  wiring_globals/src/spark_wiring_gpio.cpp
Labels: 5.x
