Repository particle-iot/device-os, pull requests merged in 2022-02, with the labels that each got.

#2395 [CI] Migration to CircleCI
  .buildpackrc
  .circleci/config.yml
  .gitignore
  .travis.yml
  bootloader/build.mk
  build/release.sh
  ci/cf_generate_message.sh
  ci/ci_release.sh
  ci/combine_binaries.sh
  ci/enumerate_build_matrix.sh
  ci/install_gcovr.sh
  ci/report/LICENSE
  ci/report/report.py
  ci/run_tests.sh
  ci/unit_tests.sh
  scripts/fetch-buildpack
  services/inc/logging.h
  test/unit_tests/CMakeLists.txt
Labels: enhancement

#2390 Thread/interrupt safety for system_event_t subscriptions, support for unsubscribing
  system/inc/system_dynalib.h
  system/inc/system_event.h
  system/src/system_event.cpp
  user/tests/wiring/api/system.cpp
  user/tests/wiring/no_fixture/system.cpp
  wiring/inc/spark_wiring_system.h
Labels: bug, enhancement

#2382 [Gen3] BLE Provisioning Mode
  hal/inc/core_hal.h
  hal/inc/device_code.h
  hal/inc/deviceid_hal.h
  hal/inc/hal_dynalib_core.h
  hal/network/lwip/esp32/esp32ncpnetif.cpp
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/device_code.cpp
  hal/src/nRF52840/deviceid_hal.cpp
  hal/src/stm32f2xx/deviceid_hal.cpp
  platform/MCU/nRF52840/inc/dct.h
  system/inc/system_ble_prov.h
  system/inc/system_control.h
  system/inc/system_dynalib.h
  system/inc/system_event.h
  system/src/ble_control_request_channel.cpp
  system/src/ble_control_request_channel.h
  system/src/ble_provisioning_mode_handler.cpp
  system/src/ble_provisioning_mode_handler.h
  system/src/control/wifi_new.cpp
  system/src/system_ble_prov.cpp
  system/src/system_control_internal.cpp
  system/src/system_control_internal.h
  system/src/system_listening_mode.cpp
  system/src/system_listening_mode.h
  system/src/system_task.cpp
  user/tests/app/ble/prov_mode/application.cpp
  user/tests/wiring/no_fixture/ble_provisioning.cpp
  user/tests/wiring/no_fixture/fastpin.cpp
  user/tests/wiring/no_fixture/system.cpp
  wiring/inc/spark_wiring_ble.h
  wiring/inc/spark_wiring_system.h
  wiring/src/spark_wiring_ble.cpp
Labels: needs review
