Repository particle-iot/device-os, pull requests merged in 2023-10, with the labels that each got.

#2702 [system] still pump system loop when SPARK_WLAN_SLEEP=1; Try to drain ISR task queue quicker
  system/src/system_task.cpp
Labels: bug, backport, 4.x, 5.x

#2703 [rtl872x] Fix unintentional pin changes for Serial1 RTS/CTS
  hal/src/rtl872x/usart_hal.cpp
Labels: bug, 5.x, 5.x-only

#2706 [msom] increase NCP baudrate to 921600, doubling throughput
  hal/network/ncp_client/quectel/quectel_ncp_client.cpp
  hal/network/ncp_client/quectel/quectel_ncp_client.h
Labels: enhancement, 5.x, 5.x-only
