Repository particle-iot/device-os, pull requests merged in 2023-03, with the labels that each got.

#2636 [rtl872x] ble: start BLE stack/event dispatching before a connection attempt
  hal/src/rtl872x/ble_hal.cpp
Labels: bug, 5.x-only

#2638 [rtl872x] usb: force SDK to pass recipient=interface requests by faking type=class
  hal/src/rtl872x/usbd_driver.cpp
Labels: bug

#2639 [r510] enable PS (packet switched) Only mode for R510 modems (Boron/BSoM/ESoMX)
  hal/network/ncp/cellular/cellular_ncp_client.h
  hal/network/ncp_client/sara/sara_ncp_client.cpp
  hal/network/ncp_client/sara/sara_ncp_client.h
  services/inc/system_cache.h
Labels: 5.x
