Repository particle-iot/device-os, pull requests merged in 2023-09, with the labels that each got.

#2694 [services] add long long support to printf/scanf
  build/arm-tools.mk
  services/src/printf_export.c
  services/src/scanf_export.c
  user/tests/integration/wiring/strformat
  user/tests/wiring/strformat/application.cpp
  user/tests/wiring/strformat/printf_scanf.cpp
  user/tests/wiring/strformat/strformat.spec.js
  user/tests/wiring/strformat/test.mk
Labels: backport, 4.x, 5.x, 4.2.0

#2693 [wiring] Add 64-bit string conversions
  test/unit_tests/wiring/string.cpp
  wiring/inc/spark_wiring_string.h
  wiring/src/spark_wiring_string.cpp
Labels: backport, 5.x, 4.2.0

#2695 [wiring] json: 64-bit support
  test/unit_tests/wiring/json.cpp
  wiring/inc/spark_wiring_json.h
  wiring/src/spark_wiring_json.cpp
Labels: backport, 4.x, 5.x, 4.2.0

#2696 fix printf/scanf for floating point numbers, add tests
  hal/src/nRF52840/include.mk
  hal/src/rtl872x/include.mk
  modules/shared/nRF52840/part1_build.mk
  modules/shared/rtl872x/part1_build.mk
  services/inc/printf_export.h
  services/src/printf_export.c
  user/tests/wiring/strformat/printf_scanf.cpp
Labels: backport, 4.x, 5.x, 4.2.0

#2699 [rtl872x] correctly handle SecureFault
  bootloader/src/rtl872x/rtl_it.c
  bootloader/src/rtl872x/rtl_it.h
  hal/src/rtl872x/core_hal.c
  hal/src/rtl872x/interrupts_irq.h
  platform/MCU/rtl872x/src/hw_config.c
  services/inc/panic.h
Labels: 5.x-only

#2700 Fixes ncp-client not waiting for modem ready on cold boot
  hal/network/ncp_client/quectel/quectel_ncp_client.cpp
  hal/network/ncp_client/quectel/quectel_ncp_client.h
Labels: bug, 4.x, 5.x
