Repository particle-iot/device-os, pull requests merged in 2023-06, with the labels that each got.

#2659 [rtl872x] usb: HID
  hal/src/rtl872x/usb_hal.cpp
  hal/src/rtl872x/usb_hal_hid.cpp
  hal/src/rtl872x/usbd_cdc.cpp
  hal/src/rtl872x/usbd_cdc.h
  hal/src/rtl872x/usbd_device.cpp
  hal/src/rtl872x/usbd_driver.cpp
  hal/src/rtl872x/usbd_driver.h
  hal/src/rtl872x/usbd_hid.cpp
  hal/src/rtl872x/usbd_hid.h
  user/tests/wiring/usbhid2/usbhid.py
  wiring/inc/spark_wiring_platform.h
  wiring/inc/spark_wiring_usbkeyboard.h
  wiring/inc/spark_wiring_usbmouse.h
  wiring/src/spark_wiring_usbkeyboard.cpp
  wiring/src/spark_wiring_usbmouse.cpp
Labels: feature, 5.x-only

#2658 Combined MFG firmware
  bootloader/src/main.c
  platform/MCU/rtl872x/inc/flash_access.h
  platform/MCU/rtl872x/inc/flash_mal.h
  platform/MCU/rtl872x/src/flash_mal.c
Labels: needs review, feature

#2661 Fixes clean target for applications with large number of fils + P2 PSRAM size calculation issues
  build/module.mk
  modules/shared/rtl872x/build_linker_script.mk
Labels: bug

#2665 [rtl872x] linker: stop relying on .dynalib + .psram_text being contiguous and properly and similarly aligned within LMA and VMA, just copy them separately
  bootloader/src/rtl872x/linker.ld
  build/arm/startup/startup_rtl872x.S
  hal/src/rtl872x/linker.ld
  modules/shared/rtl872x/inc/user_part_export.c
  modules/shared/rtl872x/linker_system_part1_common.ld
  modules/shared/rtl872x/linker_user_part_common.ld
Labels: bug
