Repository particle-iot/device-os, pull requests merged in 2023-02, with the labels that each got.

#2618 [ci] Fix gcc and newhal builds
  ci/run_tests.sh
  hal/inc/watchdog_hal.h
  system/src/server_config.cpp
  system/src/system_cloud_internal.cpp
  user/tests/libraries/unit-test/ParticleFunbag.cpp
Labels: internal, 4.x, 5.x

#2616 Ethernet GPIO config
  hal/inc/hal_platform.h
  hal/network/api/ifapi.h
  hal/network/lwip/ifapi.cpp
  hal/network/lwip/wiznet/wiznetif.cpp
  hal/network/lwip/wiznet/wiznetif_config.cpp
  hal/network/lwip/wiznet/wiznetif_config.h
  hal/src/argon/hal_platform_config.h
  hal/src/argon/network/network.cpp
  hal/src/b5som/hal_platform_config.h
  hal/src/b5som/network/network.cpp
  hal/src/boron/hal_platform_config.h
  hal/src/boron/network/network.cpp
  hal/src/nRF52840/interrupts_hal.cpp
  hal/src/rtl872x/interrupts_hal.cpp
  hal/src/tracker/hal_platform_config.h
  hal/src/tracker/network/network.cpp
  hal/src/trackerm/hal_platform_config.h
  hal/src/trackerm/network/network.cpp
  hal/src/tron/hal_platform_config.h
  hal/src/tron/network/network.cpp
  services/inc/system_cache.h
  user/tests/app/ethernet/ethernet.cpp
Labels: feature, 5.x-only

#2622 Ensure thread07 test executes as intended
  system/inc/active_object.h
  system/inc/system_cloud.h
  system/inc/system_dynalib_cloud.h
  system/src/system_cloud.cpp
  user/tests/wiring/no_fixture/ble_provisioning.cpp
  user/tests/wiring/no_fixture/tcp.cpp
  user/tests/wiring/no_fixture/thread.cpp
  user/tests/wiring/no_fixture/time.cpp
  wiring/inc/spark_wiring_cloud.h
Labels: 5.x-only

#2624 [rtl872x] hal: fix heap allocation issue in interrupt hal and postpone the mode button initialization.
  hal/src/rtl872x/core_hal.c
  hal/src/rtl872x/interrupts_hal.cpp
  platform/MCU/rtl872x/src/hw_config.c
  user/tests/wiring/shared_interrupt/shared_interrupt.cpp
Labels: bug, 5.x-only

#2626 [rtl872x] Fix watchdog tests; system/application thread stack size increase
  hal/inc/hal_platform.h
  hal/src/rtl872x/core_hal.c
  hal/src/rtl872x/hal_platform_rtl8721x_config.h
  hal/src/rtl872x/sleep_hal.cpp
  system/src/system_threading.cpp
  user/tests/wiring/watchdog/watchdog.cpp
Labels: bug, 5.x-only

#2627 [test] turn off NCP before testing wiring/watchdog
  user/tests/wiring/watchdog/watchdog.cpp
  user/tests/wiring/watchdog/watchdog.spec.js
Labels: 5.x-only

#2628 [rtl872x] bootloader: fix destination address flash page alignment in case of compressed modules
  platform/MCU/rtl872x/src/flash_mal.c
Labels: bug, 5.x-only
