Repository particle-iot/device-os, pull requests merged in 2023-01, with the labels that each got.

#2570 Server key rotation
  communication/inc/coap.h
  communication/inc/protocol.h
  communication/inc/spark_protocol_functions.h
  communication/src/messages.cpp
  communication/src/protocol.cpp
  hal/inc/ota_flash_hal.h
  hal/shared/parse_server_address.h
  hal/src/gcc/ota_flash_hal.cpp
  hal/src/nRF52840/ota_flash_hal.cpp
  hal/src/rtl872x/ota_flash_hal.cpp
  platform/MCU/nRF52840/inc/nrfx_glue.h
  services/inc/system_defs.h
  services/inc/system_error.h
  system/inc/system_cloud.h
  system/src/main.cpp
  system/src/server_config.cpp
  system/src/server_config.h
  system/src/system_cloud_connection.cpp
  system/src/system_cloud_internal.cpp
  system/src/system_cloud_internal_constants.c
  test/unit_tests/communication/CMakeLists.txt
  test/unit_tests/mock/core_hal_mock.cpp
  test/unit_tests/mock/core_hal_mock.h
  test/unit_tests/mock/dct_hal_mock.cpp
  test/unit_tests/mock/dct_hal_mock.h
  test/unit_tests/mock/mbedtls_mock.cpp
  test/unit_tests/mock/mbedtls_mock.h
  test/unit_tests/stub/core_hal.cpp
  test/unit_tests/stub/dct.h
  test/unit_tests/stub/dct_hal.cpp
  test/unit_tests/stub/dct_hal.h
  test/unit_tests/stub/mbedtls/asn1.cpp
  test/unit_tests/stub/mbedtls/asn1.h
  test/unit_tests/stub/mbedtls/md.cpp
  test/unit_tests/stub/mbedtls/md.h
  test/unit_tests/stub/mbedtls/pk.cpp
  test/unit_tests/stub/mbedtls/pk.h
  test/unit_tests/stub/mbedtls_util.cpp
  test/unit_tests/stub/sha256.h
  test/unit_tests/system/CMakeLists.txt
  test/unit_tests/system/server_config.cpp
  third_party/nrf5_sdk/build.mk
Labels: feature, 5.x

#2613 Fix GCC platform build
  system/src/server_config.cpp
  system/src/system_cloud_internal.cpp
Labels: bug, 5.x

#2612 [rtl872x] enable factory reset feature
  system/src/main.cpp
Labels: bug, 5.x-only

#2611 [test] mailbox support and support for resets within tests
  user/tests/integration/application/src/request_handler.cpp
  user/tests/integration/application/src/request_handler.h
  user/tests/integration/runner/mailbox/mailbox.cpp
  user/tests/integration/runner/mailbox/mailbox.spec.js
  user/tests/integration/slo/application_max_size/application_max_size.cpp
  user/tests/integration/slo/connect_time/connect_time.cpp
  user/tests/integration/slo/connect_time/connect_time.spec.js
  user/tests/libraries/unit-test/ParticleFunbag.cpp
  user/tests/libraries/unit-test/unit-test.h
  user/tests/wiring/no_fixture/system.cpp
Labels: internal, feature, 4.x, 5.x

#2595 Feature: supports hardware watchdog
  bootloader/prebootloader/src/rtl872x/part1/rtl_support.c
  hal-dynalib/src/hal_watchdog.c
  hal/inc/hal_dynalib_core.h
  hal/inc/hal_dynalib_watchdog.h
  hal/inc/hal_platform.h
  hal/inc/watchdog_base.h
  hal/inc/watchdog_hal.h
  hal/src/gcc/core_hal.cpp
  hal/src/gcc/watchdog_hal.cpp
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/delay_hal.cpp
  hal/src/nRF52840/hal_dynalib_export.cpp
  hal/src/nRF52840/hal_platform_nrf52840_config.h
  hal/src/nRF52840/watchdog_hal.c
  hal/src/nRF52840/watchdog_hal.cpp
  hal/src/rtl872x/core_hal.c
  hal/src/rtl872x/hal_dynalib_export.cpp
  hal/src/rtl872x/hal_platform_rtl8721x_config.h
  hal/src/rtl872x/rtl_sdk_support.cpp
  hal/src/rtl872x/watchdog_hal.cpp
  hal/src/template/core_hal.cpp
  hal/src/template/watchdog_hal.cpp
  modules/argon/system-part1/module_system_part1_export.ld
  modules/b5som/system-part1/module_system_part1_export.ld
  modules/boron/system-part1/module_system_part1_export.ld
  modules/shared/nRF52840/inc/system-part1/module_system_part1.inc
  modules/shared/rtl872x/inc/system-part1/module_system_part1.inc
  modules/tracker/system-part1/module_system_part1_export.ld
  modules/trackerm/system-part1/module_system_part1_export.ld
  modules/tron/system-part1/module_system_part1_export.ld
  platform/MCU/nRF52840/src/hw_config.c
  platform/MCU/rtl872x/src/hw_config.c
  system/src/main.cpp
  system/src/system_task.cpp
  user/tests/integration/wiring/watchdog
  user/tests/wiring/api/watchdog.cpp
  user/tests/wiring/watchdog/application.cpp
  user/tests/wiring/watchdog/test.mk
  user/tests/wiring/watchdog/watchdog.cpp
  user/tests/wiring/watchdog/watchdog.spec.js
  wiring/inc/spark_wiring_platform.h
  wiring/inc/spark_wiring_watchdog.h
  wiring/src/spark_wiring_watchdog.cpp
Labels: bootloader, 4.x, 5.x
