Repository particle-iot/device-os, pull requests merged in 2023-04, with the labels that each got.

#2634 [rtl872x] hal: I2C may fail to read/write from/to slave device.
  hal/src/rtl872x/i2c_hal.cpp
Labels: bug, needs review, backport, 5.x

#2643 [rtl872x] hal: uart may deadlock on initialization.
  hal/src/rtl872x/usart_hal.cpp
Labels: bug

#2645 minor fix to ensure PS only mode is only applied to R510 at this time
  hal/network/ncp_client/sara/sara_ncp_client.cpp
Labels: backport, 5.x

#2652 [nRF52] UART sleep/wakeup
  hal/src/nRF52840/sleep_hal.cpp
Labels: bug, 4.x, 5.x
