Repository particle-iot/device-os, pull requests merged in 2024-12, with the labels that each got.

#2843 [gen3] fix internal -> external flash writes
  bootloader/prebootloader/src/rtl872x/mbr/sources.mk
  bootloader/prebootloader/src/rtl872x/part1/linker.ld
  bootloader/prebootloader/src/rtl872x/part1/sources.mk
  bootloader/src/rtl872x/sources.mk
  hal/inc/hal_platform.h
  hal/shared/flash_common.cpp
  hal/shared/flash_common.h
  hal/src/nRF52840/exflash_hal.cpp
  hal/src/nRF52840/flash_hal.c
  hal/src/nRF52840/hal_platform_nrf52840_config.h
  hal/src/rtl872x/exflash_hal.cpp
  hal/src/rtl872x/exflash_hal_lock.cpp
  hal/src/rtl872x/flash_common.cpp
  hal/src/rtl872x/flash_common.h
  hal/src/rtl872x/hal_platform_rtl8721x_config.h
  user/tests/wiring/no_fixture_stress/exflash.cpp
Labels: bug

#2845 [r510] ensures LTE Cat-M1 band 71 is disabled
  hal/network/ncp_client/sara/sara_ncp_client.cpp
Labels: bug, 6.x

#2836 [Gen4] fixes a BLE lockup circumstance
  hal/src/rtl872x/ble_hal.cpp
  wiring/src/spark_wiring_ble.cpp
Labels: bug, ble

#2839 [Gen4] ble: clear connecting flag on connected for peripheral role
  hal/src/rtl872x/ble_hal.cpp
Labels: bug, ble

#2847 [network] postpone ethernet interface initialization to allow STARTUP() call to override pin configuration without a reset
  hal/inc/hal_platform.h
  hal/network/lwip/wiznet/wiznetif.cpp
  hal/network/lwip/wiznet/wiznetif.h
  hal/src/argon/network/network.cpp
  hal/src/b5som/network/network.cpp
  hal/src/boron/network/network.cpp
  hal/src/msom/network/network.cpp
  hal/src/tracker/network/network.cpp
  hal/src/trackerm/network/network.cpp
  hal/src/tron/network/network.cpp
  system/src/system_power.cpp
Labels: enhancement, documentation

#2846 [network] fixes Ethernet default config/validation, minor optimizations
  hal/network/lwip/wiznet/wiznetif.cpp
  hal/network/lwip/wiznet/wiznetif_config.cpp
  user/tests/app/connection-manager/application.cpp
  user/tests/app/ethernet/ethernet.cpp
  user/tests/wiring/network_config/network_config.cpp
Labels: bug, documentation

#2849 [gen4] wifi: use BSSID from scan result, always perform scans before connect
  hal/network/ncp/wifi/wifi_network_manager.cpp
  hal/network/ncp_client/realtek/rtl_ncp_client.cpp
  hal/src/rtl872x/i2c_hal.cpp
Labels: enhancement

#2850 [u-blox][r510] fixes EHS timing when modem locks up while in Power Saving mode
  hal/network/ncp_client/sara/sara_ncp_client.cpp
  hal/network/ncp_client/sara/sara_ncp_client.h
Labels: bug, 6.x
