Repository particle-iot/device-os, pull requests merged in 2024-08, with the labels that each got.

#2805 [Gen 4] WiFi stuff
  hal/network/ncp_client/realtek/rtl_ncp_client.cpp
  hal/network/ncp_client/realtek/rtl_ncp_client.h
  hal/src/rtl872x/ble_hal.cpp
Labels: bug, enhancement

#2800 [rtl872x] fixes DMA enabled USART flush
  hal/src/rtl872x/usart_hal.cpp
Labels: bug, 5.x-only

#2796 Fix/ble stop scanning
  hal/src/nRF52840/ble_hal.cpp
  hal/src/rtl872x/ble_hal.cpp
  user/tests/wiring/ble_central_peripheral/ble_central/central.cpp
  user/tests/wiring/ble_central_peripheral/ble_peripheral/peripheral.cpp
  user/tests/wiring/no_fixture_ble/ble.cpp
  wiring/inc/spark_wiring_ble.h
  wiring/src/spark_wiring_ble.cpp
Labels: bug, 5.x

#2813 Gen4 BLE fixes
  hal/src/rtl872x/ble_hal.cpp
  user/tests/wiring/ble_central_peripheral/ble_central/central.cpp
  user/tests/wiring/ble_central_peripheral/ble_peripheral/peripheral.cpp
Labels: ble, 5.x

#2803 [cellular][r510] unmask bands for global use
  hal/network/ncp/cellular/cellular_ncp_client.h
  hal/network/ncp_client/sara/sara_ncp_client.cpp
Labels: enhancement, 5.x

#2819 [Gen4] clear I2C tx buffer per transmission
  hal/src/rtl872x/i2c_hal.cpp
Labels: bug, 5.x

#2816 Add serial loopback to test runner
  hal/inc/hal_dynalib_usart.h
  hal/inc/usart_hal.h
  hal/src/nRF52840/usart_hal.cpp
  hal/src/rtl872x/usart_hal.cpp
  user/tests/integration/wiring/serial_loopback
  user/tests/integration/wiring/serial_loopback2
  user/tests/wiring/serial_loopback/application.cpp
  user/tests/wiring/serial_loopback/readme.md
  user/tests/wiring/serial_loopback/serial.cpp
  user/tests/wiring/serial_loopback/serial_loopback.config.json
  user/tests/wiring/serial_loopback/serial_loopback.spec.js
  user/tests/wiring/serial_loopback2/README.md
  user/tests/wiring/serial_loopback2/application.cpp
  user/tests/wiring/serial_loopback2/loopback.cpp
  user/tests/wiring/serial_loopback2/serial_loopback2.config.json
  user/tests/wiring/serial_loopback2/serial_loopback2.spec.js
Labels: bug, 5.x

#2818 [Gen4] fixes BLE race condition while scanning
  hal/src/rtl872x/ble_hal.cpp
Labels: bug, 5.x

#2801 [Gen3] hal: improves BLE connect and discovery procedure.
  hal/inc/hal_platform.h
  hal/src/nRF52840/ble_hal.cpp
  hal/src/rtl872x/ble_hal.cpp
  hal/src/rtl872x/hal_platform_rtl8721x_config.h
  user/tests/wiring/ble_central_peripheral/ble_central/central.cpp
  user/tests/wiring/ble_central_peripheral/ble_peripheral/peripheral.cpp
  wiring/src/spark_wiring_ble.cpp
Labels: bug, enhancement, 5.x

#2814 [tests] Support integration tests on gen4 after device-constants update
  user/tests/integration/communication/events/events.spec.js
  user/tests/integration/communication/functions/functions.spec.js
  user/tests/integration/communication/ledger/ledger.spec.js
  user/tests/integration/communication/variables/variables.spec.js
  user/tests/integration/ota/assets/assets.spec.js
  user/tests/integration/ota/min_max_app_size/min_max_app_size.spec.js
  user/tests/integration/ota/multiple_ota_no_reset/multiple_ota_no_reset.spec.js
  user/tests/integration/package-lock.json
  user/tests/integration/package.json
  user/tests/integration/runner/mailbox/mailbox.spec.js
  user/tests/integration/slo/application_max_size/application_max_size.spec.js
  user/tests/integration/slo/connect_time/connect_time.spec.js
  user/tests/integration/slo/startup/startup-slos.spec.js
  user/tests/wiring/ble_central_peripheral/ble_central_peripheral.spec.js
  user/tests/wiring/ble_scanner_broadcaster/ble_scanner_broadcaster.spec.js
  user/tests/wiring/filesystem/filesystem.spec.js
  user/tests/wiring/gen3_invalid_compat_user_app/gen3_invalid_compat_user_app.spec.js
  user/tests/wiring/ledger/ledger.spec.js
  user/tests/wiring/network_config/network_config.spec.js
  user/tests/wiring/no_fixture/no_fixture.spec.js
  user/tests/wiring/no_fixture_ble/no_fixture_ble.spec.js
  user/tests/wiring/no_fixture_i2c/no_fixture_i2c.spec.js
  user/tests/wiring/no_fixture_long_running/no_fixture_long_running.spec.js
  user/tests/wiring/no_fixture_spi/no_fixture_spi.spec.js
  user/tests/wiring/no_fixture_stress/no_fixture_stress.spec.js
  user/tests/wiring/strformat/strformat.spec.js
  user/tests/wiring/time_compat/time_compat.spec.js
  user/tests/wiring/watchdog/watchdog.spec.js
Labels: internal
