Repository particle-iot/device-os, pull requests merged in 2024-07, with the labels that each got.

#2797 Reduce latency of the system loop
  hal/src/nRF52840/concurrent_hal.cpp
  hal/src/rtl872x/concurrent_hal.cpp
Labels: bug

#2799 [gen3] increase system-part1 size
  bootloader/src/nRF52840/dfu_usb.c
  build/arm-tools.mk
  build/arm/linker/linker_module_info_ext.ld
  build/arm/linker/linker_module_start_ext.ld
  build/arm/linker/nrf52840/linker_nrf52840_sdk_ram.ld
  build/arm/linker/nrf52840/platform_flash.ld
  build/platform-id.mk
  hal/src/nRF52840/ota_module_bounds.c
  modules/argon/system-part1/linker.ld
  modules/argon/system-part1/makefile
  modules/b5som/system-part1/linker.ld
  modules/b5som/system-part1/makefile
  modules/boron/system-part1/linker.ld
  modules/boron/system-part1/makefile
  modules/shared/nRF52840/linker_system_part1_common.ld
  modules/tracker/system-part1/linker.ld
  modules/tracker/system-part1/makefile
  platform/MCU/nRF52840/inc/flash_mal.h
  platform/MCU/nRF52840/src/hw_config.c
Labels: feature, 6.x

#2798 Work around a bug in lfs_remove()
  services/src/file_util.cpp
Labels: bug

#2802 Device protection fixes
  bootloader/src/nRF52840/usbd_dfu.cpp
  bootloader/src/nRF52840/usbd_dfu.h
  bootloader/src/rtl872x/usbd_dfu.cpp
  bootloader/src/rtl872x/usbd_dfu.h
Labels: bug, 6.x

#2791 Export hal_spi_get_clock_divider()
  hal/inc/hal_dynalib_spi.h
Labels: 6.x

#2793 [system] battery state might be wrong when it is detached
  system/src/system_power_manager.cpp
Labels: 6.x

#2777 [system] power: add method to specify the PMIC/FuelGauge interrupt pin.
  hal/inc/power_hal.h
  system/src/system_power_manager.cpp
  system/src/system_power_manager.h
  wiring/inc/spark_wiring_system_power.h
Labels: 6.x

#2775 Makes the Ethernet interrupt pin optional.
  hal/network/lwip/wiznet/wiznetif.cpp
  hal/network/lwip/wiznet/wiznetif_config.cpp
Labels: enhancement, documentation, 6.x

#2794 Makes the Ethernet reset pin optional.
  hal/network/lwip/wiznet/wiznetif.cpp
  hal/network/lwip/wiznet/wiznetif.h
  hal/network/lwip/wiznet/wiznetif_config.cpp
  hal/src/b5som/network/network.cpp
  hal/src/boron/network/network.cpp
  hal/src/msom/network/network.cpp
Labels: 6.x
