Repository particle-iot/device-os, pull requests merged in 2024-09, with the labels that each got.

#2825 [gen4] prebootloader: fix STOP/ULP sleep with disabled rtos, get correct wake-up reason
  bootloader/prebootloader/src/rtl872x/part1/sleep_handler.cpp
Labels: bug

#2795 [tests] wiring/acm: test-runner runnable ACM fixture test
  user/tests/integration/wiring/acm
  user/tests/wiring/acm/acm.config.js
  user/tests/wiring/acm/acm.cpp
  user/tests/wiring/acm/acm.spec.js
  user/tests/wiring/acm/application.cpp
  user/tests/wiring/acm/test.mk
Labels: internal

#2827 5.9.0 fixes
  system/src/system_power_manager.cpp
  user/tests/integration/slo/startup/startup-slos.spec.js
  user/tests/wiring/no_fixture/i2c.cpp
Labels: internal

#2831 [gen3] make sure that extended system-part1 is compatible with older bootloaders as well as 6.1.2
  build/arm/linker/nrf52840/platform_flash.ld
  build/macros.mk
  build/module.mk
  dynalib/inc/module_info.inc
  hal/inc/hal_platform.h
  hal/src/nRF52840/core_hal.c
  hal/src/nRF52840/hal_platform_nrf52840_config.h
  hal/src/nRF52840/linker.ld
  modules/argon/system-part1/linker.ld
  modules/b5som/system-part1/linker.ld
  modules/boron/system-part1/linker.ld
  modules/shared/nRF52840/inc/system_part1_loader.c
  modules/shared/nRF52840/linker_system_part1_common.ld
  modules/shared/rtl872x/inc/system_part1_loader.c
  modules/tracker/system-part1/linker.ld
  platform/MCU/nRF52840/src/hw_config.c
Labels: enhancement
