Repository particle-iot/device-os, pull requests merged in 2024-02, with the labels that each got.

#2735 Improve bg95 connection speed by only setting nwscanseq if needed
  hal/network/ncp_client/quectel/quectel_ncp_client.cpp
Labels: bug, 5.x-only

#2736 [system] Fix bad int to bool conversion for clearCredentials
  system/inc/system_network.h
  system/src/system_network_manager_api.cpp
Labels: 5.x, 6.x

#2740 [tracker] disable esp32 sdio driver text logs
  hal/src/tracker/sdspi/port.h
Labels: internal, 5.x, 6.x

#2742 [rtl872x] ota: fix bounds check, add ota/min_max_app_size test
  hal/inc/ota_flash_hal.h
  hal/src/gcc/ota_flash_hal.cpp
  hal/src/rtl872x/ota_module.cpp
  hal/src/rtl872x/ota_module_bounds.c
  user/tests/integration/ota/min_max_app_size/min_max_app_size.cpp
  user/tests/integration/ota/min_max_app_size/min_max_app_size.spec.js
  user/tests/integration/package-lock.json
  user/tests/integration/package.json
Labels: bug

#2743 Fixes std::call_once reentrancy problem
  hal/src/nRF52840/bits/gthr.cpp
  hal/src/nRF52840/include.mk
  hal/src/nRF52840/sources.mk
  hal/src/portable/FreeRTOS/bits/gthr-default.h
  hal/src/portable/FreeRTOS/bits/gthr.cpp
  hal/src/rtl872x/bits/gthr-default.h
  hal/src/rtl872x/bits/gthr.cpp
  hal/src/rtl872x/include.mk
  hal/src/rtl872x/sources.mk
  system/src/system_threading.cpp
Labels: internal
