Repository particle-iot/device-os, pull requests merged in 2024-03, with the labels that each got.

#2746 Add WiFi credential check
  hal/inc/wlan_hal.h
  hal/network/ncp/wifi/wifi_network_manager.cpp
  hal/network/ncp/wifi/wifi_network_manager.h
  hal/network/ncp/wifi/wlan_hal.cpp
  system/src/control/wifi_new.cpp
  user/tests/wiring/wifi_cred_check/application.cpp
  user/tests/wiring/wifi_cred_check/wifi_cred_check.cpp
  wiring/inc/spark_wiring_wifi_credentials.h
Labels: feature, 5.x

#2744 [rtl872x] fix usb high speed
  bootloader/src/rtl872x/usb_hal.cpp
  hal/src/rtl872x/usbd_driver.cpp
  hal/src/rtl872x/usbd_driver.h
  third_party/ambd_sdk/include.mk
Labels: bug, bootloader, 5.x-only

#2749 [rtl872x] hal: fix false TX DMA completion in SPI HAL.
  hal/src/rtl872x/spi_hal.cpp
Labels: bug, 5.x-only

#2751 Fix monolithic build errors.
  hal/inc/user_hal.h
  hal/src/nRF52840/user_hal.cpp
  hal/src/rtl872x/user_hal.cpp
  system/src/asset_manager.cpp
  system/src/ledger/ledger.cpp
  system/src/ledger/ledger_manager.cpp
Labels: bug, 5.x-only

#2750 [rtl872x] fix millis() may jump after ~37 hours.
  hal/src/rtl872x/timer_hal.cpp
Labels: bug, 5.x-only

#2755 [rtl872x] some more fixes
  hal/src/rtl872x/ble_hal.cpp
  hal/src/rtl872x/rtl_osdep.cpp
  hal/src/rtl872x/rtl_sdk_support.cpp
  hal/src/rtl872x/rtl_sdk_support.h
  system/src/system_connection_manager.cpp
Labels: bug

#2757 [rtl872x] SPI and UART HAL minor fix.
  hal/src/rtl872x/spi_hal.cpp
  hal/src/rtl872x/usart_hal.cpp
Labels: bug, 5.x-only

#2754 Refactor WiFi credential check; [Gen 4] WiFi thread safety issues, USB re-enumeration bugfix for weird USB hubs
  hal/network/lwip/esp32/esp32ncpnetif.cpp
  hal/network/lwip/realtek/rtlncpnetif.cpp
  hal/network/ncp/wifi/wifi_network_manager.cpp
  hal/network/ncp/wifi/wifi_network_manager.h
  hal/network/ncp/wifi/wlan_hal.cpp
  hal/network/ncp_client/realtek/rtl_ncp_client.cpp
  hal/network/ncp_client/realtek/rtl_ncp_client.h
  hal/src/rtl872x/lwip/lwip_rtlk.cpp
  hal/src/rtl872x/rtl_sdk_support.cpp
  hal/src/rtl872x/usbd_driver.cpp
  hal/src/rtl872x/usbd_driver.h
  system/src/control/wifi_new.cpp
  user/tests/wiring/wifi_cred_check/wifi_cred_check.cpp
  wiring/inc/spark_wiring_wifi.h
Labels: bug, needs review, DO NOT MERGE, 5.x-only

#2753 Fix msom usb + ble setup names
  bootloader/src/nRF52840/usbd_device.cpp
  build/platform-id.mk
  hal/src/b5som/app_usbd_string_config.h
  hal/src/boron/app_usbd_string_config.h
  hal/src/boron/hal_platform_config.h
  hal/src/msom/hal_platform_config.h
  hal/src/tron/hal_platform_config.h
Labels: DO NOT MERGE

#2758 [system] network: force IFF_UP if requested and no credentials exist
  system/inc/system_network.h
  system/src/control/wifi_new.cpp
  system/src/system_network_manager.cpp
  system/src/system_network_manager.h
  system/src/system_network_manager_api.cpp
Labels: bug
