Repository particle-iot/device-os, pull requests merged in 2024-06, with the labels that each got.

#2779 Display Photon 2 instead of P2, dont allow extended advertising data on rtl platforms
  bootloader/src/rtl872x/sources.mk
  hal/inc/device_code.h
  hal/src/nRF52840/ble_hal_impl.h
  hal/src/nRF52840/device_code.cpp
  hal/src/rtl872x/ble_hal_impl.h
  hal/src/rtl872x/device_code.cpp
  hal/src/rtl872x/usbd_cdc.cpp
  hal/src/rtl872x/usbd_control.cpp
  hal/src/rtl872x/usbd_device.cpp
  hal/src/tron/hal_platform_config.h
  system/src/ble_provisioning_mode_handler.cpp
  system/src/system_ble_prov.cpp
  user/applications/tinker/src/burnin_test.cpp
  user/applications/tinker/src/fqc_test.cpp
  wiring/src/spark_wiring_ble.cpp
Labels: bootloader

#2784 [rtl872x] SPI hal: set sample delay for SPI0@25MHz
  hal/src/rtl872x/spi_hal.cpp
Labels: 5.x

#2782 [eg91e][eg91ex] enable 921600 baud rate
  hal/network/ncp_client/quectel/quectel_ncp_client.cpp
  hal/network/ncp_client/quectel/quectel_ncp_client.h
Labels: feature, backport, 4.x, 5.x

#2787 [gen3] hal: fix gpio glitch
  hal/src/nRF52840/gpio_hal.cpp
Labels: backport, 4.x, 6.x
